
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cz.tacr.elza.ws.core.v1;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Component;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-09T13:06:28.035+01:00
 * Generated source version: 3.1.8
 * 
 */

@Component
@javax.jws.WebService(
                      serviceName = "CoreService",
                      portName = "DaoCoreService",
                      targetNamespace = "http://elza.tacr.cz/ws/core/v1",
//                      wsdlLocation = "file:elza-core-v1.wsdl",
                      endpointInterface = "cz.tacr.elza.ws.core.v1.DaoService")
                      
public class DaoCoreServiceImpl implements DaoService {

    private Log logger = LogFactory.getLog(this.getClass());

    /* (non-Javadoc)
     * @see cz.tacr.elza.ws.core.v1.DaoService#_import(cz.tacr.elza.ws.types.v1.DaoImport daoImport)*
     */
    public void _import(cz.tacr.elza.ws.types.v1.DaoImport daoImport) throws CoreServiceException   { 
        logger.info("Executing operation _import");
        // TODO ELZA-1300 - Zprovoznit webové služby - dopsat implementaci
        System.out.println(daoImport);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new CoreServiceException("CoreServiceException...");
    }

    /* (non-Javadoc)
     * @see cz.tacr.elza.ws.core.v1.DaoService#addPackage(cz.tacr.elza.ws.types.v1.DaoPackage daoPackage)*
     */
    public java.lang.String addPackage(cz.tacr.elza.ws.types.v1.DaoPackage daoPackage) throws CoreServiceException   { 
        logger.info("Executing operation addPackage");
        // TODO ELZA-1300 - Zprovoznit webové služby - dopsat implementaci
        System.out.println(daoPackage);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new CoreServiceException("CoreServiceException...");
    }

    /* (non-Javadoc)
     * @see cz.tacr.elza.ws.core.v1.DaoService#removePackage(java.lang.String packageIdentifier)*
     */
    public void removePackage(java.lang.String packageIdentifier) throws CoreServiceException   { 
        logger.info("Executing operation removePackage");
        // TODO ELZA-1300 - Zprovoznit webové služby - dopsat implementaci
        System.out.println(packageIdentifier);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new CoreServiceException("CoreServiceException...");
    }

    /* (non-Javadoc)
     * @see cz.tacr.elza.ws.core.v1.DaoService#getDid(java.lang.String packageIdentifier)*
     */
    public cz.tacr.elza.ws.types.v1.Did getDid(java.lang.String packageIdentifier) throws CoreServiceException   { 
        logger.info("Executing operation getDid");
        // TODO ELZA-1300 - Zprovoznit webové služby - dopsat implementaci
        System.out.println(packageIdentifier);
        try {
            cz.tacr.elza.ws.types.v1.Did _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new CoreServiceException("CoreServiceException...");
    }

    /* (non-Javadoc)
     * @see cz.tacr.elza.ws.core.v1.DaoService#link(cz.tacr.elza.ws.types.v1.DaoLink daoLink)*
     */
    public void link(cz.tacr.elza.ws.types.v1.DaoLink daoLink) throws CoreServiceException   { 
        logger.info("Executing operation link");
        // TODO ELZA-1300 - Zprovoznit webové služby - dopsat implementaci
        System.out.println(daoLink);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new CoreServiceException("CoreServiceException...");
    }

    /* (non-Javadoc)
     * @see cz.tacr.elza.ws.core.v1.DaoService#removeDao(java.lang.String packageIdentifier)*
     */
    public void removeDao(java.lang.String packageIdentifier) throws CoreServiceException   { 
        logger.info("Executing operation removeDao");
        // TODO ELZA-1300 - Zprovoznit webové služby - dopsat implementaci
        System.out.println(packageIdentifier);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new CoreServiceException("CoreServiceException...");
    }

}
