
package cz.tacr.elza.ws.core.v1;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-09T13:06:28.072+01:00
 * Generated source version: 3.1.8
 * 
 */
 
public class DaoDigitizationService_DaoDigitizationService_Server{

    protected DaoDigitizationService_DaoDigitizationService_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new DaoDigitizationServiceImpl();
        String address = "http://elza.tacr.cz/ws/core/v1/dao-service/digitization";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new DaoDigitizationService_DaoDigitizationService_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
