
package cz.tacr.elza.ws.core.v1;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-09T13:06:28.073+01:00
 * Generated source version: 3.1.8
 * 
 */
 
public class DaoRequestsService_DaoRequestsService_Server{

    protected DaoRequestsService_DaoRequestsService_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new DaoRequestsServiceImpl();
        String address = "http://elza.tacr.cz/ws/core/v1/dao-service/requests";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new DaoRequestsService_DaoRequestsService_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
