package cz.tacr.elza.ws.core.v1;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-09T13:06:28.068+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://elza.tacr.cz/ws/core/v1", name = "DaoRequestsService")
@XmlSeeAlso({cz.tacr.elza.ws.types.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DaoRequestsService {

    @WebMethod(operationName = "DestructionRequestRevoked")
    @Oneway
    public void destructionRequestRevoked(
        @WebParam(partName = "requestRevoked", name = "requestRevoked", targetNamespace = "")
        cz.tacr.elza.ws.types.v1.RequestRevoked requestRevoked
    ) throws CoreServiceException;

    @WebMethod(operationName = "TransferRequestFinished")
    @Oneway
    public void transferRequestFinished(
        @WebParam(partName = "requestIdentifier", name = "requestIdentifier", targetNamespace = "")
        java.lang.String requestIdentifier
    ) throws CoreServiceException;

    @WebMethod(operationName = "TransferRequestRevoked")
    @Oneway
    public void transferRequestRevoked(
        @WebParam(partName = "requestRevoked", name = "requestRevoked", targetNamespace = "")
        cz.tacr.elza.ws.types.v1.RequestRevoked requestRevoked
    ) throws CoreServiceException;

    @WebMethod(operationName = "DestructionRequestFinished")
    @Oneway
    public void destructionRequestFinished(
        @WebParam(partName = "requestIdentifier", name = "requestIdentifier", targetNamespace = "")
        java.lang.String requestIdentifier
    ) throws CoreServiceException;
}
