package ZP2015;

import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.NewLevel;
import cz.tacr.elza.drools.model.DescItem;
import cz.tacr.elza.drools.model.NewLevelApproach;

global cz.tacr.elza.drools.model.NewLevelApproaches results;

/*
 * Implementační poznámky:
 * 
 * Nový uzel se pozná podle chybějícího nodeId nebo je typu NewLevel
 */

rule "Archivní soubor"
when
    NewLevel( parent==null )
then
	NewLevelApproach approach = results.create("Archivní soubor");
	approach.addDescItem("ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_ROOT");
end

rule "Série"
when
	$level: NewLevel( parent!=null && $items: parent.descItems )
    DescItem( type == "ZP2015_LEVEL_TYPE" && ( specCode == "ZP2015_LEVEL_ROOT" || specCode == "ZP2015_LEVEL_SERIES" ) ) from $items
	// Serii nelze pridat pokud pred existuje neco jineho nez serie
	//not ( NewLevel ( siblingBefore!=null && $itemsBefore: siblingBefore.descItems ) and
	//	DescItem( type == "ZP2015_LEVEL_TYPE" && specCode != "ZP2015_LEVEL_SERIES" ) from $itemsBefore )
	// Serii nelze pridat pokud za existuje neco jineho nez serie 
	//not ( NewLevel ( siblingAfter!=null && $itemsAfter: siblingAfter.descItems ) and
	//	DescItem( type == "ZP2015_LEVEL_TYPE" && specCode != "ZP2015_LEVEL_SERIES" ) from $itemsAfter ) 
then
	NewLevelApproach approach = results.create("Série v11");
	approach.addDescItem("ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_SERIES");
end

rule "Logická složka"
when
	$level: NewLevel( parent!=null && $items: parent.descItems)
	DescItem( type == "ZP2015_LEVEL_TYPE" && ( specCode == "ZP2015_LEVEL_SERIES" || specCode == "ZP2015_LEVEL_FOLDER" ) ) from $items
	not DescItem( type == "ZP2015_FOLDER_TYPE" && specCode == "ZP2015_FOLDER_SINGLE_TYPE" ) from $items
then
	NewLevelApproach approach = results.create("Logická složka v3");
	approach.addDescItem("ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_FOLDER");
	approach.addDescItem("ZP2015_FOLDER_TYPE", "ZP2015_FOLDER_LOGICAL");
end

rule "Složka s množstevní EJ"
when
	$level: NewLevel( parent!=null && $items: parent.descItems)
	DescItem( type == "ZP2015_LEVEL_TYPE" && ( specCode == "ZP2015_LEVEL_SERIES" || specCode == "ZP2015_LEVEL_FOLDER" ) ) from $items
	not ( Level( nodeId!=null, $items2: descItems) and
		DescItem( type == "ZP2015_FOLDER_TYPE" && specCode != "ZP2015_FOLDER_LOGICAL" ) from $items2 )
then
	NewLevelApproach approach = results.create("Složka s množstevní EJ");
    approach.addDescItem("ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_FOLDER");
    approach.addDescItem("ZP2015_FOLDER_TYPE", "ZP2015_FOLDER_UNITS");
end

rule "Složka s uvedením typu EJ"
when
	$level: NewLevel( parent!=null && $items: parent.descItems)
	DescItem( type == "ZP2015_LEVEL_TYPE" && ( specCode == "ZP2015_LEVEL_SERIES" || specCode == "ZP2015_LEVEL_FOLDER" ) ) from $items
	not ( Level( nodeId!=null, $items2: descItems) and
		DescItem( type == "ZP2015_FOLDER_TYPE" && specCode != "ZP2015_FOLDER_LOGICAL" ) from $items2 )
then
    NewLevelApproach approach = results.create("Složka s uvedením typu EJ");
    approach.addDescItem("ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_FOLDER");
    approach.addDescItem("ZP2015_FOLDER_TYPE", "ZP2015_FOLDER_SINGLE_TYPE");
end

rule "Jednotlivost"
when
	$level: NewLevel( parent!=null && $items: parent.descItems )
	DescItem( type == "ZP2015_LEVEL_TYPE" && ( specCode == "ZP2015_LEVEL_SERIES" || specCode == "ZP2015_LEVEL_FOLDER" ) ) from $items
	// Jednotlivost nejde pridat pokud pred existuje serie
	// not ( NewLevel ( siblingBefore!=null && $itemsBefore: siblingBefore.descItems ) and
	//	DescItem( type == "ZP2015_LEVEL_TYPE" && specCode == "ZP2015_LEVEL_SERIES" ) from $itemsBefore )
	// Jednotlivost nejde pridat pokud za existuje serie 
	// not ( NewLevel ( siblingAfter!=null && $itemsAfter: siblingAfter.descItems ) and
	//	DescItem( type == "ZP2015_LEVEL_TYPE" && specCode == "ZP2015_LEVEL_SERIES" ) from $itemsAfter ) 
then
    NewLevelApproach approach = results.create("Jednotlivost v3");
    approach.addDescItem("ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_ITEM");
end

rule "Část jednotlivosti"
when
	$level: NewLevel( parent!=null && $items: parent.descItems)
	DescItem( type == "ZP2015_LEVEL_TYPE" && ( specCode == "ZP2015_LEVEL_ITEM" || specCode == "ZP2015_LEVEL_PART" ) ) from $items
then
    NewLevelApproach approach = results.create("Část jednotlivosti");
    approach.addDescItem("ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_PART");
end
