package ZP2015;


import java.util.Arrays;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.NewLevel;
import cz.tacr.elza.domain.vo.DataValidationResult;
import cz.tacr.elza.drools.model.DescItem;
import cz.tacr.elza.domain.RulArrangementType;
import cz.tacr.elza.domain.ArrDescItem
import java.util.ArrayList
import java.util.List
import cz.tacr.elza.domain.ArrDescItemEnum
import cz.tacr.elza.drools.model.NewLevelApproach;

global cz.tacr.elza.drools.model.NewLevelApproaches results;

function boolean isRootLevel(Level level){
    if (level == null) {
        return false;
    }
    return level.getParent() == null;
}

function boolean hasLevelTypeAndSpec(Level level, String typeCode, String specCode){
    if(level == null || level.getDescItems() == null){
        return false;
    }

    for (DescItem descItem : level.getDescItems()) {
        if(typeCode.equals(descItem.getType()) && specCode.equals(descItem.getSpecCode())){
            return true;
        }
    }
    return false;
}

rule "Vytvoření AP"
when
    level: NewLevel(eventSource == null)
then
    NewLevelApproach approach = results.create("Vytvoření AP");
    approach.addDescItem("ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_ROOT");
end

rule "Pokud rodič levelu je root level"
when
    level: Level()
    eval(isRootLevel(level.getParent()))
then
    NewLevelApproach approach = results.create("Nejvyšší série");
    approach.addDescItem("ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_SERIES");
end

rule "Pokud rodič levelu má atribut ZP2015_LEVEL_TYPE/ZP2015_LEVEL_ITEM"
when
    level: Level()
    eval(hasLevelTypeAndSpec(level.getParent(), "ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_ITEM"))
then
    NewLevelApproach approach = results.create("Část jednotlivosti");
    approach.addDescItem("ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_PART");
end

rule "Pokud rodič levelu má atribut ZP2015_LEVEL_TYPE/ZP2015_LEVEL_PART"
when
    level: Level()
    eval(hasLevelTypeAndSpec(level.getParent(), "ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_PART"))
then
    NewLevelApproach approach = results.create("Část jednotlivosti");
    approach.addDescItem("ZP2015_LEVEL_TYPE", "ZP2015_LEVEL_PART");
end