package drlglobal;
import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec
import cz.tacr.elza.drools.model.RequiredType;
import cz.tacr.elza.drools.model.item.Item;
import cz.tacr.elza.drools.model.Ap;
import cz.tacr.elza.drools.model.Part;
import cz.tacr.elza.drools.model.PartType;

rule "R_NAM_002 Použití prvků popisu pro označení"
when $it: ItemType(code in ("NM_MINOR"))
then
    $it.setPossible();
end

rule "R_NAM_002.2 Použití prvků popisu pro označení"
when $it: ItemType(code == "NM_TYPE")
     $is : ItemSpec(code in ("NT_OFFICIAL")) from $it.specs
then
    $it.setPossible();
    $is.setPossible();
end

rule "R_NAM_002.3 Použití prvků popisu pro označení"
when $part: Part(preferred)
     $it: ItemType(code in ("NM_MINOR"))
then
    $it.setRequired();
end
