package ZP2015;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

// Doporučení položky
rule "Doporučené"
no-loop
when
    $itemType : RulItemTypeExt(code in ("AP_DESCRIPTION"))
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
    $itemType.setRepeatable(false);
end

// Možné položky
rule "Možné - opakující"
no-loop
when
    $itemType : RulItemTypeExt(code in ("VZTAH_STAT_ZASTUPCE"))
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setRepeatable(true);
end

// Možné položky
rule "Možné - neopakující"
no-loop
when
    $itemType : RulItemTypeExt(code in ("AP_NAME"))
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setRepeatable(false);
end
