build:
  stage: build
  tags:
    - build
  script:
    - mvn -B -Ptest,release install
    - cp distrib/elza-war/target/elza-*.war distrib/elza-docker/elza.war
    - docker-buildtag.sh elza distrib/elza-docker
  artifacts:
    reports:
      junit:
        - '**/target/surefire-reports/TEST-*.xml'
