package drlglobal;
import cz.tacr.elza.drools.model.ApValidationErrors;
import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec
import cz.tacr.elza.drools.model.RequiredType;
import cz.tacr.elza.drools.model.item.Item;
import cz.tacr.elza.drools.model.item.UnitdateItem;
import cz.tacr.elza.drools.model.Ap;
import cz.tacr.elza.drools.model.Part;
import cz.tacr.elza.drools.model.PartType;
import cz.tacr.elza.drools.model.Index;
import cz.tacr.elza.drools.model.GeoModel;
import cz.tacr.elza.drools.model.ExpectedItems;
global ApValidationErrors results;


/*
Existence prvků popisu u zániku
*/

rule "R_EXT_006 Povinnost prvků popisu zániku"
when $ae: Ap( )
     $part: Part(type == PartType.PT_EXT) from $ae.Parts
     not (Item(type in ("NOTE")) from $part.items)
     not (UnitdateItem(type in ("EXT_DATE")) from $part.items)
     not (Part(parentPartId == $part.id) from $ae.Parts)
then 
    results.addError("U zániku neexistuje ani jeden z následujícího popisu: poznámka, datace, návazná entita.");
end
  

/*
R_NAM_005 Kontrola hodnoty chronologického doplňku
*/

rule "R_NAM_005 Kontrola chronologickeho doplňku se zánikem"
when $ae: Ap( )
     $part: Part(type == PartType.PT_NAME) from $ae.parts
     $partExt: Part(type == PartType.PT_EXT) from $ae.parts
     ExpectedItems( $expItems: items )
     $expSupChro: Item(type == "NM_SUP_CHRO" ) from $expItems
     $item: Item(type == "NM_SUP_CHRO", value!=$expSupChro.value ) from $part.items
then
    results.addError("Chronologický doplněk neodpovídá očekávané hodnotě. Hodnota: " + $item.getValue() + ", očekáváná hodnota: " + $expSupChro.getValue());
end


rule "R_NAM_005 Kontrola chronologickeho doplňku bez zániku"
when $ae: Ap( )
     $part: Part(type == PartType.PT_NAME) from $ae.parts
     not $partExt: Part(type == PartType.PT_EXT) from $ae.parts
     ExpectedItems( $expItems: items )
     $expSupChro: Item(type == "NM_SUP_CHRO" ) from $expItems
     $item: Item(type == "NM_SUP_CHRO", value!=$expSupChro.value && value!=($expSupChro.value + "?")) from $part.items
then
    results.addError("Chronologický doplněk neodpovídá očekávané hodnotě. Hodnota: " + $item.getValue() + ", očekáváná hodnota: " + $expSupChro.getValue());
end

