
package cz.tacr.elza.ws.core.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2019-06-21T09:42:06.685+02:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "errorDescription", targetNamespace = "http://elza.tacr.cz/ws/types/v1")
public class CoreServiceException extends RuntimeException {
    
    private cz.tacr.elza.ws.types.v1.ErrorDescription errorDescription;

    public CoreServiceException() {
        super();
    }
    
    public CoreServiceException(String message) {
        super(message);
    }
    
    public CoreServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public CoreServiceException(String message, cz.tacr.elza.ws.types.v1.ErrorDescription errorDescription) {
        super(message);
        this.errorDescription = errorDescription;
    }

    public CoreServiceException(String message, cz.tacr.elza.ws.types.v1.ErrorDescription errorDescription, Throwable cause) {
        super(message, cause);
        this.errorDescription = errorDescription;
    }

    public cz.tacr.elza.ws.types.v1.ErrorDescription getFaultInfo() {
        return this.errorDescription;
    }
}
