package ZP2015;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

rule "Atribut ZP2015_TITLE je nemožný"
salience 100
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_TITLE")
then
    $itemType.setIndefinable(true);
end

rule "Všechny jsou možný a neopakovatelný"
when
    $itemType : RulItemTypeExt()
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setRepeatable(false);
end
