elza:
  data:
    # Nastaveni DB
    url: <dbURL>
    user: <dbUser>
    pass: <dbPass>

#  attachment:
    # Konfigurace mimetypu pro editaci souboru
#    mimeDefs:
#      - mimeType: text/plain
#        editable: true
        # Generatory pro jednotlive typy souboru
#        generators:
#         - outputMimeType: application/pdf
#           command: pandoc {2} -o {4}
#           outputFileName: result.pdf

spring:    
  jpa:
    properties:
      hibernate:
        <dbDialect>
