spring:
  datasource:
    url: jdbc:postgresql://vyv-inet/elza
    driver-class-name: org.postgresql.Driver
    username: app
    password: app
  jpa:
    # Logovani SQL dotazu
    show-sql: true
    # Upgrade DB
    hibernate.ddl-auto: update    
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #hibernate.naming-strategy: cz.tacr.elza.hibernate.UppercaseImprovedNamingStrategy
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
vax:
  viewMain: FindingAid
  viewError: Exception

debug:
  firstView: Test
