spring:
  datasource:
    url: jdbc:postgresql://vyv-inet/elza
    username: app
    password: app
  jpa:
    # Logovani SQL dotazu
    show-sql: true
    # Upgrade DB
    hibernate.ddl-auto: update    
vax:
  viewMain: FindingAidList
  viewError: Exception

debug:
  firstView: FindingAidList
