application:
  version: ${project.parent.version}

spring:
  datasource:
    url: jdbc:postgresql://vyv-inet/elza
#    url: jdbc:postgresql://vyv-inet/elza_test    
#    url: jdbc:postgresql://vyv-inet/elza_test_data
    username: app
    password: app
  data:
    rest:
      base-uri: /rest
  jpa:
    # Logovani SQL dotazu
    show-sql: true
vax:
  viewMain: FindingAidList
  viewError: Exception

debug:
  firstView: FindingAidList
