elza:
  treenode:
    title: ${elza.conf.treenode.title}
    defaultTitle: ${elza.conf.treenode.default.title} 
spring:
  application:
     name: elza
     version: ${project.parent.version}
  datasource:
    url: ${elza.data.url}
    username: ${elza.data.user}
    password: ${elza.data.pass}
  data:
    rest:
      base-uri: /rest
  app:
      buildType: REL      
  jpa:
    # Logovani SQL dotazu
    #show-sql: true
    properties:
          hibernate:
              search:
                  lucene_version: LUCENE_CURRENT
                  default:
                      indexBase: ./lucene/indexes/
                      directory_provider: filesystem
                      
