elza:
  treenode:
    title: ${elza.conf.treenode.title}
    defaultTitle: ${elza.conf.treenode.default.title} 
  workingDir: ./work
  xmlImport:
    transformationDir: ${elza.workingDir}/transformations/
  bulkactions:
    bulkactionsDir: ${elza.workingDir}/bulkactions
  rulesDir: ${elza.workingDir}/rules
  groovy:
    groovyDir: ${elza.workingDir}/groovy
spring:
  application:
     name: elza
     version: ${project.parent.version}
  datasource:
    url: ${elza.data.url}
    username: ${elza.data.user}
    password: ${elza.data.pass}
  data:
    rest:
      base-uri: /rest
  app:
      buildType: REL      
  jpa:
    # Logovani SQL dotazu
    #show-sql: true
    properties:
          hibernate:
              search:
                  lucene_version: LUCENE_CURRENT
                  default:
                      indexBase: ${elza.workingDir}/lucene/indexes/
                      directory_provider: filesystem
                      
