package isaarcpf;
import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec;
import cz.tacr.elza.drools.model.item.IntItem;
import cz.tacr.elza.drools.model.Part;
import cz.tacr.elza.drools.model.PartType;

rule "ISAAR 5.3.2: relationships of the class"
when $it: ItemType(code == "REL_ENTITY")
     $is: ItemSpec(code in ("RT_SUPCORP", "RT_ISPART", "RT_ISMEMBER", "RT_FOUNDER", "RT_OWNER", "RT_PREDECESSOR", "RT_SUCCESSOR", "RT_OTHERNAME", "ISAAR_RT_ASSOCIATED", "RT_RESIDENCE", "RT_PLACE", "RT_GEOSCOPE", "RT_FUNCTION", "RT_ACTIVITYFIELD")) from $it.specs
then
    $it.setPossible();
    $is.setPossible();
end

