package SimpleDev;


import java.util.Arrays;
import cz.tacr.elza.drools.model.Level
import cz.tacr.elza.drools.model.ActiveLevel
import cz.tacr.elza.drools.model.DescItem;
import cz.tacr.elza.domain.vo.DataValidationResult;
import cz.tacr.elza.domain.vo.DataValidationResults;

global DataValidationResults results;

// Kontrola, zda každý list má ukládací jednotku
rule "List musí mít ukládací jednotku směrem ke kořeni"
when
	$activeLevel: ActiveLevel( !hasChildren )
	not ( $level: Level( $items: descItems ) and 
		DescItem(type=="SRD_STORAGE_ID") from $items )
then
	results.createMissing("SRD_STORAGE_ID", "Chybí ukládací jednotka", "STORAGE_ID");
end

// Kontrola, zda každý list má dataci
rule "List musí mít dataci směrem ke kořeni"
when
	$activeLevel: ActiveLevel( !hasChildren )
	not ( $level: Level( $items: descItems ) and 
		DescItem(type in 
		  ( "SRD_UNIT_DATE_PRE", "SRD_UNIT_DATE", "SRD_UNIT_DATE_POST","SRD_UNIT_DATE_TEXT" ) )
		  from $items )
then
	results.createMissing("SRD_UNIT_DATE", "Není uvedena datace", "BASIC");
end

// Kontrola, zda každá hromadina s EJ má uvedenu ukládací jednotku s druhem KAR,FAS,DAJ
rule "Každá hromadina s EJ má uvedenu ukládací jednotku"
when
	$activeLevel: ActiveLevel( $items: descItems )
	DescItem(type=="SRD_FOLDER_TYPE" && (specCode=="SRD_FOLDER_UNITS"||specCode=="SRD_FOLDER_SINGLE_TYPE") ) from $items 
	not ( DescItem(type=="SRD_STORAGE_ID"&&packet!=null&&packet.packetType!=null&&(packet.packetType.code=="BOX"||packet.packetType.code=="FASCICLE"||packet.packetType.code=="DATA_UNIT" ) ) from $items )
then
	results.createMissing("SRD_STORAGE_ID", "Ukládací jednotka bez uvedení typu hromadiny", "STORAGE_ID");
end

// Počet jednotek musí být větší než 1 pro SRD_UNIT_COUNT
rule "Počet jednotek musí být větší než 1 - SRD_UNIT_COUNT"
when
	$activeLevel: ActiveLevel( $items: descItems )
    $descItem: DescItem(type=="SRD_UNIT_COUNT"  && integer.intValue()<2 ) from $items
then
	results.createError($descItem.getDescItemId(), "Počet jednotek musí být větší než 1", "BASIC");
end

// Povinné pokud je nastaven typ pořádání
rule "Pořadové číslo - povinné"
no-loop
when
	$activeLevel : ActiveLevel( )
	DescItem(type=="SRD_ARRANGEMENT_TYPE" && specCode in ("SRD_ARRANGEMENT_MAN", "SRD_ARRANGEMENT_INV", "SRD_ARRANGEMENT_KAT") ) from $activeLevel.descItems
	not DescItem(type=="SRD_SERIAL_NUMBER" && !isInherited()) from $activeLevel.descItems
then
	results.createMissing("SRD_SERIAL_NUMBER", "Pořadové číslo musí být nastaveno", "SERIAL_NO");
end

// referenční označení v INV|KAT - povinné pro uzly mimo kořen
rule "Referenční označení - povinné"
no-loop
when
	$activeLevel: ActiveLevel( parent!=null )
	DescItem(type=="SRD_ARRANGEMENT_TYPE" && specCode in ("SRD_ARRANGEMENT_INV", "SRD_ARRANGEMENT_KAT") ) from $activeLevel.descItems
	not DescItem(type=="SRD_UNIT_ID" && !isInherited()) from $activeLevel.descItems
then
	results.createMissing("SRD_UNIT_ID", "Referenční označení musí byt přiřazeno", "REF_NO");
end

/*



function DescItem getLevelAttribute(Level level, String attributeName){
     if(level.getDescItems() == null){
         return null;
     } else{
         for (DescItem descItem : level.getDescItems()) {
            if(descItem.getType().equals(attributeName)){
                 return descItem;
            }
         }
         return null;
     }
}

function boolean hasLevelRequiredTypeSpec(Level level, String typeCode, String requiredSpecCode){
    if(level.getDescItems() == null){
        return false;
    }


    for (DescItem descItem : level.getDescItems()) {
        if(typeCode.equals(descItem.getType()) && requiredSpecCode.equals(descItem.getSpecCode())){
            return true;
        }
    }
    return false;
}



rule "Kontrola u posledního node/levelu stromu (listu), zda je v jeho větvi (od něj až po root) alespoň jednou uveden atribut SRD_TITLE"
when
    level: Level()
    eval(strategies.contains("COMPLETE"))
    eval(isLeaf(level))
    eval(!hasLevelAttribute(level, "SRD_TITLE") && !hasParentsAttribute(level, "SRD_TITLE"))
then
	results.add(DataValidationResult.createMissing("SRD_TITLE", "V hierarchii archivního popisu není uveden atribut SRD_TITLE"));
end


rule "Kontrola root levelu/node na atribut SRD_LEVEL_TYPE, zda je správně podřízenost/nadřízenost"
when
    //jedná se o level přímo pod rootem
    level: Level(parent != null, parent.getParent() == null)
    eval(hasLevelAttribute(level, "SRD_LEVEL_TYPE"))
    eval(!hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_SERIES"))
then
    DescItem typeItem = getLevelAttribute(level, "SRD_LEVEL_TYPE");
    results.add(DataValidationResult.createError(typeItem.getDescItemId(), "Chybně uvedená úroveň popisu: " + typeItem.getSpecCode()+" nesmí být pod kořenovým uzlem."));
end

rule "Kontrola SRD_LEVEL_SERIES levelu/node na atribut SRD_LEVEL_TYPE, zda je správně podřízenost/nadřízenost"
when
    level: Level(parent != null)
    eval(hasLevelAttribute(level, "SRD_LEVEL_TYPE"))
    eval(hasLevelAttribute(level.getParent(), "SRD_LEVEL_TYPE"))

    eval(hasLevelRequiredTypeSpec(level.getParent(), "SRD_LEVEL_TYPE", "SRD_LEVEL_SERIES")
            &&

            (   !hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_SERIES")
            &&  !hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_FOLDER")
            &&  !hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_ITEM")
               )
        )
then
    DescItem typeItem = getLevelAttribute(level, "SRD_LEVEL_TYPE");
    DescItem parentItem = getLevelAttribute(level.getParent(), "SRD_LEVEL_TYPE");
    results.add(DataValidationResult.createError(typeItem.getDescItemId(), "Chybně uvedená úroveň popisu: " + typeItem.getSpecCode()+", nadřízená je: "+parentItem.getSpecCode()));
end

rule "Kontrola SRD_LEVEL_FOLDER levelu/node na atribut SRD_LEVEL_TYPE, zda je správně podřízenost/nadřízenost"
when
    level: Level(parent != null)
    eval(hasLevelAttribute(level, "SRD_LEVEL_TYPE"))
    eval(hasLevelAttribute(level.getParent(), "SRD_LEVEL_TYPE"))

    eval(hasLevelRequiredTypeSpec(level.getParent(), "SRD_LEVEL_TYPE", "SRD_LEVEL_FOLDER")
        &&  (!hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_FOLDER")
            &&!hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_ITEM")
            )
        )


    eval(!(hasLevelRequiredTypeSpec(level.getParent(), "SRD_LEVEL_TYPE", "SRD_LEVEL_ITEM")
        &&  !hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_PART")
        ))


    eval(!(hasLevelRequiredTypeSpec(level.getParent(), "SRD_LEVEL_TYPE", "SRD_LEVEL_PART")
        &&  !hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_PART")
        ))
then
    DescItem typeItem = getLevelAttribute(level, "SRD_LEVEL_TYPE");
    DescItem parentItem = getLevelAttribute(level.getParent(), "SRD_LEVEL_TYPE");
    results.add(DataValidationResult.createError(typeItem.getDescItemId(), "Chybně uvedená úroveň popisu: " + typeItem.getSpecCode()+", nadřízená je: "+parentItem.getSpecCode()));
end

rule "Kontrola SRD_LEVEL_ITEM levelu/node na atribut SRD_LEVEL_TYPE, zda je správně podřízenost/nadřízenost"
when
    level: Level(parent != null)
    eval(hasLevelAttribute(level, "SRD_LEVEL_TYPE"))
    eval(hasLevelAttribute(level.getParent(), "SRD_LEVEL_TYPE"))

    eval(hasLevelRequiredTypeSpec(level.getParent(), "SRD_LEVEL_TYPE", "SRD_LEVEL_ITEM")
        &&  !hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_PART")
        )
then
    DescItem typeItem = getLevelAttribute(level, "SRD_LEVEL_TYPE");
    DescItem parentItem = getLevelAttribute(level.getParent(), "SRD_LEVEL_TYPE");
    results.add(DataValidationResult.createError(typeItem.getDescItemId(), "Chybně uvedená úroveň popisu: " + typeItem.getSpecCode()+", nadřízená je: "+parentItem.getSpecCode()));
end

rule "Kontrola SRD_LEVEL_PART levelu/node na atribut SRD_LEVEL_TYPE, zda je správně podřízenost/nadřízenost"
when
    level: Level(parent != null)
    eval(hasLevelAttribute(level, "SRD_LEVEL_TYPE"))
    eval(hasLevelAttribute(level.getParent(), "SRD_LEVEL_TYPE"))

    eval(hasLevelRequiredTypeSpec(level.getParent(), "SRD_LEVEL_TYPE", "SRD_LEVEL_PART")
        &&  !hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_PART")
        )
then
    DescItem typeItem = getLevelAttribute(level, "SRD_LEVEL_TYPE");
    DescItem parentItem = getLevelAttribute(level.getParent(), "SRD_LEVEL_TYPE");
    results.add(DataValidationResult.createError(typeItem.getDescItemId(), "Chybně uvedená úroveň popisu: " + typeItem.getSpecCode()+", nadřízená je: "+parentItem.getSpecCode()));
end


rule "Kontrola koncových uzlů typu série a jednotlivost"
when
    //jedná se o level přímo pod rootem
    level: Level()
    eval(arrType.getCode().equals("KAT"))
    eval(isLeaf(level))
    eval(hasLevelAttribute(level, "SRD_LEVEL_TYPE"))

    eval(hasLevelAttribute(level.getParent(), "SRD_LEVEL_TYPE"))
    eval(hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_FOLDER")
        ||
         hasLevelRequiredTypeSpec(level, "SRD_LEVEL_TYPE", "SRD_LEVEL_SERIES"))
then
    DescItem typeItem = getLevelAttribute(level, "SRD_LEVEL_TYPE");
    results.add(DataValidationResult.createError(typeItem.getDescItemId(), "Chybně ukončená úroveň popisu v "+arrType.getCode()+": "+typeItem.getSpecCode()));
end
*/
