package SimpleDev;

import cz.tacr.elza.api.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.api.RulItemType;

// Volitelné neopakovatelné prvky popisu
rule "Jen vybrané jsou možné"
no-loop 
when
	$itemType : RulItemTypeExt( code in ( 
	"SRD_UNIT_COUNT", "SRD_UNIT_HIST", "SRD_STATISTICS", "ZP2015_UNIT_COUNT_TABLE") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setRepeatable(false);
end

// Povinné neopakovatelné prvky popisu
rule "Povinné neopakovatelné prvky popisu"
no-loop 
when
	$itemType : RulItemTypeExt( code in ("SRD_TITLE" ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
    $itemType.setRepeatable(false);
end
