/**
 * FA.
 */
export const FA_REQUEST_FA_FILE_TREE = 'FA_REQUEST_FA_FILE_TREE'
export const FA_RECEIVE_FA_FILE_TREE = 'FA_RECEIVE_FA_FILE_TREE'

export const FA_SELECT_FA = 'FA_SELECT_FA'
export const FA_CLOSE_FA = 'FA_CLOSE_FA'

export const FA_SELECT_NODE = 'FA_SELECT_NODE'
export const FA_CLOSE_NODE = 'FA_CLOSE_NODE'

/**
 * Party.
 */
export const PARTY_XXX = 'PARTY_XXX'

/**
 * Record.
 */
export const RECORD_REQUEST_RECORD_LIST = 'RECORD_REQUEST_RECORD_LIST'
export const RECORD_RECEIVE_RECORD_LIST = 'RECORD_RECEIVE_RECORD_LIST'
export const RECORD_SELECT_RECORD = 'RECORD_SELECT_RECORD'
export const RECORD_RECEIVE_RECORD_DETAIL = 'RECORD_RECEIVE_RECORD_DETAIL'
export const RECORD_REQUEST_RECORD_DETAIL = 'RECORD_REQUEST_RECORD_DETAIL'

/**
 * Global.
 */
export const GLOBAL_GET_OBJECT_INFO = 'GLOBAL_GET_OBJECT_INFO'
