//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for doplnekTypA.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="doplnekTypA"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="rozpis iniciál"/&gt;
 *     &lt;enumeration value="obecný doplněk"/&gt;
 *     &lt;enumeration value="římské číslice"/&gt;
 *     &lt;enumeration value="geografický doplněk"/&gt;
 *     &lt;enumeration value="chronologický doplněk"/&gt;
 *     &lt;enumeration value="pořadí události"/&gt;
 *     &lt;enumeration value="jazyk díla"/&gt;
 *     &lt;enumeration value="autor/tvůrce"/&gt;
 *     &lt;enumeration value="pramen/zdroj"/&gt;
 *     &lt;enumeration value="chronologický doplněk/verze díla"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "doplnekTypA")
@XmlEnum
public enum DoplnekTypA {

    @XmlEnumValue("rozpis inici\u00e1l")
    ROZPIS_INICIÁL("rozpis inici\u00e1l"),
    @XmlEnumValue("obecn\u00fd dopln\u011bk")
    OBECNÝ_DOPLNĚK("obecn\u00fd dopln\u011bk"),
    @XmlEnumValue("\u0159\u00edmsk\u00e9 \u010d\u00edslice")
    ŘÍMSKÉ_ČÍSLICE("\u0159\u00edmsk\u00e9 \u010d\u00edslice"),
    @XmlEnumValue("geografick\u00fd dopln\u011bk")
    GEOGRAFICKÝ_DOPLNĚK("geografick\u00fd dopln\u011bk"),
    @XmlEnumValue("chronologick\u00fd dopln\u011bk")
    CHRONOLOGICKÝ_DOPLNĚK("chronologick\u00fd dopln\u011bk"),
    @XmlEnumValue("po\u0159ad\u00ed ud\u00e1losti")
    POŘADÍ_UDÁLOSTI("po\u0159ad\u00ed ud\u00e1losti"),
    @XmlEnumValue("jazyk d\u00edla")
    JAZYK_DÍLA("jazyk d\u00edla"),
    @XmlEnumValue("autor/tv\u016frce")
    AUTOR_TVŮRCE("autor/tv\u016frce"),
    @XmlEnumValue("pramen/zdroj")
    PRAMEN_ZDROJ("pramen/zdroj"),
    @XmlEnumValue("chronologick\u00fd dopln\u011bk/verze d\u00edla")
    CHRONOLOGICKÝ_DOPLNĚK_VERZE_DÍLA("chronologick\u00fd dopln\u011bk/verze d\u00edla");
    private final String value;

    DoplnekTypA(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DoplnekTypA fromValue(String v) {
        for (DoplnekTypA c: DoplnekTypA.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
