//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.24 at 04:42:06 PM CET
//


package cz.tacr.elza.interpi.ws.wo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Komplexní typ pre popis jedné entity, obsahuje přímo základní identifikaci entity.
 *
 * <p>Java class for entitaTyp complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="entitaTyp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="trida" type="{http://www.interpi.cz}tridaTyp"/&gt;
 *         &lt;element name="podtrida" type="{http://www.interpi.cz}podtridaTyp"/&gt;
 *         &lt;element name="identifikace" type="{http://www.interpi.cz}identifikaceTyp" maxOccurs="unbounded"/&gt;
 *         &lt;element name="zaznam" type="{http://www.interpi.cz}zaznamTyp"/&gt;
 *         &lt;element name="preferovane_oznaceni" type="{http://www.interpi.cz}oznaceniTyp" maxOccurs="unbounded"/&gt;
 *         &lt;element name="variantni_oznaceni" type="{http://www.interpi.cz}oznaceniTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="udalost" type="{http://www.interpi.cz}udalostTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="pocatek_existence" type="{http://www.interpi.cz}udalostTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="konec_existence" type="{http://www.interpi.cz}udalostTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="zmena" type="{http://www.interpi.cz}udalostTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="popis" type="{http://www.interpi.cz}popisTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="souradnice" type="{http://www.interpi.cz}souradniceTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="titul" type="{http://www.interpi.cz}titulTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="kodovane_udaje" type="{http://www.interpi.cz}kodovaneTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="souvisejici_entita" type="{http://www.interpi.cz}souvisejiciTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="hierarchicka_struktura" type="{http://www.interpi.cz}strukturaTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="zarazeni" type="{http://www.interpi.cz}zarazeniTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="vyobrazeni" type="{http://www.interpi.cz}vyobrazeniTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="zdroj_informaci" type="{http://www.interpi.cz}zdrojTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entitaTyp", propOrder = {
    "content"
})
@XmlRootElement
public class EntitaTyp {

    @XmlElementRefs({
        @XmlElementRef(name = "zaznam", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "souvisejici_entita", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "souradnice", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "vyobrazeni", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "zmena", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "hierarchicka_struktura", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "preferovane_oznaceni", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "identifikace", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "zarazeni", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "titul", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "trida", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "variantni_oznaceni", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "popis", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "udalost", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "kodovane_udaje", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "podtrida", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "konec_existence", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "pocatek_existence", namespace = "http://www.interpi.cz", type = JAXBElement.class),
        @XmlElementRef(name = "zdroj_informaci", namespace = "http://www.interpi.cz", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Komplexní typ pre popis jedné entity, obsahuje přímo základní identifikaci entity.Gets the value of the content property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ZaznamTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link SouvisejiciTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link SouradniceTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link VyobrazeniTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link UdalostTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link StrukturaTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link OznaceniTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link IdentifikaceTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link ZarazeniTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link TitulTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link TridaTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link OznaceniTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link PopisTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link UdalostTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link KodovaneTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link PodtridaTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link UdalostTyp }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link UdalostTyp }{@code >}
     * {@link JAXBElement }{@code <}{@link ZdrojTyp }{@code >}
     *
     *
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
