//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hlavni_castTypA.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="hlavni_castTypA"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="příjmení"/&gt;
 *     &lt;enumeration value="jméno"/&gt;
 *     &lt;enumeration value="jurisdikce"/&gt;
 *     &lt;enumeration value="nadřazená korporace"/&gt;
 *     &lt;enumeration value="příme pořadí"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "hlavni_castTypA")
@XmlEnum
public enum HlavniCastTypA {

    @XmlEnumValue("p\u0159\u00edjmen\u00ed")
    PŘÍJMENÍ("p\u0159\u00edjmen\u00ed"),
    @XmlEnumValue("jm\u00e9no")
    JMÉNO("jm\u00e9no"),
    @XmlEnumValue("jurisdikce")
    JURISDIKCE("jurisdikce"),
    @XmlEnumValue("nad\u0159azen\u00e1 korporace")
    NADŘAZENÁ_KORPORACE("nad\u0159azen\u00e1 korporace"),
    @XmlEnumValue("p\u0159\u00edme po\u0159ad\u00ed")
    PŘÍME_POŘADÍ("p\u0159\u00edme po\u0159ad\u00ed");
    private final String value;

    HlavniCastTypA(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HlavniCastTypA fromValue(String v) {
        for (HlavniCastTypA c: HlavniCastTypA.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
