//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Entita musí mít uvedeno minimálně jedno identifikační číslo. Přimárně se uvádi identifikační číslo INTERPI (v případě prezentace záznamů ze znalostní báze INTERPI pro jiné systémy). V jiných případech, kdy je prezentován záznam jiného systému pro znalostní bázi INTEPRI musí záznam obsahovat jiný identifikátor (primárně standardní čísla, čísla národních systému a pod.). V nevyhnutných případech je možné jako jiný identifikátor uvést systémové číslo jiného spoluprajícího systému (instituce). Označení systému ze zapíše do příslušného prvku, jako typ identifikátoru se uvede "systémové číslo".
 * 
 * <p>Java class for identifikaceTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identifikaceTyp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifikator" type="{http://www.interpi.cz}identifikatorTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="identifikator_jiny" type="{http://www.interpi.cz}identifikator_jinyTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identifikaceTyp", propOrder = {
    "identifikator",
    "identifikatorJiny"
})
public class IdentifikaceTyp {

    protected List<IdentifikatorTyp> identifikator;
    @XmlElement(name = "identifikator_jiny")
    protected List<IdentifikatorJinyTyp> identifikatorJiny;

    /**
     * Gets the value of the identifikator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifikator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifikator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifikatorTyp }
     * 
     * 
     */
    public List<IdentifikatorTyp> getIdentifikator() {
        if (identifikator == null) {
            identifikator = new ArrayList<IdentifikatorTyp>();
        }
        return this.identifikator;
    }

    /**
     * Gets the value of the identifikatorJiny property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifikatorJiny property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifikatorJiny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifikatorJinyTyp }
     * 
     * 
     */
    public List<IdentifikatorJinyTyp> getIdentifikatorJiny() {
        if (identifikatorJiny == null) {
            identifikatorJiny = new ArrayList<IdentifikatorJinyTyp>();
        }
        return this.identifikatorJiny;
    }

}
