//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Kódované údaje se používají pro vyjádření entity pomocí standardizovaných kódů. Kódovaný údaj nemusí vystihovat entitu úplně přesně. Pokud je to možné, uvede se přesný kódovaných údaj, v jiném případě se zvolí kódovaný údaj pro širší oblast, která entitu zahrnuje.
 * 
 * <p>Java class for kodovaneTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="kodovaneTyp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="datace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="poznámka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="typ" use="required" type="{http://www.interpi.cz}kodovaneTypA" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kodovaneTyp", propOrder = {
    "kod",
    "datace",
    "pozn\u00e1mka"
})
public class KodovaneTyp {

    @XmlElement(required = true)
    protected String kod;
    protected String datace;
    protected String poznámka;
    @XmlAttribute(name = "typ", required = true)
    protected KodovaneTypA typ;

    /**
     * Gets the value of the kod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKod() {
        return kod;
    }

    /**
     * Sets the value of the kod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKod(String value) {
        this.kod = value;
    }

    /**
     * Gets the value of the datace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatace() {
        return datace;
    }

    /**
     * Sets the value of the datace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatace(String value) {
        this.datace = value;
    }

    /**
     * Gets the value of the poznámka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoznámka() {
        return poznámka;
    }

    /**
     * Sets the value of the poznámka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoznámka(String value) {
        this.poznámka = value;
    }

    /**
     * Gets the value of the typ property.
     * 
     * @return
     *     possible object is
     *     {@link KodovaneTypA }
     *     
     */
    public KodovaneTypA getTyp() {
        return typ;
    }

    /**
     * Sets the value of the typ property.
     * 
     * @param value
     *     allowed object is
     *     {@link KodovaneTypA }
     *     
     */
    public void setTyp(KodovaneTypA value) {
        this.typ = value;
    }

}
