//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for komplexni_dataceTypA.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="komplexni_dataceTypA"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="začátek"/&gt;
 *     &lt;enumeration value="konec"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "komplexni_dataceTypA")
@XmlEnum
public enum KomplexniDataceTypA {

    @XmlEnumValue("za\u010d\u00e1tek")
    ZAČÁTEK("za\u010d\u00e1tek"),
    @XmlEnumValue("konec")
    KONEC("konec");
    private final String value;

    KomplexniDataceTypA(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static KomplexniDataceTypA fromValue(String v) {
        for (KomplexniDataceTypA c: KomplexniDataceTypA.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
