//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.tacr.elza.interpi.ws.wo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Set_QNAME = new QName("http://www.interpi.cz", "set");
    private final static QName _Entita_QNAME = new QName("http://www.interpi.cz", "entita");
    private final static QName _EntitaTypTrida_QNAME = new QName("http://www.interpi.cz", "trida");
    private final static QName _EntitaTypPodtrida_QNAME = new QName("http://www.interpi.cz", "podtrida");
    private final static QName _EntitaTypIdentifikace_QNAME = new QName("http://www.interpi.cz", "identifikace");
    private final static QName _EntitaTypZaznam_QNAME = new QName("http://www.interpi.cz", "zaznam");
    private final static QName _EntitaTypPreferovaneOznaceni_QNAME = new QName("http://www.interpi.cz", "preferovane_oznaceni");
    private final static QName _EntitaTypVariantniOznaceni_QNAME = new QName("http://www.interpi.cz", "variantni_oznaceni");
    private final static QName _EntitaTypUdalost_QNAME = new QName("http://www.interpi.cz", "udalost");
    private final static QName _EntitaTypPocatekExistence_QNAME = new QName("http://www.interpi.cz", "pocatek_existence");
    private final static QName _EntitaTypKonecExistence_QNAME = new QName("http://www.interpi.cz", "konec_existence");
    private final static QName _EntitaTypZmena_QNAME = new QName("http://www.interpi.cz", "zmena");
    private final static QName _EntitaTypPopis_QNAME = new QName("http://www.interpi.cz", "popis");
    private final static QName _EntitaTypSouradnice_QNAME = new QName("http://www.interpi.cz", "souradnice");
    private final static QName _EntitaTypTitul_QNAME = new QName("http://www.interpi.cz", "titul");
    private final static QName _EntitaTypKodovaneUdaje_QNAME = new QName("http://www.interpi.cz", "kodovane_udaje");
    private final static QName _EntitaTypSouvisejiciEntita_QNAME = new QName("http://www.interpi.cz", "souvisejici_entita");
    private final static QName _EntitaTypHierarchickaStruktura_QNAME = new QName("http://www.interpi.cz", "hierarchicka_struktura");
    private final static QName _EntitaTypZarazeni_QNAME = new QName("http://www.interpi.cz", "zarazeni");
    private final static QName _EntitaTypVyobrazeni_QNAME = new QName("http://www.interpi.cz", "vyobrazeni");
    private final static QName _EntitaTypZdrojInformaci_QNAME = new QName("http://www.interpi.cz", "zdroj_informaci");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.tacr.elza.interpi.ws.wo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetTyp }
     * 
     */
    public SetTyp createSetTyp() {
        return new SetTyp();
    }

    /**
     * Create an instance of {@link EntitaTyp }
     * 
     */
    public EntitaTyp createEntitaTyp() {
        return new EntitaTyp();
    }

    /**
     * Create an instance of {@link IdentifikaceTyp }
     * 
     */
    public IdentifikaceTyp createIdentifikaceTyp() {
        return new IdentifikaceTyp();
    }

    /**
     * Create an instance of {@link IdentifikatorTyp }
     * 
     */
    public IdentifikatorTyp createIdentifikatorTyp() {
        return new IdentifikatorTyp();
    }

    /**
     * Create an instance of {@link IdentifikatorJinyTyp }
     * 
     */
    public IdentifikatorJinyTyp createIdentifikatorJinyTyp() {
        return new IdentifikatorJinyTyp();
    }

    /**
     * Create an instance of {@link ZaznamTyp }
     * 
     */
    public ZaznamTyp createZaznamTyp() {
        return new ZaznamTyp();
    }

    /**
     * Create an instance of {@link HistorieZaznamuTyp }
     * 
     */
    public HistorieZaznamuTyp createHistorieZaznamuTyp() {
        return new HistorieZaznamuTyp();
    }

    /**
     * Create an instance of {@link SouhlasTyp }
     * 
     */
    public SouhlasTyp createSouhlasTyp() {
        return new SouhlasTyp();
    }

    /**
     * Create an instance of {@link PoznamkaTyp }
     * 
     */
    public PoznamkaTyp createPoznamkaTyp() {
        return new PoznamkaTyp();
    }

    /**
     * Create an instance of {@link OznaceniTyp }
     * 
     */
    public OznaceniTyp createOznaceniTyp() {
        return new OznaceniTyp();
    }

    /**
     * Create an instance of {@link HlavniCastTyp }
     * 
     */
    public HlavniCastTyp createHlavniCastTyp() {
        return new HlavniCastTyp();
    }

    /**
     * Create an instance of {@link VedlejsiCastTyp }
     * 
     */
    public VedlejsiCastTyp createVedlejsiCastTyp() {
        return new VedlejsiCastTyp();
    }

    /**
     * Create an instance of {@link DoplnekTyp }
     * 
     */
    public DoplnekTyp createDoplnekTyp() {
        return new DoplnekTyp();
    }

    /**
     * Create an instance of {@link UdalostTyp }
     * 
     */
    public UdalostTyp createUdalostTyp() {
        return new UdalostTyp();
    }

    /**
     * Create an instance of {@link KomplexniDataceTyp }
     * 
     */
    public KomplexniDataceTyp createKomplexniDataceTyp() {
        return new KomplexniDataceTyp();
    }

    /**
     * Create an instance of {@link SouvisejiciTyp }
     * 
     */
    public SouvisejiciTyp createSouvisejiciTyp() {
        return new SouvisejiciTyp();
    }

    /**
     * Create an instance of {@link IdentifikatorSouvTyp }
     * 
     */
    public IdentifikatorSouvTyp createIdentifikatorSouvTyp() {
        return new IdentifikatorSouvTyp();
    }

    /**
     * Create an instance of {@link SouvisejiciPracTyp }
     * 
     */
    public SouvisejiciPracTyp createSouvisejiciPracTyp() {
        return new SouvisejiciPracTyp();
    }

    /**
     * Create an instance of {@link SouvisejiciZpracTyp }
     * 
     */
    public SouvisejiciZpracTyp createSouvisejiciZpracTyp() {
        return new SouvisejiciZpracTyp();
    }

    /**
     * Create an instance of {@link SouvisejiciMinTyp }
     * 
     */
    public SouvisejiciMinTyp createSouvisejiciMinTyp() {
        return new SouvisejiciMinTyp();
    }

    /**
     * Create an instance of {@link PopisTyp }
     * 
     */
    public PopisTyp createPopisTyp() {
        return new PopisTyp();
    }

    /**
     * Create an instance of {@link TitulTyp }
     * 
     */
    public TitulTyp createTitulTyp() {
        return new TitulTyp();
    }

    /**
     * Create an instance of {@link KodovaneTyp }
     * 
     */
    public KodovaneTyp createKodovaneTyp() {
        return new KodovaneTyp();
    }

    /**
     * Create an instance of {@link StrukturaTyp }
     * 
     */
    public StrukturaTyp createStrukturaTyp() {
        return new StrukturaTyp();
    }

    /**
     * Create an instance of {@link SouradniceTyp }
     * 
     */
    public SouradniceTyp createSouradniceTyp() {
        return new SouradniceTyp();
    }

    /**
     * Create an instance of {@link ZarazeniTyp }
     * 
     */
    public ZarazeniTyp createZarazeniTyp() {
        return new ZarazeniTyp();
    }

    /**
     * Create an instance of {@link VyobrazeniTyp }
     * 
     */
    public VyobrazeniTyp createVyobrazeniTyp() {
        return new VyobrazeniTyp();
    }

    /**
     * Create an instance of {@link ZdrojTyp }
     * 
     */
    public ZdrojTyp createZdrojTyp() {
        return new ZdrojTyp();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "set")
    public JAXBElement<SetTyp> createSet(SetTyp value) {
        return new JAXBElement<SetTyp>(_Set_QNAME, SetTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntitaTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "entita")
    public JAXBElement<EntitaTyp> createEntita(EntitaTyp value) {
        return new JAXBElement<EntitaTyp>(_Entita_QNAME, EntitaTyp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TridaTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "trida", scope = EntitaTyp.class)
    public JAXBElement<TridaTyp> createEntitaTypTrida(TridaTyp value) {
        return new JAXBElement<TridaTyp>(_EntitaTypTrida_QNAME, TridaTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PodtridaTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "podtrida", scope = EntitaTyp.class)
    public JAXBElement<PodtridaTyp> createEntitaTypPodtrida(PodtridaTyp value) {
        return new JAXBElement<PodtridaTyp>(_EntitaTypPodtrida_QNAME, PodtridaTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifikaceTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "identifikace", scope = EntitaTyp.class)
    public JAXBElement<IdentifikaceTyp> createEntitaTypIdentifikace(IdentifikaceTyp value) {
        return new JAXBElement<IdentifikaceTyp>(_EntitaTypIdentifikace_QNAME, IdentifikaceTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZaznamTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "zaznam", scope = EntitaTyp.class)
    public JAXBElement<ZaznamTyp> createEntitaTypZaznam(ZaznamTyp value) {
        return new JAXBElement<ZaznamTyp>(_EntitaTypZaznam_QNAME, ZaznamTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OznaceniTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "preferovane_oznaceni", scope = EntitaTyp.class)
    public JAXBElement<OznaceniTyp> createEntitaTypPreferovaneOznaceni(OznaceniTyp value) {
        return new JAXBElement<OznaceniTyp>(_EntitaTypPreferovaneOznaceni_QNAME, OznaceniTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OznaceniTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "variantni_oznaceni", scope = EntitaTyp.class)
    public JAXBElement<OznaceniTyp> createEntitaTypVariantniOznaceni(OznaceniTyp value) {
        return new JAXBElement<OznaceniTyp>(_EntitaTypVariantniOznaceni_QNAME, OznaceniTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UdalostTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "udalost", scope = EntitaTyp.class)
    public JAXBElement<UdalostTyp> createEntitaTypUdalost(UdalostTyp value) {
        return new JAXBElement<UdalostTyp>(_EntitaTypUdalost_QNAME, UdalostTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UdalostTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "pocatek_existence", scope = EntitaTyp.class)
    public JAXBElement<UdalostTyp> createEntitaTypPocatekExistence(UdalostTyp value) {
        return new JAXBElement<UdalostTyp>(_EntitaTypPocatekExistence_QNAME, UdalostTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UdalostTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "konec_existence", scope = EntitaTyp.class)
    public JAXBElement<UdalostTyp> createEntitaTypKonecExistence(UdalostTyp value) {
        return new JAXBElement<UdalostTyp>(_EntitaTypKonecExistence_QNAME, UdalostTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UdalostTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "zmena", scope = EntitaTyp.class)
    public JAXBElement<UdalostTyp> createEntitaTypZmena(UdalostTyp value) {
        return new JAXBElement<UdalostTyp>(_EntitaTypZmena_QNAME, UdalostTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PopisTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "popis", scope = EntitaTyp.class)
    public JAXBElement<PopisTyp> createEntitaTypPopis(PopisTyp value) {
        return new JAXBElement<PopisTyp>(_EntitaTypPopis_QNAME, PopisTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SouradniceTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "souradnice", scope = EntitaTyp.class)
    public JAXBElement<SouradniceTyp> createEntitaTypSouradnice(SouradniceTyp value) {
        return new JAXBElement<SouradniceTyp>(_EntitaTypSouradnice_QNAME, SouradniceTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TitulTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "titul", scope = EntitaTyp.class)
    public JAXBElement<TitulTyp> createEntitaTypTitul(TitulTyp value) {
        return new JAXBElement<TitulTyp>(_EntitaTypTitul_QNAME, TitulTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KodovaneTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "kodovane_udaje", scope = EntitaTyp.class)
    public JAXBElement<KodovaneTyp> createEntitaTypKodovaneUdaje(KodovaneTyp value) {
        return new JAXBElement<KodovaneTyp>(_EntitaTypKodovaneUdaje_QNAME, KodovaneTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SouvisejiciTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "souvisejici_entita", scope = EntitaTyp.class)
    public JAXBElement<SouvisejiciTyp> createEntitaTypSouvisejiciEntita(SouvisejiciTyp value) {
        return new JAXBElement<SouvisejiciTyp>(_EntitaTypSouvisejiciEntita_QNAME, SouvisejiciTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StrukturaTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "hierarchicka_struktura", scope = EntitaTyp.class)
    public JAXBElement<StrukturaTyp> createEntitaTypHierarchickaStruktura(StrukturaTyp value) {
        return new JAXBElement<StrukturaTyp>(_EntitaTypHierarchickaStruktura_QNAME, StrukturaTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZarazeniTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "zarazeni", scope = EntitaTyp.class)
    public JAXBElement<ZarazeniTyp> createEntitaTypZarazeni(ZarazeniTyp value) {
        return new JAXBElement<ZarazeniTyp>(_EntitaTypZarazeni_QNAME, ZarazeniTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VyobrazeniTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "vyobrazeni", scope = EntitaTyp.class)
    public JAXBElement<VyobrazeniTyp> createEntitaTypVyobrazeni(VyobrazeniTyp value) {
        return new JAXBElement<VyobrazeniTyp>(_EntitaTypVyobrazeni_QNAME, VyobrazeniTyp.class, EntitaTyp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZdrojTyp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.interpi.cz", name = "zdroj_informaci", scope = EntitaTyp.class)
    public JAXBElement<ZdrojTyp> createEntitaTypZdrojInformaci(ZdrojTyp value) {
        return new JAXBElement<ZdrojTyp>(_EntitaTypZdrojInformaci_QNAME, ZdrojTyp.class, EntitaTyp.class, value);
    }

}
