//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.interpi.cz", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cz.tacr.elza.interpi.ws.wo;
