//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for popisTypA.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="popisTypA"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="životopis"/&gt;
 *     &lt;enumeration value="stručná charakteristika"/&gt;
 *     &lt;enumeration value="historie"/&gt;
 *     &lt;enumeration value="genealogie"/&gt;
 *     &lt;enumeration value="funkce"/&gt;
 *     &lt;enumeration value="normy konstitutivní"/&gt;
 *     &lt;enumeration value="normy - působnost původce"/&gt;
 *     &lt;enumeration value="vnitřní struktura"/&gt;
 *     &lt;enumeration value="popis"/&gt;
 *     &lt;enumeration value="geografický popis"/&gt;
 *     &lt;enumeration value="účel a využití"/&gt;
 *     &lt;enumeration value="definice"/&gt;
 *     &lt;enumeration value="pokyny k použití"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "popisTypA")
@XmlEnum
public enum PopisTypA {

    @XmlEnumValue("\u017eivotopis")
    ŽIVOTOPIS("\u017eivotopis"),
    @XmlEnumValue("stru\u010dn\u00e1 charakteristika")
    STRUČNÁ_CHARAKTERISTIKA("stru\u010dn\u00e1 charakteristika"),
    @XmlEnumValue("historie")
    HISTORIE("historie"),
    @XmlEnumValue("genealogie")
    GENEALOGIE("genealogie"),
    @XmlEnumValue("funkce")
    FUNKCE("funkce"),
    @XmlEnumValue("normy konstitutivn\u00ed")
    NORMY_KONSTITUTIVNÍ("normy konstitutivn\u00ed"),
    @XmlEnumValue("normy - p\u016fsobnost p\u016fvodce")
    NORMY_PŮSOBNOST_PŮVODCE("normy - p\u016fsobnost p\u016fvodce"),
    @XmlEnumValue("vnit\u0159n\u00ed struktura")
    VNITŘNÍ_STRUKTURA("vnit\u0159n\u00ed struktura"),
    @XmlEnumValue("popis")
    POPIS("popis"),
    @XmlEnumValue("geografick\u00fd popis")
    GEOGRAFICKÝ_POPIS("geografick\u00fd popis"),
    @XmlEnumValue("\u00fa\u010del a vyu\u017eit\u00ed")
    ÚČEL_A_VYUŽITÍ("\u00fa\u010del a vyu\u017eit\u00ed"),
    @XmlEnumValue("definice")
    DEFINICE("definice"),
    @XmlEnumValue("pokyny k pou\u017eit\u00ed")
    POKYNY_K_POUŽITÍ("pokyny k pou\u017eit\u00ed");
    private final String value;

    PopisTypA(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PopisTypA fromValue(String v) {
        for (PopisTypA c: PopisTypA.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
