//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for souradnice_systemTyp.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="souradnice_systemTyp"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="S-JTSK"/&gt;
 *     &lt;enumeration value="ETRS"/&gt;
 *     &lt;enumeration value="WGS84"/&gt;
 *     &lt;enumeration value="S-42/83"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "souradnice_systemTyp")
@XmlEnum
public enum SouradniceSystemTyp {

    @XmlEnumValue("S-JTSK")
    S_JTSK("S-JTSK"),
    ETRS("ETRS"),
    @XmlEnumValue("WGS84")
    WGS_84("WGS84"),
    @XmlEnumValue("S-42/83")
    S_42_83("S-42/83");
    private final String value;

    SouradniceSystemTyp(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SouradniceSystemTyp fromValue(String v) {
        for (SouradniceSystemTyp c: SouradniceSystemTyp.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
