//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Vlastnost specifická pro třídu geografický objekt, která umožňuje zápis souřadnic s ní souvisejících. Pro vymezení centra oblasti se použije jeden bod. Pro vymezení lineárních útvarů (řeky, trasy) je doporučeno použít minimální počet souřadnic - např. počáteční a koncový bod. Pro vymezení geografické oblasti čtyři souřadnice. Pro vymezení polygonu neomezený počet bodů na obvodu.
 * 
 * <p>Java class for souradniceTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="souradniceTyp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pouzity_system" type="{http://www.interpi.cz}souradnice_systemTyp" minOccurs="0"/&gt;
 *         &lt;element name="udaje_souradnic" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *         &lt;element name="poznamka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="typ" use="required" type="{http://www.interpi.cz}souradniceTypA" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "souradniceTyp", propOrder = {
    "pouzitySystem",
    "udajeSouradnic",
    "poznamka"
})
public class SouradniceTyp {

    @XmlElement(name = "pouzity_system")
    @XmlSchemaType(name = "string")
    protected SouradniceSystemTyp pouzitySystem;
    @XmlElement(name = "udaje_souradnic", required = true)
    protected List<String> udajeSouradnic;
    protected String poznamka;
    @XmlAttribute(name = "typ", required = true)
    protected SouradniceTypA typ;

    /**
     * Gets the value of the pouzitySystem property.
     * 
     * @return
     *     possible object is
     *     {@link SouradniceSystemTyp }
     *     
     */
    public SouradniceSystemTyp getPouzitySystem() {
        return pouzitySystem;
    }

    /**
     * Sets the value of the pouzitySystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link SouradniceSystemTyp }
     *     
     */
    public void setPouzitySystem(SouradniceSystemTyp value) {
        this.pouzitySystem = value;
    }

    /**
     * Gets the value of the udajeSouradnic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the udajeSouradnic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUdajeSouradnic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUdajeSouradnic() {
        if (udajeSouradnic == null) {
            udajeSouradnic = new ArrayList<String>();
        }
        return this.udajeSouradnic;
    }

    /**
     * Gets the value of the poznamka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoznamka() {
        return poznamka;
    }

    /**
     * Sets the value of the poznamka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoznamka(String value) {
        this.poznamka = value;
    }

    /**
     * Gets the value of the typ property.
     * 
     * @return
     *     possible object is
     *     {@link SouradniceTypA }
     *     
     */
    public SouradniceTypA getTyp() {
        return typ;
    }

    /**
     * Sets the value of the typ property.
     * 
     * @param value
     *     allowed object is
     *     {@link SouradniceTypA }
     *     
     */
    public void setTyp(SouradniceTypA value) {
        this.typ = value;
    }

}
