//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Součástí popisu entity je i vyjádření jednoduchého vztahu k jiným entitám. Jednoduchý vztah se tvoří prpojením na jinou entitu s uvedením role související entity, datace vztahu a poznámky.
 * 
 * <p>Java class for souvisejiciTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="souvisejiciTyp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifikator" type="{http://www.interpi.cz}identifikator_souvTyp" maxOccurs="unbounded"/&gt;
 *         &lt;element name="trida" type="{http://www.interpi.cz}tridaTyp"/&gt;
 *         &lt;element name="preferovane_oznaceni" type="{http://www.interpi.cz}oznaceniTyp"/&gt;
 *         &lt;element name="poznamka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="role" use="required" type="{http://www.interpi.cz}roleTypA" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "souvisejiciTyp", propOrder = {
    "identifikator",
    "trida",
    "preferovaneOznaceni",
    "poznamka"
})
public class SouvisejiciTyp {

    @XmlElement(required = true)
    protected List<IdentifikatorSouvTyp> identifikator;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TridaTyp trida;
    @XmlElement(name = "preferovane_oznaceni", required = true)
    protected OznaceniTyp preferovaneOznaceni;
    protected String poznamka;
    @XmlAttribute(name = "role", required = true)
    protected RoleTypA role;

    /**
     * Gets the value of the identifikator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifikator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifikator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifikatorSouvTyp }
     * 
     * 
     */
    public List<IdentifikatorSouvTyp> getIdentifikator() {
        if (identifikator == null) {
            identifikator = new ArrayList<IdentifikatorSouvTyp>();
        }
        return this.identifikator;
    }

    /**
     * Gets the value of the trida property.
     * 
     * @return
     *     possible object is
     *     {@link TridaTyp }
     *     
     */
    public TridaTyp getTrida() {
        return trida;
    }

    /**
     * Sets the value of the trida property.
     * 
     * @param value
     *     allowed object is
     *     {@link TridaTyp }
     *     
     */
    public void setTrida(TridaTyp value) {
        this.trida = value;
    }

    /**
     * Gets the value of the preferovaneOznaceni property.
     * 
     * @return
     *     possible object is
     *     {@link OznaceniTyp }
     *     
     */
    public OznaceniTyp getPreferovaneOznaceni() {
        return preferovaneOznaceni;
    }

    /**
     * Sets the value of the preferovaneOznaceni property.
     * 
     * @param value
     *     allowed object is
     *     {@link OznaceniTyp }
     *     
     */
    public void setPreferovaneOznaceni(OznaceniTyp value) {
        this.preferovaneOznaceni = value;
    }

    /**
     * Gets the value of the poznamka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoznamka() {
        return poznamka;
    }

    /**
     * Sets the value of the poznamka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoznamka(String value) {
        this.poznamka = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link RoleTypA }
     *     
     */
    public RoleTypA getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleTypA }
     *     
     */
    public void setRole(RoleTypA value) {
        this.role = value;
    }

}
