//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for zarazeniTypA.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="zarazeniTypA"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="obor působnosti"/&gt;
 *     &lt;enumeration value="pohlaví"/&gt;
 *     &lt;enumeration value="příslušnost k zemi"/&gt;
 *     &lt;enumeration value="určení jazykové oblasti"/&gt;
 *     &lt;enumeration value="kategorie"/&gt;
 *     &lt;enumeration value="geografická působnost"/&gt;
 *     &lt;enumeration value="charakteristika"/&gt;
 *     &lt;enumeration value="téma"/&gt;
 *     &lt;enumeration value="téma/účel"/&gt;
 *     &lt;enumeration value="obor"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "zarazeniTypA")
@XmlEnum
public enum ZarazeniTypA {

    @XmlEnumValue("obor p\u016fsobnosti")
    OBOR_PŮSOBNOSTI("obor p\u016fsobnosti"),
    @XmlEnumValue("pohlav\u00ed")
    POHLAVÍ("pohlav\u00ed"),
    @XmlEnumValue("p\u0159\u00edslu\u0161nost k zemi")
    PŘÍSLUŠNOST_K_ZEMI("p\u0159\u00edslu\u0161nost k zemi"),
    @XmlEnumValue("ur\u010den\u00ed jazykov\u00e9 oblasti")
    URČENÍ_JAZYKOVÉ_OBLASTI("ur\u010den\u00ed jazykov\u00e9 oblasti"),
    @XmlEnumValue("kategorie")
    KATEGORIE("kategorie"),
    @XmlEnumValue("geografick\u00e1 p\u016fsobnost")
    GEOGRAFICKÁ_PŮSOBNOST("geografick\u00e1 p\u016fsobnost"),
    @XmlEnumValue("charakteristika")
    CHARAKTERISTIKA("charakteristika"),
    @XmlEnumValue("t\u00e9ma")
    TÉMA("t\u00e9ma"),
    @XmlEnumValue("t\u00e9ma/\u00fa\u010del")
    TÉMA_ÚČEL("t\u00e9ma/\u00fa\u010del"),
    @XmlEnumValue("obor")
    OBOR("obor");
    private final String value;

    ZarazeniTypA(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ZarazeniTypA fromValue(String v) {
        for (ZarazeniTypA c: ZarazeniTypA.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
