//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Zdroj informací o entitě se uvádí k celému záznamu nebo ke konkrétním vlastnosti. Zdroj se uvádí v podobě stráčného standardizovaného popisu. Pokud se většina informací vybírá z obecně dostupných zdrojů, nebo jedinečného zdroje, není potřeba uvádět zdroj každé vlasnosti. Pro zmenšení objemu dat se zdroj u vlastnosti uvádí pouze jako číslo zdroje, kterým je identifikován při jeho popisu
 * 
 * <p>Java class for zdrojTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zdrojTyp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cislo_zdroje" type="{http://www.interpi.cz}cislo_zdrojeTyp"/&gt;
 *         &lt;element name="standardizovany_popis" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zdrojTyp", propOrder = {
    "cisloZdroje",
    "standardizovanyPopis"
})
public class ZdrojTyp {

    @XmlElement(name = "cislo_zdroje")
    @XmlSchemaType(name = "integer")
    protected int cisloZdroje;
    @XmlElement(name = "standardizovany_popis", required = true)
    protected String standardizovanyPopis;

    /**
     * Gets the value of the cisloZdroje property.
     * 
     */
    public int getCisloZdroje() {
        return cisloZdroje;
    }

    /**
     * Sets the value of the cisloZdroje property.
     * 
     */
    public void setCisloZdroje(int value) {
        this.cisloZdroje = value;
    }

    /**
     * Gets the value of the standardizovanyPopis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardizovanyPopis() {
        return standardizovanyPopis;
    }

    /**
     * Sets the value of the standardizovanyPopis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardizovanyPopis(String value) {
        this.standardizovanyPopis = value;
    }

}
