//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Entita může mít uvedeny identifikační čísla různých systému a to s ohledem na potřebu kooperece a sdílení dat. Alespoň jeden identifikátor je nutné uvést v případě, že není možné uvést identifikační číslo INTERPI (tj. v případě prezentace dat jiného systému pro INTERPI - zakládání nového záznamu).
 * 
 * <p>Java class for identifikator_jinyTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identifikator_jinyTyp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="identifikator_cislo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="kooperujici_system" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="druh_zaznamu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="typ" use="required" type="{http://www.interpi.cz}identifikator_jinyTypA" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identifikator_jinyTyp", propOrder = {
    "identifikatorCislo",
    "kooperujiciSystem",
    "druhZaznamu"
})
public class IdentifikatorJinyTyp {

    @XmlElement(name = "identifikator_cislo")
    protected String identifikatorCislo;
    @XmlElement(name = "kooperujici_system")
    protected String kooperujiciSystem;
    @XmlElement(name = "druh_zaznamu")
    protected String druhZaznamu;
    @XmlAttribute(name = "typ", required = true)
    protected IdentifikatorJinyTypA typ;

    /**
     * Gets the value of the identifikatorCislo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifikatorCislo() {
        return identifikatorCislo;
    }

    /**
     * Sets the value of the identifikatorCislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifikatorCislo(String value) {
        this.identifikatorCislo = value;
    }

    /**
     * Gets the value of the kooperujiciSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKooperujiciSystem() {
        return kooperujiciSystem;
    }

    /**
     * Sets the value of the kooperujiciSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKooperujiciSystem(String value) {
        this.kooperujiciSystem = value;
    }

    /**
     * Gets the value of the druhZaznamu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDruhZaznamu() {
        return druhZaznamu;
    }

    /**
     * Sets the value of the druhZaznamu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDruhZaznamu(String value) {
        this.druhZaznamu = value;
    }

    /**
     * Gets the value of the typ property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifikatorJinyTypA }
     *     
     */
    public IdentifikatorJinyTypA getTyp() {
        return typ;
    }

    /**
     * Sets the value of the typ property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifikatorJinyTypA }
     *     
     */
    public void setTyp(IdentifikatorJinyTypA value) {
        this.typ = value;
    }

}
