//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for identifikator_souvTypA.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="identifikator_souvTypA"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="INTERPI"/&gt;
 *     &lt;enumeration value="muzejní autority"/&gt;
 *     &lt;enumeration value="národní autority"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "identifikator_souvTypA")
@XmlEnum
public enum IdentifikatorSouvTypA {

    INTERPI("INTERPI"),
    @XmlEnumValue("muzejn\u00ed autority")
    MUZEJNÍ_AUTORITY("muzejn\u00ed autority"),
    @XmlEnumValue("n\u00e1rodn\u00ed autority")
    NÁRODNÍ_AUTORITY("n\u00e1rodn\u00ed autority");
    private final String value;

    IdentifikatorSouvTypA(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IdentifikatorSouvTypA fromValue(String v) {
        for (IdentifikatorSouvTypA c: IdentifikatorSouvTypA.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
