//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for jazykTyp.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="jazykTyp"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="aar"/&gt;
 *     &lt;enumeration value="abk"/&gt;
 *     &lt;enumeration value="ace"/&gt;
 *     &lt;enumeration value="afr"/&gt;
 *     &lt;enumeration value="akk"/&gt;
 *     &lt;enumeration value="alb"/&gt;
 *     &lt;enumeration value="ale"/&gt;
 *     &lt;enumeration value="amh"/&gt;
 *     &lt;enumeration value="ara"/&gt;
 *     &lt;enumeration value="arc"/&gt;
 *     &lt;enumeration value="arm"/&gt;
 *     &lt;enumeration value="arn"/&gt;
 *     &lt;enumeration value="asm"/&gt;
 *     &lt;enumeration value="ava"/&gt;
 *     &lt;enumeration value="aze"/&gt;
 *     &lt;enumeration value="bak"/&gt;
 *     &lt;enumeration value="bal"/&gt;
 *     &lt;enumeration value="bam"/&gt;
 *     &lt;enumeration value="ban"/&gt;
 *     &lt;enumeration value="baq"/&gt;
 *     &lt;enumeration value="bel"/&gt;
 *     &lt;enumeration value="ben"/&gt;
 *     &lt;enumeration value="bre"/&gt;
 *     &lt;enumeration value="bua"/&gt;
 *     &lt;enumeration value="bul"/&gt;
 *     &lt;enumeration value="bur"/&gt;
 *     &lt;enumeration value="cat"/&gt;
 *     &lt;enumeration value="ceb"/&gt;
 *     &lt;enumeration value="cop"/&gt;
 *     &lt;enumeration value="cor"/&gt;
 *     &lt;enumeration value="cos"/&gt;
 *     &lt;enumeration value="cze"/&gt;
 *     &lt;enumeration value="dan"/&gt;
 *     &lt;enumeration value="day"/&gt;
 *     &lt;enumeration value="del"/&gt;
 *     &lt;enumeration value="dgr"/&gt;
 *     &lt;enumeration value="doi"/&gt;
 *     &lt;enumeration value="dut"/&gt;
 *     &lt;enumeration value="egy"/&gt;
 *     &lt;enumeration value="eng"/&gt;
 *     &lt;enumeration value="epo"/&gt;
 *     &lt;enumeration value="esk"/&gt;
 *     &lt;enumeration value="est"/&gt;
 *     &lt;enumeration value="fao"/&gt;
 *     &lt;enumeration value="fin"/&gt;
 *     &lt;enumeration value="fre"/&gt;
 *     &lt;enumeration value="fry"/&gt;
 *     &lt;enumeration value="geo"/&gt;
 *     &lt;enumeration value="ger"/&gt;
 *     &lt;enumeration value="gez"/&gt;
 *     &lt;enumeration value="gla"/&gt;
 *     &lt;enumeration value="gle"/&gt;
 *     &lt;enumeration value="glg"/&gt;
 *     &lt;enumeration value="got"/&gt;
 *     &lt;enumeration value="grc"/&gt;
 *     &lt;enumeration value="gre"/&gt;
 *     &lt;enumeration value="guj"/&gt;
 *     &lt;enumeration value="hau"/&gt;
 *     &lt;enumeration value="haw"/&gt;
 *     &lt;enumeration value="heb"/&gt;
 *     &lt;enumeration value="hin"/&gt;
 *     &lt;enumeration value="hit"/&gt;
 *     &lt;enumeration value="hrv"/&gt;
 *     &lt;enumeration value="hun"/&gt;
 *     &lt;enumeration value="che"/&gt;
 *     &lt;enumeration value="chi"/&gt;
 *     &lt;enumeration value="chu"/&gt;
 *     &lt;enumeration value="chv"/&gt;
 *     &lt;enumeration value="chy"/&gt;
 *     &lt;enumeration value="ice"/&gt;
 *     &lt;enumeration value="ile"/&gt;
 *     &lt;enumeration value="ina"/&gt;
 *     &lt;enumeration value="ind"/&gt;
 *     &lt;enumeration value="ita"/&gt;
 *     &lt;enumeration value="jav"/&gt;
 *     &lt;enumeration value="jpn"/&gt;
 *     &lt;enumeration value="kas"/&gt;
 *     &lt;enumeration value="kaz"/&gt;
 *     &lt;enumeration value="khm"/&gt;
 *     &lt;enumeration value="kho"/&gt;
 *     &lt;enumeration value="kir"/&gt;
 *     &lt;enumeration value="kor"/&gt;
 *     &lt;enumeration value="kur"/&gt;
 *     &lt;enumeration value="lao"/&gt;
 *     &lt;enumeration value="lat"/&gt;
 *     &lt;enumeration value="lav"/&gt;
 *     &lt;enumeration value="lit"/&gt;
 *     &lt;enumeration value="ltz"/&gt;
 *     &lt;enumeration value="mac"/&gt;
 *     &lt;enumeration value="mal"/&gt;
 *     &lt;enumeration value="mao"/&gt;
 *     &lt;enumeration value="mar"/&gt;
 *     &lt;enumeration value="mas"/&gt;
 *     &lt;enumeration value="may"/&gt;
 *     &lt;enumeration value="mlt"/&gt;
 *     &lt;enumeration value="mni"/&gt;
 *     &lt;enumeration value="mol"/&gt;
 *     &lt;enumeration value="mon"/&gt;
 *     &lt;enumeration value="nep"/&gt;
 *     &lt;enumeration value="nor"/&gt;
 *     &lt;enumeration value="nub"/&gt;
 *     &lt;enumeration value="oci"/&gt;
 *     &lt;enumeration value="oss"/&gt;
 *     &lt;enumeration value="ota"/&gt;
 *     &lt;enumeration value="pan"/&gt;
 *     &lt;enumeration value="peo"/&gt;
 *     &lt;enumeration value="per"/&gt;
 *     &lt;enumeration value="phn"/&gt;
 *     &lt;enumeration value="pol"/&gt;
 *     &lt;enumeration value="por"/&gt;
 *     &lt;enumeration value="pus"/&gt;
 *     &lt;enumeration value="roh"/&gt;
 *     &lt;enumeration value="rom"/&gt;
 *     &lt;enumeration value="rum"/&gt;
 *     &lt;enumeration value="rus"/&gt;
 *     &lt;enumeration value="sah"/&gt;
 *     &lt;enumeration value="san"/&gt;
 *     &lt;enumeration value="sat"/&gt;
 *     &lt;enumeration value="scc"/&gt;
 *     &lt;enumeration value="sco"/&gt;
 *     &lt;enumeration value="scr"/&gt;
 *     &lt;enumeration value="sin"/&gt;
 *     &lt;enumeration value="slo"/&gt;
 *     &lt;enumeration value="slv"/&gt;
 *     &lt;enumeration value="smo"/&gt;
 *     &lt;enumeration value="snd"/&gt;
 *     &lt;enumeration value="som"/&gt;
 *     &lt;enumeration value="spa"/&gt;
 *     &lt;enumeration value="srp"/&gt;
 *     &lt;enumeration value="sux"/&gt;
 *     &lt;enumeration value="swa"/&gt;
 *     &lt;enumeration value="swe"/&gt;
 *     &lt;enumeration value="syr"/&gt;
 *     &lt;enumeration value="tah"/&gt;
 *     &lt;enumeration value="tam"/&gt;
 *     &lt;enumeration value="tat"/&gt;
 *     &lt;enumeration value="tel"/&gt;
 *     &lt;enumeration value="tgk"/&gt;
 *     &lt;enumeration value="tha"/&gt;
 *     &lt;enumeration value="tib"/&gt;
 *     &lt;enumeration value="tuk"/&gt;
 *     &lt;enumeration value="tur"/&gt;
 *     &lt;enumeration value="uig"/&gt;
 *     &lt;enumeration value="ukr"/&gt;
 *     &lt;enumeration value="urd"/&gt;
 *     &lt;enumeration value="uzb"/&gt;
 *     &lt;enumeration value="vie"/&gt;
 *     &lt;enumeration value="vol"/&gt;
 *     &lt;enumeration value="wel"/&gt;
 *     &lt;enumeration value="wen"/&gt;
 *     &lt;enumeration value="yid"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "jazykTyp")
@XmlEnum
public enum JazykTyp {

    @XmlEnumValue("aar")
    AAR("aar"),
    @XmlEnumValue("abk")
    ABK("abk"),
    @XmlEnumValue("ace")
    ACE("ace"),
    @XmlEnumValue("afr")
    AFR("afr"),
    @XmlEnumValue("akk")
    AKK("akk"),
    @XmlEnumValue("alb")
    ALB("alb"),
    @XmlEnumValue("ale")
    ALE("ale"),
    @XmlEnumValue("amh")
    AMH("amh"),
    @XmlEnumValue("ara")
    ARA("ara"),
    @XmlEnumValue("arc")
    ARC("arc"),
    @XmlEnumValue("arm")
    ARM("arm"),
    @XmlEnumValue("arn")
    ARN("arn"),
    @XmlEnumValue("asm")
    ASM("asm"),
    @XmlEnumValue("ava")
    AVA("ava"),
    @XmlEnumValue("aze")
    AZE("aze"),
    @XmlEnumValue("bak")
    BAK("bak"),
    @XmlEnumValue("bal")
    BAL("bal"),
    @XmlEnumValue("bam")
    BAM("bam"),
    @XmlEnumValue("ban")
    BAN("ban"),
    @XmlEnumValue("baq")
    BAQ("baq"),
    @XmlEnumValue("bel")
    BEL("bel"),
    @XmlEnumValue("ben")
    BEN("ben"),
    @XmlEnumValue("bre")
    BRE("bre"),
    @XmlEnumValue("bua")
    BUA("bua"),
    @XmlEnumValue("bul")
    BUL("bul"),
    @XmlEnumValue("bur")
    BUR("bur"),
    @XmlEnumValue("cat")
    CAT("cat"),
    @XmlEnumValue("ceb")
    CEB("ceb"),
    @XmlEnumValue("cop")
    COP("cop"),
    @XmlEnumValue("cor")
    COR("cor"),
    @XmlEnumValue("cos")
    COS("cos"),
    @XmlEnumValue("cze")
    CZE("cze"),
    @XmlEnumValue("dan")
    DAN("dan"),
    @XmlEnumValue("day")
    DAY("day"),
    @XmlEnumValue("del")
    DEL("del"),
    @XmlEnumValue("dgr")
    DGR("dgr"),
    @XmlEnumValue("doi")
    DOI("doi"),
    @XmlEnumValue("dut")
    DUT("dut"),
    @XmlEnumValue("egy")
    EGY("egy"),
    @XmlEnumValue("eng")
    ENG("eng"),
    @XmlEnumValue("epo")
    EPO("epo"),
    @XmlEnumValue("esk")
    ESK("esk"),
    @XmlEnumValue("est")
    EST("est"),
    @XmlEnumValue("fao")
    FAO("fao"),
    @XmlEnumValue("fin")
    FIN("fin"),
    @XmlEnumValue("fre")
    FRE("fre"),
    @XmlEnumValue("fry")
    FRY("fry"),
    @XmlEnumValue("geo")
    GEO("geo"),
    @XmlEnumValue("ger")
    GER("ger"),
    @XmlEnumValue("gez")
    GEZ("gez"),
    @XmlEnumValue("gla")
    GLA("gla"),
    @XmlEnumValue("gle")
    GLE("gle"),
    @XmlEnumValue("glg")
    GLG("glg"),
    @XmlEnumValue("got")
    GOT("got"),
    @XmlEnumValue("grc")
    GRC("grc"),
    @XmlEnumValue("gre")
    GRE("gre"),
    @XmlEnumValue("guj")
    GUJ("guj"),
    @XmlEnumValue("hau")
    HAU("hau"),
    @XmlEnumValue("haw")
    HAW("haw"),
    @XmlEnumValue("heb")
    HEB("heb"),
    @XmlEnumValue("hin")
    HIN("hin"),
    @XmlEnumValue("hit")
    HIT("hit"),
    @XmlEnumValue("hrv")
    HRV("hrv"),
    @XmlEnumValue("hun")
    HUN("hun"),
    @XmlEnumValue("che")
    CHE("che"),
    @XmlEnumValue("chi")
    CHI("chi"),
    @XmlEnumValue("chu")
    CHU("chu"),
    @XmlEnumValue("chv")
    CHV("chv"),
    @XmlEnumValue("chy")
    CHY("chy"),
    @XmlEnumValue("ice")
    ICE("ice"),
    @XmlEnumValue("ile")
    ILE("ile"),
    @XmlEnumValue("ina")
    INA("ina"),
    @XmlEnumValue("ind")
    IND("ind"),
    @XmlEnumValue("ita")
    ITA("ita"),
    @XmlEnumValue("jav")
    JAV("jav"),
    @XmlEnumValue("jpn")
    JPN("jpn"),
    @XmlEnumValue("kas")
    KAS("kas"),
    @XmlEnumValue("kaz")
    KAZ("kaz"),
    @XmlEnumValue("khm")
    KHM("khm"),
    @XmlEnumValue("kho")
    KHO("kho"),
    @XmlEnumValue("kir")
    KIR("kir"),
    @XmlEnumValue("kor")
    KOR("kor"),
    @XmlEnumValue("kur")
    KUR("kur"),
    @XmlEnumValue("lao")
    LAO("lao"),
    @XmlEnumValue("lat")
    LAT("lat"),
    @XmlEnumValue("lav")
    LAV("lav"),
    @XmlEnumValue("lit")
    LIT("lit"),
    @XmlEnumValue("ltz")
    LTZ("ltz"),
    @XmlEnumValue("mac")
    MAC("mac"),
    @XmlEnumValue("mal")
    MAL("mal"),
    @XmlEnumValue("mao")
    MAO("mao"),
    @XmlEnumValue("mar")
    MAR("mar"),
    @XmlEnumValue("mas")
    MAS("mas"),
    @XmlEnumValue("may")
    MAY("may"),
    @XmlEnumValue("mlt")
    MLT("mlt"),
    @XmlEnumValue("mni")
    MNI("mni"),
    @XmlEnumValue("mol")
    MOL("mol"),
    @XmlEnumValue("mon")
    MON("mon"),
    @XmlEnumValue("nep")
    NEP("nep"),
    @XmlEnumValue("nor")
    NOR("nor"),
    @XmlEnumValue("nub")
    NUB("nub"),
    @XmlEnumValue("oci")
    OCI("oci"),
    @XmlEnumValue("oss")
    OSS("oss"),
    @XmlEnumValue("ota")
    OTA("ota"),
    @XmlEnumValue("pan")
    PAN("pan"),
    @XmlEnumValue("peo")
    PEO("peo"),
    @XmlEnumValue("per")
    PER("per"),
    @XmlEnumValue("phn")
    PHN("phn"),
    @XmlEnumValue("pol")
    POL("pol"),
    @XmlEnumValue("por")
    POR("por"),
    @XmlEnumValue("pus")
    PUS("pus"),
    @XmlEnumValue("roh")
    ROH("roh"),
    @XmlEnumValue("rom")
    ROM("rom"),
    @XmlEnumValue("rum")
    RUM("rum"),
    @XmlEnumValue("rus")
    RUS("rus"),
    @XmlEnumValue("sah")
    SAH("sah"),
    @XmlEnumValue("san")
    SAN("san"),
    @XmlEnumValue("sat")
    SAT("sat"),
    @XmlEnumValue("scc")
    SCC("scc"),
    @XmlEnumValue("sco")
    SCO("sco"),
    @XmlEnumValue("scr")
    SCR("scr"),
    @XmlEnumValue("sin")
    SIN("sin"),
    @XmlEnumValue("slo")
    SLO("slo"),
    @XmlEnumValue("slv")
    SLV("slv"),
    @XmlEnumValue("smo")
    SMO("smo"),
    @XmlEnumValue("snd")
    SND("snd"),
    @XmlEnumValue("som")
    SOM("som"),
    @XmlEnumValue("spa")
    SPA("spa"),
    @XmlEnumValue("srp")
    SRP("srp"),
    @XmlEnumValue("sux")
    SUX("sux"),
    @XmlEnumValue("swa")
    SWA("swa"),
    @XmlEnumValue("swe")
    SWE("swe"),
    @XmlEnumValue("syr")
    SYR("syr"),
    @XmlEnumValue("tah")
    TAH("tah"),
    @XmlEnumValue("tam")
    TAM("tam"),
    @XmlEnumValue("tat")
    TAT("tat"),
    @XmlEnumValue("tel")
    TEL("tel"),
    @XmlEnumValue("tgk")
    TGK("tgk"),
    @XmlEnumValue("tha")
    THA("tha"),
    @XmlEnumValue("tib")
    TIB("tib"),
    @XmlEnumValue("tuk")
    TUK("tuk"),
    @XmlEnumValue("tur")
    TUR("tur"),
    @XmlEnumValue("uig")
    UIG("uig"),
    @XmlEnumValue("ukr")
    UKR("ukr"),
    @XmlEnumValue("urd")
    URD("urd"),
    @XmlEnumValue("uzb")
    UZB("uzb"),
    @XmlEnumValue("vie")
    VIE("vie"),
    @XmlEnumValue("vol")
    VOL("vol"),
    @XmlEnumValue("wel")
    WEL("wel"),
    @XmlEnumValue("wen")
    WEN("wen"),
    @XmlEnumValue("yid")
    YID("yid");
    private final String value;

    JazykTyp(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JazykTyp fromValue(String v) {
        for (JazykTyp c: JazykTyp.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
