//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Struktura označení entity. Označení je základní vlastnost každé entity. Rozlišuje se preferované a variantní označení. Každá entita musí mít určeno alespoň jedno označení. Označení se zapisují s ohledem na pravidla, podle kterých se vytváří. Označení se zapisuje také s ohledem na jeho časovou platnost a jazyk, ve kterém je zapsáno. Každá třída entit má určeno, které typy označení se považují za preferované a které za variantní. Pravidla pro tvorbu označení jsou uvedeny v Metodice.
 * 
 * <p>Java class for oznaceniTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oznaceniTyp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pravidla" type="{http://www.interpi.cz}pravidlaTyp" maxOccurs="unbounded"/&gt;
 *         &lt;element name="hlavni_cast" type="{http://www.interpi.cz}hlavni_castTyp"/&gt;
 *         &lt;element name="vedlejsi_cast" type="{http://www.interpi.cz}vedlejsi_castTyp" minOccurs="0"/&gt;
 *         &lt;element name="doplnek" type="{http://www.interpi.cz}doplnekTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="datace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="jazyk" type="{http://www.interpi.cz}jazykTyp" minOccurs="0"/&gt;
 *         &lt;element name="poznamka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cislo_zdroje" type="{http://www.interpi.cz}cislo_zdrojeTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="typ" type="{http://www.interpi.cz}oznaceni_typTypA" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oznaceniTyp", propOrder = {
    "pravidla",
    "hlavniCast",
    "vedlejsiCast",
    "doplnek",
    "datace",
    "jazyk",
    "poznamka",
    "cisloZdroje"
})
public class OznaceniTyp {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected List<PravidlaTyp> pravidla;
    @XmlElement(name = "hlavni_cast", required = true)
    protected HlavniCastTyp hlavniCast;
    @XmlElement(name = "vedlejsi_cast")
    protected VedlejsiCastTyp vedlejsiCast;
    protected List<DoplnekTyp> doplnek;
    protected String datace;
    @XmlSchemaType(name = "string")
    protected JazykTyp jazyk;
    protected String poznamka;
    @XmlElement(name = "cislo_zdroje", type = Integer.class)
    @XmlSchemaType(name = "integer")
    protected List<Integer> cisloZdroje;
    @XmlAttribute(name = "typ")
    protected OznaceniTypTypA typ;

    /**
     * Gets the value of the pravidla property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pravidla property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPravidla().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PravidlaTyp }
     * 
     * 
     */
    public List<PravidlaTyp> getPravidla() {
        if (pravidla == null) {
            pravidla = new ArrayList<PravidlaTyp>();
        }
        return this.pravidla;
    }

    /**
     * Gets the value of the hlavniCast property.
     * 
     * @return
     *     possible object is
     *     {@link HlavniCastTyp }
     *     
     */
    public HlavniCastTyp getHlavniCast() {
        return hlavniCast;
    }

    /**
     * Sets the value of the hlavniCast property.
     * 
     * @param value
     *     allowed object is
     *     {@link HlavniCastTyp }
     *     
     */
    public void setHlavniCast(HlavniCastTyp value) {
        this.hlavniCast = value;
    }

    /**
     * Gets the value of the vedlejsiCast property.
     * 
     * @return
     *     possible object is
     *     {@link VedlejsiCastTyp }
     *     
     */
    public VedlejsiCastTyp getVedlejsiCast() {
        return vedlejsiCast;
    }

    /**
     * Sets the value of the vedlejsiCast property.
     * 
     * @param value
     *     allowed object is
     *     {@link VedlejsiCastTyp }
     *     
     */
    public void setVedlejsiCast(VedlejsiCastTyp value) {
        this.vedlejsiCast = value;
    }

    /**
     * Gets the value of the doplnek property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the doplnek property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDoplnek().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DoplnekTyp }
     * 
     * 
     */
    public List<DoplnekTyp> getDoplnek() {
        if (doplnek == null) {
            doplnek = new ArrayList<DoplnekTyp>();
        }
        return this.doplnek;
    }

    /**
     * Gets the value of the datace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatace() {
        return datace;
    }

    /**
     * Sets the value of the datace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatace(String value) {
        this.datace = value;
    }

    /**
     * Gets the value of the jazyk property.
     * 
     * @return
     *     possible object is
     *     {@link JazykTyp }
     *     
     */
    public JazykTyp getJazyk() {
        return jazyk;
    }

    /**
     * Sets the value of the jazyk property.
     * 
     * @param value
     *     allowed object is
     *     {@link JazykTyp }
     *     
     */
    public void setJazyk(JazykTyp value) {
        this.jazyk = value;
    }

    /**
     * Gets the value of the poznamka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoznamka() {
        return poznamka;
    }

    /**
     * Sets the value of the poznamka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoznamka(String value) {
        this.poznamka = value;
    }

    /**
     * Gets the value of the cisloZdroje property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cisloZdroje property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCisloZdroje().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getCisloZdroje() {
        if (cisloZdroje == null) {
            cisloZdroje = new ArrayList<Integer>();
        }
        return this.cisloZdroje;
    }

    /**
     * Gets the value of the typ property.
     * 
     * @return
     *     possible object is
     *     {@link OznaceniTypTypA }
     *     
     */
    public OznaceniTypTypA getTyp() {
        return typ;
    }

    /**
     * Sets the value of the typ property.
     * 
     * @param value
     *     allowed object is
     *     {@link OznaceniTypTypA }
     *     
     */
    public void setTyp(OznaceniTypTypA value) {
        this.typ = value;
    }

}
