//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for podtridaTyp.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="podtridaTyp"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="autorská a umělecká díla"/&gt;
 *     &lt;enumeration value="všeobecně známé dokumenty, smlouvy, zákony, předpisy, normy"/&gt;
 *     &lt;enumeration value="vyznamenání, ceny, soutěžní trofeje"/&gt;
 *     &lt;enumeration value="výrobky a jejich typová označení, obchodní značky, odrůdy, plemena vytvořená člověkem"/&gt;
 *     &lt;enumeration value="názvy společenských, dětských her"/&gt;
 *     &lt;enumeration value="programy, projekty, granty"/&gt;
 *     &lt;enumeration value="stavby, trasy, zásahy do přírodních útvarů s vlastním jménem nebo jinou identifikací"/&gt;
 *     &lt;enumeration value="administrativně či jinak lidmi vymezená území"/&gt;
 *     &lt;enumeration value="administrativně vymezené části přírody"/&gt;
 *     &lt;enumeration value="vymezené obvody a správní celky"/&gt;
 *     &lt;enumeration value="geomorfologické útvary na dně moře"/&gt;
 *     &lt;enumeration value="geomorfologické útvary na zemském povrchu"/&gt;
 *     &lt;enumeration value="vodstvo a vodní plocha, vodní tok"/&gt;
 *     &lt;enumeration value="pojmenované útvary"/&gt;
 *     &lt;enumeration value="pojmenované trvalé klimatické jevy"/&gt;
 *     &lt;enumeration value="Vesmír a jeho části"/&gt;
 *     &lt;enumeration value="administrativně vymezená území s vlastní správou"/&gt;
 *     &lt;enumeration value="orgány, organizační složky a příspěvkové organizace veřejné správy"/&gt;
 *     &lt;enumeration value="sdružení organizací"/&gt;
 *     &lt;enumeration value="vojenské a bezpečnostní jednotky"/&gt;
 *     &lt;enumeration value="organizace založené za účelem podnikání"/&gt;
 *     &lt;enumeration value="politické organizace"/&gt;
 *     &lt;enumeration value="náboženské organizace a instituce"/&gt;
 *     &lt;enumeration value="kulturní, výchovné, výzkumné a zdravotnické organizace a instituce"/&gt;
 *     &lt;enumeration value="nadace a nadační fondy"/&gt;
 *     &lt;enumeration value="profesní a zájmové organizace"/&gt;
 *     &lt;enumeration value="spolky, společenské organizace"/&gt;
 *     &lt;enumeration value="pojmenované části korporací"/&gt;
 *     &lt;enumeration value="fyzická osoba"/&gt;
 *     &lt;enumeration value="fiktivní fyzická osoba"/&gt;
 *     &lt;enumeration value="bytost"/&gt;
 *     &lt;enumeration value="zvíře"/&gt;
 *     &lt;enumeration value="nepojmenované objekty a jejich fyzické části"/&gt;
 *     &lt;enumeration value="kategorie a skupiny nepojmenovaných osob"/&gt;
 *     &lt;enumeration value="kategorie a skupiny nepojmenovaných korporací"/&gt;
 *     &lt;enumeration value="materiály a techniky"/&gt;
 *     &lt;enumeration value="formy a žánry"/&gt;
 *     &lt;enumeration value="systematická nomenklatura"/&gt;
 *     &lt;enumeration value="abstraktní entity"/&gt;
 *     &lt;enumeration value="organizované akce a události"/&gt;
 *     &lt;enumeration value="ozbrojené střety (bitvy, války, obléhání…)"/&gt;
 *     &lt;enumeration value="lidové zvyky, významné dny a svátky"/&gt;
 *     &lt;enumeration value="dočasné přírodní jevy"/&gt;
 *     &lt;enumeration value="rodina, rod"/&gt;
 *     &lt;enumeration value="větev rodu"/&gt;
 *     &lt;enumeration value="fiktivní rod"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "podtridaTyp")
@XmlEnum
public enum PodtridaTyp {

    @XmlEnumValue("autorsk\u00e1 a um\u011bleck\u00e1 d\u00edla")
    AUTORSKÁ_A_UMĚLECKÁ_DÍLA("autorsk\u00e1 a um\u011bleck\u00e1 d\u00edla"),
    @XmlEnumValue("v\u0161eobecn\u011b zn\u00e1m\u00e9 dokumenty, smlouvy, z\u00e1kony, p\u0159edpisy, normy")
    VŠEOBECNĚ_ZNÁMÉ_DOKUMENTY_SMLOUVY_ZÁKONY_PŘEDPISY_NORMY("v\u0161eobecn\u011b zn\u00e1m\u00e9 dokumenty, smlouvy, z\u00e1kony, p\u0159edpisy, normy"),
    @XmlEnumValue("vyznamen\u00e1n\u00ed, ceny, sout\u011b\u017en\u00ed trofeje")
    VYZNAMENÁNÍ_CENY_SOUTĚŽNÍ_TROFEJE("vyznamen\u00e1n\u00ed, ceny, sout\u011b\u017en\u00ed trofeje"),
    @XmlEnumValue("v\u00fdrobky a jejich typov\u00e1 ozna\u010den\u00ed, obchodn\u00ed zna\u010dky, odr\u016fdy, plemena vytvo\u0159en\u00e1 \u010dlov\u011bkem")
    VÝROBKY_A_JEJICH_TYPOVÁ_OZNAČENÍ_OBCHODNÍ_ZNAČKY_ODRŮDY_PLEMENA_VYTVOŘENÁ_ČLOVĚKEM("v\u00fdrobky a jejich typov\u00e1 ozna\u010den\u00ed, obchodn\u00ed zna\u010dky, odr\u016fdy, plemena vytvo\u0159en\u00e1 \u010dlov\u011bkem"),
    @XmlEnumValue("n\u00e1zvy spole\u010densk\u00fdch, d\u011btsk\u00fdch her")
    NÁZVY_SPOLEČENSKÝCH_DĚTSKÝCH_HER("n\u00e1zvy spole\u010densk\u00fdch, d\u011btsk\u00fdch her"),
    @XmlEnumValue("programy, projekty, granty")
    PROGRAMY_PROJEKTY_GRANTY("programy, projekty, granty"),
    @XmlEnumValue("stavby, trasy, z\u00e1sahy do p\u0159\u00edrodn\u00edch \u00fatvar\u016f s vlastn\u00edm jm\u00e9nem nebo jinou identifikac\u00ed")
    STAVBY_TRASY_ZÁSAHY_DO_PŘÍRODNÍCH_ÚTVARŮ_S_VLASTNÍM_JMÉNEM_NEBO_JINOU_IDENTIFIKACÍ("stavby, trasy, z\u00e1sahy do p\u0159\u00edrodn\u00edch \u00fatvar\u016f s vlastn\u00edm jm\u00e9nem nebo jinou identifikac\u00ed"),
    @XmlEnumValue("administrativn\u011b \u010di jinak lidmi vymezen\u00e1 \u00fazem\u00ed")
    ADMINISTRATIVNĚ_ČI_JINAK_LIDMI_VYMEZENÁ_ÚZEMÍ("administrativn\u011b \u010di jinak lidmi vymezen\u00e1 \u00fazem\u00ed"),
    @XmlEnumValue("administrativn\u011b vymezen\u00e9 \u010d\u00e1sti p\u0159\u00edrody")
    ADMINISTRATIVNĚ_VYMEZENÉ_ČÁSTI_PŘÍRODY("administrativn\u011b vymezen\u00e9 \u010d\u00e1sti p\u0159\u00edrody"),
    @XmlEnumValue("vymezen\u00e9 obvody a spr\u00e1vn\u00ed celky")
    VYMEZENÉ_OBVODY_A_SPRÁVNÍ_CELKY("vymezen\u00e9 obvody a spr\u00e1vn\u00ed celky"),
    @XmlEnumValue("geomorfologick\u00e9 \u00fatvary na dn\u011b mo\u0159e")
    GEOMORFOLOGICKÉ_ÚTVARY_NA_DNĚ_MOŘE("geomorfologick\u00e9 \u00fatvary na dn\u011b mo\u0159e"),
    @XmlEnumValue("geomorfologick\u00e9 \u00fatvary na zemsk\u00e9m povrchu")
    GEOMORFOLOGICKÉ_ÚTVARY_NA_ZEMSKÉM_POVRCHU("geomorfologick\u00e9 \u00fatvary na zemsk\u00e9m povrchu"),
    @XmlEnumValue("vodstvo a vodn\u00ed plocha, vodn\u00ed tok")
    VODSTVO_A_VODNÍ_PLOCHA_VODNÍ_TOK("vodstvo a vodn\u00ed plocha, vodn\u00ed tok"),
    @XmlEnumValue("pojmenovan\u00e9 \u00fatvary")
    POJMENOVANÉ_ÚTVARY("pojmenovan\u00e9 \u00fatvary"),
    @XmlEnumValue("pojmenovan\u00e9 trval\u00e9 klimatick\u00e9 jevy")
    POJMENOVANÉ_TRVALÉ_KLIMATICKÉ_JEVY("pojmenovan\u00e9 trval\u00e9 klimatick\u00e9 jevy"),
    @XmlEnumValue("Vesm\u00edr a jeho \u010d\u00e1sti")
    VESMÍR_A_JEHO_ČÁSTI("Vesm\u00edr a jeho \u010d\u00e1sti"),
    @XmlEnumValue("administrativn\u011b vymezen\u00e1 \u00fazem\u00ed s vlastn\u00ed spr\u00e1vou")
    ADMINISTRATIVNĚ_VYMEZENÁ_ÚZEMÍ_S_VLASTNÍ_SPRÁVOU("administrativn\u011b vymezen\u00e1 \u00fazem\u00ed s vlastn\u00ed spr\u00e1vou"),
    @XmlEnumValue("org\u00e1ny, organiza\u010dn\u00ed slo\u017eky a p\u0159\u00edsp\u011bvkov\u00e9 organizace ve\u0159ejn\u00e9 spr\u00e1vy")
    ORGÁNY_ORGANIZAČNÍ_SLOŽKY_A_PŘÍSPĚVKOVÉ_ORGANIZACE_VEŘEJNÉ_SPRÁVY("org\u00e1ny, organiza\u010dn\u00ed slo\u017eky a p\u0159\u00edsp\u011bvkov\u00e9 organizace ve\u0159ejn\u00e9 spr\u00e1vy"),
    @XmlEnumValue("sdru\u017een\u00ed organizac\u00ed")
    SDRUŽENÍ_ORGANIZACÍ("sdru\u017een\u00ed organizac\u00ed"),
    @XmlEnumValue("vojensk\u00e9 a bezpe\u010dnostn\u00ed jednotky")
    VOJENSKÉ_A_BEZPEČNOSTNÍ_JEDNOTKY("vojensk\u00e9 a bezpe\u010dnostn\u00ed jednotky"),
    @XmlEnumValue("organizace zalo\u017een\u00e9 za \u00fa\u010delem podnik\u00e1n\u00ed")
    ORGANIZACE_ZALOŽENÉ_ZA_ÚČELEM_PODNIKÁNÍ("organizace zalo\u017een\u00e9 za \u00fa\u010delem podnik\u00e1n\u00ed"),
    @XmlEnumValue("politick\u00e9 organizace")
    POLITICKÉ_ORGANIZACE("politick\u00e9 organizace"),
    @XmlEnumValue("n\u00e1bo\u017eensk\u00e9 organizace a instituce")
    NÁBOŽENSKÉ_ORGANIZACE_A_INSTITUCE("n\u00e1bo\u017eensk\u00e9 organizace a instituce"),
    @XmlEnumValue("kulturn\u00ed, v\u00fdchovn\u00e9, v\u00fdzkumn\u00e9 a zdravotnick\u00e9 organizace a instituce")
    KULTURNÍ_VÝCHOVNÉ_VÝZKUMNÉ_A_ZDRAVOTNICKÉ_ORGANIZACE_A_INSTITUCE("kulturn\u00ed, v\u00fdchovn\u00e9, v\u00fdzkumn\u00e9 a zdravotnick\u00e9 organizace a instituce"),
    @XmlEnumValue("nadace a nada\u010dn\u00ed fondy")
    NADACE_A_NADAČNÍ_FONDY("nadace a nada\u010dn\u00ed fondy"),
    @XmlEnumValue("profesn\u00ed a z\u00e1jmov\u00e9 organizace")
    PROFESNÍ_A_ZÁJMOVÉ_ORGANIZACE("profesn\u00ed a z\u00e1jmov\u00e9 organizace"),
    @XmlEnumValue("spolky, spole\u010densk\u00e9 organizace")
    SPOLKY_SPOLEČENSKÉ_ORGANIZACE("spolky, spole\u010densk\u00e9 organizace"),
    @XmlEnumValue("pojmenovan\u00e9 \u010d\u00e1sti korporac\u00ed")
    POJMENOVANÉ_ČÁSTI_KORPORACÍ("pojmenovan\u00e9 \u010d\u00e1sti korporac\u00ed"),
    @XmlEnumValue("fyzick\u00e1 osoba")
    FYZICKÁ_OSOBA("fyzick\u00e1 osoba"),
    @XmlEnumValue("fiktivn\u00ed fyzick\u00e1 osoba")
    FIKTIVNÍ_FYZICKÁ_OSOBA("fiktivn\u00ed fyzick\u00e1 osoba"),
    @XmlEnumValue("bytost")
    BYTOST("bytost"),
    @XmlEnumValue("zv\u00ed\u0159e")
    ZVÍŘE("zv\u00ed\u0159e"),
    @XmlEnumValue("nepojmenovan\u00e9 objekty a jejich fyzick\u00e9 \u010d\u00e1sti")
    NEPOJMENOVANÉ_OBJEKTY_A_JEJICH_FYZICKÉ_ČÁSTI("nepojmenovan\u00e9 objekty a jejich fyzick\u00e9 \u010d\u00e1sti"),
    @XmlEnumValue("kategorie a skupiny nepojmenovan\u00fdch osob")
    KATEGORIE_A_SKUPINY_NEPOJMENOVANÝCH_OSOB("kategorie a skupiny nepojmenovan\u00fdch osob"),
    @XmlEnumValue("kategorie a skupiny nepojmenovan\u00fdch korporac\u00ed")
    KATEGORIE_A_SKUPINY_NEPOJMENOVANÝCH_KORPORACÍ("kategorie a skupiny nepojmenovan\u00fdch korporac\u00ed"),
    @XmlEnumValue("materi\u00e1ly a techniky")
    MATERIÁLY_A_TECHNIKY("materi\u00e1ly a techniky"),
    @XmlEnumValue("formy a \u017e\u00e1nry")
    FORMY_A_ŽÁNRY("formy a \u017e\u00e1nry"),
    @XmlEnumValue("systematick\u00e1 nomenklatura")
    SYSTEMATICKÁ_NOMENKLATURA("systematick\u00e1 nomenklatura"),
    @XmlEnumValue("abstraktn\u00ed entity")
    ABSTRAKTNÍ_ENTITY("abstraktn\u00ed entity"),
    @XmlEnumValue("organizovan\u00e9 akce a ud\u00e1losti")
    ORGANIZOVANÉ_AKCE_A_UDÁLOSTI("organizovan\u00e9 akce a ud\u00e1losti"),
    @XmlEnumValue("ozbrojen\u00e9 st\u0159ety (bitvy, v\u00e1lky, obl\u00e9h\u00e1n\u00ed\u2026)")
    OZBROJENÉ_STŘETY_BITVY_VÁLKY_OBLÉHÁNÍ("ozbrojen\u00e9 st\u0159ety (bitvy, v\u00e1lky, obl\u00e9h\u00e1n\u00ed\u2026)"),
    @XmlEnumValue("lidov\u00e9 zvyky, v\u00fdznamn\u00e9 dny a sv\u00e1tky")
    LIDOVÉ_ZVYKY_VÝZNAMNÉ_DNY_A_SVÁTKY("lidov\u00e9 zvyky, v\u00fdznamn\u00e9 dny a sv\u00e1tky"),
    @XmlEnumValue("do\u010dasn\u00e9 p\u0159\u00edrodn\u00ed jevy")
    DOČASNÉ_PŘÍRODNÍ_JEVY("do\u010dasn\u00e9 p\u0159\u00edrodn\u00ed jevy"),
    @XmlEnumValue("rodina, rod")
    RODINA_ROD("rodina, rod"),
    @XmlEnumValue("v\u011btev rodu")
    VĚTEV_RODU("v\u011btev rodu"),
    @XmlEnumValue("fiktivn\u00ed rod")
    FIKTIVNÍ_ROD("fiktivn\u00ed rod");
    private final String value;

    PodtridaTyp(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PodtridaTyp fromValue(String v) {
        for (PodtridaTyp c: PodtridaTyp.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
