//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for poznamkaTypA.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="poznamkaTypA"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="veřejná poznámka"/&gt;
 *     &lt;enumeration value="neveřejná poznámka"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "poznamkaTypA")
@XmlEnum
public enum PoznamkaTypA {

    @XmlEnumValue("ve\u0159ejn\u00e1 pozn\u00e1mka")
    VEŘEJNÁ_POZNÁMKA("ve\u0159ejn\u00e1 pozn\u00e1mka"),
    @XmlEnumValue("neve\u0159ejn\u00e1 pozn\u00e1mka")
    NEVEŘEJNÁ_POZNÁMKA("neve\u0159ejn\u00e1 pozn\u00e1mka");
    private final String value;

    PoznamkaTypA(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PoznamkaTypA fromValue(String v) {
        for (PoznamkaTypA c: PoznamkaTypA.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
