//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for souradniceTypA.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="souradniceTypA"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="centrum oblasti"/&gt;
 *     &lt;enumeration value="lineární útvar"/&gt;
 *     &lt;enumeration value="geografická oblast"/&gt;
 *     &lt;enumeration value="polygon"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "souradniceTypA")
@XmlEnum
public enum SouradniceTypA {

    @XmlEnumValue("centrum oblasti")
    CENTRUM_OBLASTI("centrum oblasti"),
    @XmlEnumValue("line\u00e1rn\u00ed \u00fatvar")
    LINEÁRNÍ_ÚTVAR("line\u00e1rn\u00ed \u00fatvar"),
    @XmlEnumValue("geografick\u00e1 oblast")
    GEOGRAFICKÁ_OBLAST("geografick\u00e1 oblast"),
    @XmlEnumValue("polygon")
    POLYGON("polygon");
    private final String value;

    SouradniceTypA(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SouradniceTypA fromValue(String v) {
        for (SouradniceTypA c: SouradniceTypA.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
