//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Hierarchická struktura je specifická vlatnost pro třídu geografický objekt. Vychází z požadavku komunity archivů, uvádět úplnou hierarchickou strukturu - umístění entity. Hierarchická struktura se zapisuje jako pořadí nadřazených prvků s tím, že se začína nejvyšší úrovní (stát) a pokračuje úrovněmi: kraj, okres, obec, místní část.
 * 
 * <p>Java class for strukturaTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="strukturaTyp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="souvisejici_entita" type="{http://www.interpi.cz}souvisejici_minTyp"/&gt;
 *         &lt;element name="poznamka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="typ" use="required" type="{http://www.interpi.cz}strukturaTypA" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "strukturaTyp", propOrder = {
    "souvisejiciEntita",
    "poznamka"
})
public class StrukturaTyp {

    @XmlElement(name = "souvisejici_entita", required = true)
    protected SouvisejiciMinTyp souvisejiciEntita;
    protected String poznamka;
    @XmlAttribute(name = "typ", required = true)
    protected int typ;

    /**
     * Gets the value of the souvisejiciEntita property.
     * 
     * @return
     *     possible object is
     *     {@link SouvisejiciMinTyp }
     *     
     */
    public SouvisejiciMinTyp getSouvisejiciEntita() {
        return souvisejiciEntita;
    }

    /**
     * Sets the value of the souvisejiciEntita property.
     * 
     * @param value
     *     allowed object is
     *     {@link SouvisejiciMinTyp }
     *     
     */
    public void setSouvisejiciEntita(SouvisejiciMinTyp value) {
        this.souvisejiciEntita = value;
    }

    /**
     * Gets the value of the poznamka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoznamka() {
        return poznamka;
    }

    /**
     * Sets the value of the poznamka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoznamka(String value) {
        this.poznamka = value;
    }

    /**
     * Gets the value of the typ property.
     * 
     */
    public int getTyp() {
        return typ;
    }

    /**
     * Sets the value of the typ property.
     * 
     */
    public void setTyp(int value) {
        this.typ = value;
    }

}
