//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Událost představuje komplexní vztah v popisu entity. Je tvořena souborem propojení na jiné entity. Obvykle se odehrává na nějakém místě, za přítomnosti různých osob, v průběhu popsané události, s přičiněním korporace apod. Událost je tak tvořena propojením na více typů entit v různých rolích, datací a poznámkou.
 * 
 * <p>Java class for udalostTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="udalostTyp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="souvisejici_entita" type="{http://www.interpi.cz}souvisejiciTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="datace" type="{http://www.interpi.cz}komplexni_dataceTyp" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element name="poznamka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cislo_zdroje" type="{http://www.interpi.cz}cislo_zdrojeTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="typ" use="required" type="{http://www.interpi.cz}udalostTypA" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "udalostTyp", propOrder = {
    "souvisejiciEntita",
    "datace",
    "poznamka",
    "cisloZdroje"
})
public class UdalostTyp {

    @XmlElement(name = "souvisejici_entita")
    protected List<SouvisejiciTyp> souvisejiciEntita;
    protected List<KomplexniDataceTyp> datace;
    protected String poznamka;
    @XmlElement(name = "cislo_zdroje", type = Integer.class)
    @XmlSchemaType(name = "integer")
    protected List<Integer> cisloZdroje;
    @XmlAttribute(name = "typ", required = true)
    protected UdalostTypA typ;

    /**
     * Gets the value of the souvisejiciEntita property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the souvisejiciEntita property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSouvisejiciEntita().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SouvisejiciTyp }
     * 
     * 
     */
    public List<SouvisejiciTyp> getSouvisejiciEntita() {
        if (souvisejiciEntita == null) {
            souvisejiciEntita = new ArrayList<SouvisejiciTyp>();
        }
        return this.souvisejiciEntita;
    }

    /**
     * Gets the value of the datace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KomplexniDataceTyp }
     * 
     * 
     */
    public List<KomplexniDataceTyp> getDatace() {
        if (datace == null) {
            datace = new ArrayList<KomplexniDataceTyp>();
        }
        return this.datace;
    }

    /**
     * Gets the value of the poznamka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoznamka() {
        return poznamka;
    }

    /**
     * Sets the value of the poznamka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoznamka(String value) {
        this.poznamka = value;
    }

    /**
     * Gets the value of the cisloZdroje property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cisloZdroje property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCisloZdroje().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getCisloZdroje() {
        if (cisloZdroje == null) {
            cisloZdroje = new ArrayList<Integer>();
        }
        return this.cisloZdroje;
    }

    /**
     * Gets the value of the typ property.
     * 
     * @return
     *     possible object is
     *     {@link UdalostTypA }
     *     
     */
    public UdalostTypA getTyp() {
        return typ;
    }

    /**
     * Sets the value of the typ property.
     * 
     * @param value
     *     allowed object is
     *     {@link UdalostTypA }
     *     
     */
    public void setTyp(UdalostTypA value) {
        this.typ = value;
    }

}
