//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vedlejsi_castTypA.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="vedlejsi_castTypA"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="číselné označení"/&gt;
 *     &lt;enumeration value="obsazení hudebního díla"/&gt;
 *     &lt;enumeration value="tónina hudebního díla"/&gt;
 *     &lt;enumeration value="údaj o aranžmá hudebního díla"/&gt;
 *     &lt;enumeration value="název části díla/výtvoru"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "vedlejsi_castTypA")
@XmlEnum
public enum VedlejsiCastTypA {

    @XmlEnumValue("\u010d\u00edseln\u00e9 ozna\u010den\u00ed")
    ČÍSELNÉ_OZNAČENÍ("\u010d\u00edseln\u00e9 ozna\u010den\u00ed"),
    @XmlEnumValue("obsazen\u00ed hudebn\u00edho d\u00edla")
    OBSAZENÍ_HUDEBNÍHO_DÍLA("obsazen\u00ed hudebn\u00edho d\u00edla"),
    @XmlEnumValue("t\u00f3nina hudebn\u00edho d\u00edla")
    TÓNINA_HUDEBNÍHO_DÍLA("t\u00f3nina hudebn\u00edho d\u00edla"),
    @XmlEnumValue("\u00fadaj o aran\u017em\u00e1 hudebn\u00edho d\u00edla")
    ÚDAJ_O_ARANŽMÁ_HUDEBNÍHO_DÍLA("\u00fadaj o aran\u017em\u00e1 hudebn\u00edho d\u00edla"),
    @XmlEnumValue("n\u00e1zev \u010d\u00e1sti d\u00edla/v\u00fdtvoru")
    NÁZEV_ČÁSTI_DÍLA_VÝTVORU("n\u00e1zev \u010d\u00e1sti d\u00edla/v\u00fdtvoru");
    private final String value;

    VedlejsiCastTypA(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VedlejsiCastTypA fromValue(String v) {
        for (VedlejsiCastTypA c: VedlejsiCastTypA.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
