//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.24 at 04:42:06 PM CET 
//


package cz.tacr.elza.interpi.ws.wo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Údaje o záznamu entity. Převážně služební informace včetně jazyku zpracování entity.
 * 
 * <p>Java class for zaznamTyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zaznamTyp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="stav" type="{http://www.interpi.cz}stavTyp"/&gt;
 *         &lt;element name="jazyk" type="{http://www.interpi.cz}jazykTyp"/&gt;
 *         &lt;element name="historie_zaznamu" type="{http://www.interpi.cz}historie_zaznamuTyp"/&gt;
 *         &lt;element name="souhlas" type="{http://www.interpi.cz}souhlasTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="poznamka" type="{http://www.interpi.cz}poznamkaTyp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zaznamTyp", propOrder = {
    "stav",
    "jazyk",
    "historieZaznamu",
    "souhlas",
    "poznamka"
})
public class ZaznamTyp {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected StavTyp stav;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected JazykTyp jazyk;
    @XmlElement(name = "historie_zaznamu", required = true)
    protected HistorieZaznamuTyp historieZaznamu;
    protected List<SouhlasTyp> souhlas;
    protected List<PoznamkaTyp> poznamka;

    /**
     * Gets the value of the stav property.
     * 
     * @return
     *     possible object is
     *     {@link StavTyp }
     *     
     */
    public StavTyp getStav() {
        return stav;
    }

    /**
     * Sets the value of the stav property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavTyp }
     *     
     */
    public void setStav(StavTyp value) {
        this.stav = value;
    }

    /**
     * Gets the value of the jazyk property.
     * 
     * @return
     *     possible object is
     *     {@link JazykTyp }
     *     
     */
    public JazykTyp getJazyk() {
        return jazyk;
    }

    /**
     * Sets the value of the jazyk property.
     * 
     * @param value
     *     allowed object is
     *     {@link JazykTyp }
     *     
     */
    public void setJazyk(JazykTyp value) {
        this.jazyk = value;
    }

    /**
     * Gets the value of the historieZaznamu property.
     * 
     * @return
     *     possible object is
     *     {@link HistorieZaznamuTyp }
     *     
     */
    public HistorieZaznamuTyp getHistorieZaznamu() {
        return historieZaznamu;
    }

    /**
     * Sets the value of the historieZaznamu property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistorieZaznamuTyp }
     *     
     */
    public void setHistorieZaznamu(HistorieZaznamuTyp value) {
        this.historieZaznamu = value;
    }

    /**
     * Gets the value of the souhlas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the souhlas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSouhlas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SouhlasTyp }
     * 
     * 
     */
    public List<SouhlasTyp> getSouhlas() {
        if (souhlas == null) {
            souhlas = new ArrayList<SouhlasTyp>();
        }
        return this.souhlas;
    }

    /**
     * Gets the value of the poznamka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the poznamka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoznamka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PoznamkaTyp }
     * 
     * 
     */
    public List<PoznamkaTyp> getPoznamka() {
        if (poznamka == null) {
            poznamka = new ArrayList<PoznamkaTyp>();
        }
        return this.poznamka;
    }

}
