package ZP2015;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

rule "Doporučené atributy pro obaly"
no-loop
when
    $itemType : RulItemTypeExt(code in ("ZP2015_PACKET_TYPE", "ZP2015_PACKET_PREFIX", "ZP2015_PACKET_NUMBER",
                                        "ZP2015_PACKET_POSTFIX"))
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Možné atributy pro obaly"
no-loop
when
    $itemType : RulItemTypeExt(code in ("ZP2015_PACKET_DESCRIPTION"))
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Typy obalů"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_PACKET_TYPE")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_PACKET_TYPE_BOX", "ZP2015_PACKET_TYPE_FASCICLE")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end
