package isaarcpf;
import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec;
import cz.tacr.elza.drools.model.item.IntItem;
import cz.tacr.elza.drools.model.Part;
import cz.tacr.elza.drools.model.PartType;

rule "Kind of beginning"
when $it: ItemType(code == "CRE_CLASS")
     $is: ItemSpec(code in ("CRC_BIRTH")) from $it.specs
then
    $it.setPossible();
    $is.setPossible();
end

