package drlglobal;
import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec
import cz.tacr.elza.drools.model.RequiredType;
import cz.tacr.elza.drools.model.item.Item;
import cz.tacr.elza.drools.model.Ap;
import cz.tacr.elza.drools.model.Part;
import cz.tacr.elza.drools.model.PartType;


rule "R_CRE_002 Použití způsobu vzniku"
when $it: ItemType(code in ("CRE_CLASS"))
then
    $it.setRequired();
end

rule "R_CRE_004 Použití datace vzniku"
when $it: ItemType(code in ("CRE_DATE"))
then
    $it.setPossible();
end
