package drlglobal;
import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec
import cz.tacr.elza.drools.model.RequiredType;
import cz.tacr.elza.drools.model.item.Item;
import cz.tacr.elza.drools.model.Ap;
import cz.tacr.elza.drools.model.Part;
import cz.tacr.elza.drools.model.PartType;


rule "R_EXT_002 Použití způsobu zániku"
when $it: ItemType(code in ("EXT_CLASS"))
then
    $it.setRequired();
end

rule "R_EXT_004 Použití datace zániku"
when $it: ItemType(code in ("EXT_DATE"))
then
    $it.setPossible();
end
