package drlglobal;
import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec
import cz.tacr.elza.drools.model.RequiredType;
import cz.tacr.elza.drools.model.item.IntItem;
import cz.tacr.elza.drools.model.Ap;
import cz.tacr.elza.drools.model.Part;
import cz.tacr.elza.drools.model.PartType;

rule "R_REL_002 Použití typu vztahu u odkazu na jinou entitu"
when $it: ItemType(code in ("REL_ENTITY"))
then
    $it.setRequired();
end

rule "R_REL_002.2 Použití typu vztahu u odkazu na jinou entitu"
/*
Možnost datace u vztahů.
Týká se i:
    R_CRE_005 Použití vztahů u vzniku
    R_EXT_005 Použití vztahů u zániku
    R_EVE_003 Použití vztahů u události
*/
when $i: IntItem(type == "REL_ENTITY", spec in ("RT_ENTITYBIRTH" ,"RT_ENTITYRISE" ,"RT_ENTITYORIGIN" ,"RT_ENTITYDEATH" ,"RT_ENTITYEXTINCTION" ,"RT_ENTITYEND" ,"RT_PLACE" ,"RT_SENIOR" ,"RT_ACTIVITYFIELD" ,"RT_COLLABORATOR" ,"RT_REPRESENT" ,"RT_MILESTONE" ,"RT_STUDYFIELD" ,"RT_SCHOOLMATE" ,"RT_TEACHER" ,"RT_AUTHOROFCHANGE" ,"RT_WHOLE" ,"RT_GEOSCOPE" ,"RT_ISPART" ,"RT_OWNER" , "RT_HOLDER" , "RT_VENUE" ,"RT_SUPCORP" ,"RT_PARTNER","RT_GEOPARTNER" ,"RT_SHEPARTNER" ,"RT_NAMEDAFTER" ,"RT_AFFILIATION" ,"RT_RESIDENCE" ,"RT_STORAGE" ,"RT_LOCATION" ,"RT_OBJECT" ,"RT_ACTIVITIES" ,"RT_NAMECHANGE" ,"RT_MENTION","RT_FUNCTION"))
     $it: ItemType(code in ("REL_BEGIN","REL_END"))
then
    $it.setPossible();
end
