elza:
  data:
      url: jdbc:postgresql://vyv-db.marbes.cz/elza_demo
      user: postgres
      pass: postgres


  treenode:
      title: ZP2015_TITLE
#  rules:
#    ZP:
#      default:
#        - NORMAL