elza:
  data:
      jdbc:postgresql://vyv-db.marbes.cz/elza_demo
      user: postgres
      pass: postgres
#  rules:
#    ZP:
#      default:
#        - NORMAL
spring:
  jpa:
    # Logovani SQL dotazu
    show-sql: true
