elza:
  data:
      # Database connection
      url: jdbc:postgresql://localhost/elza
      user: app
      pass: app
  # Elza working directory. Set absolute path to the working directory
  workingDir: D:\Elza\work

spring:
  jpa:
      properties:
          hibernate:
              # Set database type and dialect for the database
              # PostgreSQL
              dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
              # H2
              #dialect: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
              # MySQL
              #dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
              # Oracle
              #dialect: org.hibernate.spatial.dialect.oracle.OracleSpatial10gDialect
              # MSSQL
              #dialect: org.hibernate.dialect.SQLServer2008Dialect

multipart.maxFileSize: 10000000
