package ZP2015;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

rule "Vypnutí opakovatelnosti"
salience 100
no-loop
when
  $itemType : RulItemTypeExt(code in ( // nastaveni pro ulozeni
		"ZP2015_RESTRICTED_ACCESS_TYPE", 
        "ZP2015_RESTRICTION_ACCESS_DATE",
        "ZP2015_NOTE"))
then
  $itemType.setRepeatable(false);
end

rule "Doporučené prvky popisu"
no-loop
when
    $itemType : RulItemTypeExt(code in (
		"ZP2015_RESTRICTED_ACCESS_TYPE", 
        "ZP2015_RESTRICTION_ACCESS_DATE"))
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Možné prvky popisu"
no-loop
when
    $itemType : RulItemTypeExt(code in (
		"ZP2015_NOTE"))
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Možné typy omezení"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_RESTRICTED_ACCESS_TYPE")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_ACCESS_STATUTORY_DEADLINE",
                                        "ZP2015_ACCESS_PERSONAL_DATA",
                                        "ZP2015_ACCESS_PERSONAL_DATA2")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end
