package ZP2015.altdescription;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;
import cz.tacr.elza.drools.model.StructObjItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

rule "Vypnutí opakovatelnosti"
salience 100
no-loop
when
  $itemType : RulItemTypeExt(code in ( // nastaveni pro ulozeni
        "ZP2015_ARCHDESC_LANG", 
        "ZP2015_TITLE",
		"ZP2015_FORMAL_TITLE",
        "ZP2015_UNIT_DATE_TEXT",
        "ZP2015_UNIT_HIST",
        "ZP2015_UNIT_ARR",
        "ZP2015_UNIT_CONTENT",
        "ZP2015_UNIT_SOURCE",
        "ZP2015_FUTURE_UNITS",
        "ZP2015_UNIT_ACCESS",
        "ZP2015_UNIT_INFO_RIGHTS",
        "ZP2015_UNIT_COPY_RIGHTS",
        "ZP2015_UNIT_CURRENT_STATUS",
        "ZP2015_COPY_SOURCE",
        "ZP2015_RELATED_UNITS",
        "ZP2015_EXISTING_COPY",
        "ZP2015_NOTE",
        "ZP2015_ARRANGEMENT_INFO",
        "ZP2015_ARRANGE_RULES",
        "ZP2015_STORAGE_COND",
        "ZP2015_SIZE",
        "ZP2015_ITEM_MAT",
        "ZP2015_PART",
        "ZP2015_WRITING",
        "ZP2015_EDITION"))
then
  $itemType.setRepeatable(false);
end

rule "Povinné prvky popisu"
no-loop
when
    $itemType : RulItemTypeExt(code in (
		"ZP2015_ARCHDESC_LANG"))
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Doporučené prvky popisu"
no-loop
when
    $itemType : RulItemTypeExt(code in (
		"ZP2015_TITLE"))
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Vždy možné prvky popisu"
no-loop
when
    $itemType : RulItemTypeExt(code in (
		"ZP2015_FORMAL_TITLE",
        "ZP2015_UNIT_DATE_TEXT",
        "ZP2015_UNIT_HIST",
        "ZP2015_UNIT_ARR",
        "ZP2015_UNIT_CONTENT",
        "ZP2015_UNIT_SOURCE",
        "ZP2015_FUTURE_UNITS",
        "ZP2015_UNIT_ACCESS",
        "ZP2015_UNIT_INFO_RIGHTS",
        "ZP2015_UNIT_COPY_RIGHTS",
        "ZP2015_UNIT_CURRENT_STATUS",
        "ZP2015_COPY_SOURCE",
        "ZP2015_RELATED_UNITS",
        "ZP2015_EXISTING_COPY",
        "ZP2015_NOTE",
        "ZP2015_ARRANGEMENT_INFO",
        "ZP2015_ARRANGE_RULES",
        "ZP2015_STORAGE_COND",
        "ZP2015_SIZE",
        "ZP2015_ITEM_MAT",
        "ZP2015_PART",
        "ZP2015_WRITING",
        "ZP2015_EDITION"))
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Povolení všech jazyků archivního popisu
rule "Povolení všech jazyků archivního popisu (ZP2015_ARCHDESC_LANG)"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_ARCHDESC_LANG")
    $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end
