package ZP2015.altdescription;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;
import cz.tacr.elza.drools.model.StructObjItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

rule "Vypnutí opakovatelnosti"
salience 100
no-loop
when
  $itemType : RulItemTypeExt(code in ( // nastaveni pro ulozeni
        "ZP2015_LANGUAGE", 
        "ZP2015_TITLE", 
        "ZP2015_NOTE"))
then
  $itemType.setRepeatable(false);
end

rule "Povinné prvky popisu"
no-loop
when
    $itemType : RulItemTypeExt(code in (
		"ZP2015_LANGUAGE"))
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Doporučené prvky popisu"
no-loop
when
    $itemType : RulItemTypeExt(code in (
		"ZP2015_TITLE"))
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Vždy možné prvky popisu"
no-loop
when
    $itemType : RulItemTypeExt(code in (
		"ZP2015_NOTE"))
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Povolení všech jazyků
rule "Povolení všech jazyků (ZP2015_LANGUAGE)"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LANGUAGE")
    $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end
