package ZP2015.origstruct;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

rule "Mozne v ramci zjednoduseneho puvodce"
when
  $itemType : RulItemTypeExt(code in ( 
               "HISTORY", "GENEALOGY", "BIOGRAPHY",
               "CORP_PURPOSE", "FOUNDING_NORMS", "SCOPE_NORMS", "CORP_STRUCTURE"
              ) )
then
  $itemType.setRepeatable(false);
  $itemType.setType(RulItemType.Type.POSSIBLE);
end
