package ZP2015;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

// Přidání metráže jako povinné
rule "Povinná metráž"
no-loop
when
    $itemType : RulItemTypeExt(code in ("ZP2015_PACKET_METRAGE"))
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end
