package drlglobal;

import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec;

rule "R_BOD_002 Použití prvků popisu pro záznam (tělo entity)"
when $it: ItemType(code in ("HISTORY","GENEALOGY"))
then
    $it.setPossible();
end

rule "R_BOD_002 Použití prvků popisu pro záznam (tělo entity - BRIEF_DESC)"
when $it: ItemType(code in ("BRIEF_DESC"))
then
    $it.setRequired();
end
