package cz.tacr.elza.ws.dao_service.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-08T12:26:59.874+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://elza.tacr.cz/ws/dao-service/v1", name = "DaoRequests")
@XmlSeeAlso({cz.tacr.elza.ws.types.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DaoRequests {

    @WebMethod(operationName = "PostDestructionRequest")
    @WebResult(name = "requestId", targetNamespace = "", partName = "requestId")
    public java.lang.String postDestructionRequest(
        @WebParam(partName = "destructionRequest", name = "destructionRequest", targetNamespace = "")
        cz.tacr.elza.ws.types.v1.DestructionRequest destructionRequest
    ) throws DaoServiceException;

    @WebMethod(operationName = "PostTransferRequest")
    @WebResult(name = "requestId", targetNamespace = "", partName = "requestId")
    public java.lang.String postTransferRequest(
        @WebParam(partName = "transferRequest", name = "transferRequest", targetNamespace = "")
        cz.tacr.elza.ws.types.v1.TransferRequest transferRequest
    ) throws DaoServiceException;
}
