package drlglobal;
import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec
import cz.tacr.elza.drools.model.RequiredType;
import cz.tacr.elza.drools.model.item.Item;
import cz.tacr.elza.drools.model.Ap;
import cz.tacr.elza.drools.model.Part;
import cz.tacr.elza.drools.model.PartType;

rule "R_IDN_003 Použití typu identifikátoru dle třídy/podtřídy"
when $it: ItemType(code == "IDN_TYPE")
     $is : ItemSpec(code in ("NUTSLAU","CZ_RETRO","RUIAN")) from $it.specs
then
    $is.setPossible();
end


rule "R_IDN_008 Použití kódu ISO 3166-1"
when
    $ae: Ap( )
    $partBody: Part(type == PartType.PT_BODY) from $ae.parts
    Item(type == "GEO_TYPE", spec in ("GT_COUNTRY", "GT_CONTINENT")) from $partBody.items
    $it: ItemType(code == "IDN_TYPE")
    $is : ItemSpec(code in ("ISO3166_2","ISO3166_3","ISO3166_NUM")) from $it.specs
then
    $is.setPossible();
end

rule "R_IDN_009 Použití kódu ISO 3166-2"
when
    $ae: Ap( )
    $partBody: Part(type == PartType.PT_BODY) from $ae.parts
    Item(type == "GEO_TYPE", spec in ("GT_ADMREGION","GT_DISTRICT","GT_AUTONOMOUSPART","GT_LAND","GT_AREA","GT_REGION","GT_CANTON","GT_OKRUH","GT_COUNTY","GT_PROVINCE","GT_VOJVODSTVI","GT_DEPARTEMENT","GT_SHIRE","GT_TERRITORIALUNIT")) from $partBody.items
    $it: ItemType(code == "IDN_TYPE")
    $is : ItemSpec(code in ("ISO3166_PART2")) from $it.specs
then
    $is.setPossible();
end
