package drlglobal;
import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec
import cz.tacr.elza.drools.model.RequiredType;
import cz.tacr.elza.drools.model.item.Item;
import cz.tacr.elza.drools.model.Ap;
import cz.tacr.elza.drools.model.Part;
import cz.tacr.elza.drools.model.PartType;


rule "R_REL_002 Použití typu vztahu u odkazu na jinou entitu"
when $part: Part(parent == null)
     $it: ItemType(code == "REL_ENTITY")
     $is : ItemSpec(code in ("RT_VENUE", "RT_NAMEDAFTER", "RT_COMPEVENT", "RT_THEME", "RT_OBJECT")) from $it.specs
then
    $is.setPossible();
    $is.setRepeatable(true);
end

rule "R_CRE_005 Použití vztahů u vzniku"
when $part: Part(parent != null)
     $parent: Part(type == PartType.PT_CRE) from $part.parent
     $parentItem: Item(type == "CRE_CLASS", spec == "CRC_ORIGIN") from $parent.items
     $it: ItemType(code == "REL_ENTITY")
     $is : ItemSpec(code in ("RT_DOCUMENT", "RT_ENTITYORIGIN", "RT_PLACE", "RT_ORGANIZER")) from $it.specs
then
    $is.setPossible();
    $is.setRepeatable(true);
end

rule "R_EXT_005 Použití vztahů u zániku"
when $part: Part(parent != null)
     $parent: Part(type == PartType.PT_EXT) from $part.parent
     $parentItem: Item(type == "EXT_CLASS", spec == "EXC_END") from $parent.items
     $it: ItemType(code == "REL_ENTITY")
     $is : ItemSpec(code in ("RT_DOCUMENT","RT_ENTITYEND","RT_PLACE")) from $it.specs
then
    $is.setPossible();
    $is.setRepeatable(true);
end



