package SimpleDev;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

rule "Doporučené atributy pro obaly"
no-loop
when
    $itemType : RulItemTypeExt(code in ("SRD_ACCESS_RESTRICTION_NAME", "SRD_ACCESS_RESTRICTION_DESCRIPTION"))
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end
