package ZP2015;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

// Povinné položky
rule "Povinné"
no-loop
when
    $itemType : RulItemTypeExt(code in ("AP_NAME"))
then
    $itemType.setType(RulItemType.Type.REQUIRED);
    $itemType.setRepeatable(false);
end

// Doporučení položky
rule "Doporučené"
no-loop
when
    $itemType : RulItemTypeExt(code in ("AP_COMPLEMENT"))
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
    $itemType.setRepeatable(false);
end

// Možné
rule "Možné"
no-loop
when
    $itemType : RulItemTypeExt(code in ("AP_DESCRIPTION"))
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setRepeatable(false);
end
