package cz.tacr.elza.ws.dao_service.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2019-06-21T09:42:07.153+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://elza.tacr.cz/ws/dao-service/v1", name = "DaoNotifications")
@XmlSeeAlso({cz.tacr.elza.ws.types.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DaoNotifications {

    @WebMethod(operationName = "OnDaoLinked", action = "OnDaoLinked")
    public void onDaoLinked(
            @WebParam(partName = "onDaoLinked", name = "onDaoLinked", targetNamespace = "")
                    cz.tacr.elza.ws.types.v1.OnDaoLinked onDaoLinked
    ) throws DaoServiceException;

    @WebMethod(operationName = "OnDaoUnlinked", action = "OnDaoUnlinked")
    public void onDaoUnlinked(
            @WebParam(partName = "onDaoUnlinked", name = "onDaoUnlinked", targetNamespace = "")
                    cz.tacr.elza.ws.types.v1.OnDaoUnlinked onDaoUnlinked
    ) throws DaoServiceException;
}
