package cz.tacr.elza.ws.dao_service.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2019-06-21T09:42:07.171+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://elza.tacr.cz/ws/dao-service/v1", name = "DaoRequests")
@XmlSeeAlso({cz.tacr.elza.ws.types.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DaoRequests {

    @WebMethod(operationName = "PostDestructionRequest", action = "PostDestructionRequest")
    @WebResult(name = "requestId", targetNamespace = "", partName = "requestId")
    public String postDestructionRequest(
            @WebParam(partName = "destructionRequest", name = "destructionRequest", targetNamespace = "")
                    cz.tacr.elza.ws.types.v1.DestructionRequest destructionRequest
    ) throws DaoServiceException;

    @WebMethod(operationName = "PostTransferRequest", action = "PostTransferRequest")
    @WebResult(name = "requestId", targetNamespace = "", partName = "requestId")
    public String postTransferRequest(
            @WebParam(partName = "transferRequest", name = "transferRequest", targetNamespace = "")
                    cz.tacr.elza.ws.types.v1.TransferRequest transferRequest
    ) throws DaoServiceException;

    @WebMethod(operationName = "SyncDaos", action = "SyncDaos")
    @WebResult(name = "daosSyncResponse", targetNamespace = "", partName = "daosSyncResponse")
    public cz.tacr.elza.ws.types.v1.DaosSyncResponse syncDaos(
            @WebParam(partName = "daosSyncRequest", name = "daosSyncRequest", targetNamespace = "")
                    cz.tacr.elza.ws.types.v1.DaosSyncRequest daosSyncRequest
    ) throws DaoServiceException;
}
