package ZP2015;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

//
// Otazky:
// - Jak pridat kopii prvku? Jde o to mit moznost postupne pridavat
//   dostupne specifikace samostatnymi pravidly
// Priklad:
// - addWithAllSpec
// - addWithoutSpec - ?kde je vzit pozdeji?

// Nastaveni vychozi neopakovatelnosti atributu
rule "U atributu je zapotrebi nove explicitne nastavit neopakovatelnost"
salience 100
no-loop
when
    $itemType : RulItemTypeExt(code in ("ZP2015_ARRANGEMENT_TYPE", "ZP2015_LEVEL_TYPE", "ZP2015_FOLDER_TYPE",
        "ZP2015_UNIT_TYPE", "ZP2015_UNIT_COUNT", "ZP2015_UNIT_ID", "ZP2015_SERIAL_NUMBER", "ZP2015_TITLE",
        "ZP2015_FORMAL_TITLE", "ZP2015_UNIT_DATE_PRE", "ZP2015_UNIT_DATE", "ZP2015_UNIT_DATE_POST",
        "ZP2015_UNIT_DATE_TEXT", "ZP2015_UNIT_HIST", "ZP2015_UNIT_ARR", "ZP2015_UNIT_CONTENT",
        "ZP2015_UNIT_SOURCE", "ZP2015_FUTURE_UNITS", "ZP2015_UNIT_ACCESS", "ZP2015_UNIT_INFO_RIGHTS",
        "ZP2015_UNIT_COPY_RIGHTS", "ZP2015_UNIT_CURRENT_STATUS", "ZP2015_COPY_SOURCE",
        "ZP2015_RELATED_UNITS", "ZP2015_EXISTING_COPY", "ZP2015_INTERNAL_NOTE", "ZP2015_NOTE",
        "ZP2015_ARRANGE_RULES", "ZP2015_ITEM_TITLE", "ZP2015_STORAGE_COND", "ZP2015_SIZE", "ZP2015_SCALE",
        "ZP2015_ORIENTATION", "ZP2015_ITEM_MAT", "ZP2015_PART", "ZP2015_EDITION",
        "ZP2015_EXERQUE", "ZP2015_PAINTING_CHAR", "ZP2015_CORROBORATION", "ZP2015_IMPRINT_COUNT",
        "ZP2015_IMPRINT_ORDER", "ZP2015_LEGEND", "ZP2015_MOVIE_LENGTH", "ZP2015_RECORD_LENGTH",
        "ZP2015_COLL_EXTENT_LENGTH", "ZP2015_NAD", "ZP2015_DESCRIPTION_DATE"))
then
    $itemType.setRepeatable(false);
end

rule "Atribut ZP2015_LEVEL_TYPE je povinný vždy"
salience 100
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Atribut ZP2015_LEVEL_TYPE, ZP2015_LEVEL_ROOT"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent==null )
    $itemSpec : RulItemSpecExt(code == "ZP2015_LEVEL_ROOT") from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Dílčí list je možný pokud je rodič kořen
rule "Dílčí list pod kořenem"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_ROOT" ) from $parentDescItems
    $itemSpec : RulItemSpecExt(code == "ZP2015_LEVEL_SECTION") from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Serie - možná pokud je rodič root nebo dílčí list
rule "Serie - možná pokud je rodič root nebo dílčí list"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ROOT", "ZP2015_LEVEL_SECTION") ) from $parentDescItems
    $itemSpec : RulItemSpecExt(code == "ZP2015_LEVEL_SERIES") from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Pokud je rodic série, tak může být série, složka nebo jednotlivost
rule "Atribut ZP2015_LEVEL_TYPE, ZP2015_LEVEL_SERIES"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_SERIES" ) from $parentDescItems
    $itemSpec : RulItemSpecExt(code == "ZP2015_LEVEL_SERIES" || code == "ZP2015_LEVEL_FOLDER" || code == "ZP2015_LEVEL_ITEM") from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Pokud je rodič složka, tak může být složka nebo jednotlivost pokud sourozenec neexistuje
rule "Atribut ZP2015_LEVEL_TYPE u rodice je ZP2015_LEVEL_FOLDER, nema sourozence"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems && siblingBefore==null && siblingAfter==null)
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $parentDescItems
    $itemSpec : RulItemSpecExt(code == "ZP2015_LEVEL_FOLDER" || code == "ZP2015_LEVEL_ITEM") from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Pokud je rodič složka a má sourozence pred, tak je stejného typu jako oni
rule "Atribut ZP2015_LEVEL_TYPE u rodice je ZP2015_LEVEL_FOLDER, ma sourozence pred"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems && siblingBefore!=null && $siblingDescItems: siblingBefore.descItems)
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $parentDescItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && $specCode: specCode) from $siblingDescItems
    $itemSpec : RulItemSpecExt(code == $specCode) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Pokud je rodič složka a má sourozence za, tak je stejného typu jako oni
rule "Atribut ZP2015_LEVEL_TYPE u rodice je ZP2015_LEVEL_FOLDER, ma sourozence za"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems && siblingAfter!=null && $siblingDescItems: siblingAfter.descItems)
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $parentDescItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && $specCode: specCode) from $siblingDescItems
    $itemSpec : RulItemSpecExt(code == $specCode) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Pokud je rodič jednotlivost, tak je část
rule "Atribut ZP2015_LEVEL_TYPE u rodice je ZP2015_LEVEL_ITEM"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && (specCode=="ZP2015_LEVEL_ITEM"||specCode=="ZP2015_LEVEL_PART") ) from $parentDescItems
    $itemSpec : RulItemSpecExt(code == "ZP2015_LEVEL_PART" ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Číslo NAD na kořeni a dílčím listu
rule "NAD na kořeni a dílčím listu"
no-loop
when
    $activeLevel : ActiveLevel( )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ROOT", "ZP2015_LEVEL_SECTION") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_NAD")
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

// Složka musí mít uveden typ
rule "Složka musí mít uveden typ"
salience 100
no-loop
when
    $activeLevel : ActiveLevel( parent!=null  )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_FOLDER_TYPE")
    $itemSpec : RulItemSpecExt(code == "ZP2015_FOLDER_LOGICAL" ) from $itemType.rulItemSpecList
then
    $itemType.setType(RulItemType.Type.REQUIRED);
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Pokud je nadřazená složka s uvedenim EJ nebo hromadina, potom musí být logická
rule "Musí být logická složka, pokud nadřazená složka je s uvedenim EJ nebo hromadina"
no-loop
when
    $activeLevel : ActiveLevel( parent!=null  )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $activeLevel.descItems
    $level : Level( this!=$activeLevel )
    DescItem(type=="ZP2015_FOLDER_TYPE" && (specCode in ("ZP2015_FOLDER_SINGLE_TYPE", "ZP2015_FOLDER_UNITS") ) ) from $level.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_FOLDER_TYPE")
    $itemSpec : RulItemSpecExt(code == "ZP2015_FOLDER_LOGICAL" ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Pokud je nadřazená složka bez uvedeni EJ nebo hromadina, potom muze byt hromadina nebo s uvedenim EJ
rule "Může být hromadina nebo s uvedením EJ, pokud nemá nadřazenou složku nebo jen logické"
no-loop
when
    $activeLevel : ActiveLevel( )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $activeLevel.descItems
    // neexistje nadrizeny level typu slozka
    not ( $level : Level( this!=$activeLevel ) and
         DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $level.descItems and
         DescItem(type=="ZP2015_FOLDER_TYPE" && specCode!="ZP2015_FOLDER_LOGICAL" ) from $level.descItems )
    $itemType : RulItemTypeExt(code == "ZP2015_FOLDER_TYPE")
    $itemSpec : RulItemSpecExt(code != "ZP2015_FOLDER_LOGICAL" ) from $itemType.rulItemSpecList
    // v katalogu nelze zadat slozku s vice stejnymi EJ
    // TODO: prepsat podminku pozitivne
    not (
        DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode=="ZP2015_ARRANGEMENT_KAT") from $activeLevel.descItems and
        RulItemSpecExt($itemSpec==this && code == "ZP2015_FOLDER_SINGLE_TYPE" ) from $itemType.rulItemSpecList
        )
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Typ pořádání - lze nastavit do úrovně složka
rule "Typ pořádání"
no-loop
when
  $activeLevel : ActiveLevel( )
  DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ROOT", "ZP2015_LEVEL_SECTION", "ZP2015_LEVEL_SERIES", "ZP2015_LEVEL_FOLDER") ) from $activeLevel.descItems
  $itemType : RulItemTypeExt(code == "ZP2015_ARRANGEMENT_TYPE")
  $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
  $itemType.setType(RulItemType.Type.POSSIBLE);
  $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Složka manipulačního seznamu
rule "Složka manipulačního seznamu"
no-loop
when
    // nesmi jiz mit deti
    $activeLevel : ActiveLevel( !hasChildren )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode=="ZP2015_ARRANGEMENT_MAN") from $activeLevel.descItems
    DescItem(type=="ZP2015_FOLDER_TYPE" && specCode=="ZP2015_FOLDER_UNITS" ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_EXTRA_UNITS")
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Pořadové číslo povinné pokud je určen způsob pořádání
// zde je označeno, jen jako možné - je generováno akcí
rule "Pořadové číslo - možné"
no-loop
when
    $activeLevel : ActiveLevel( )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_MAN", "ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_SERIAL_NUMBER")
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setPolicyTypeCode("SERIAL_NO");
end

// referenční označení možné pro ostatní typy pro nejvyšší uzly
// neni mozne pro koren
rule "Referenční označení - možné pro série vždy"
no-loop
when
    $activeLevel: ActiveLevel( parent!=null && $items: descItems)
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ROOT" , "ZP2015_LEVEL_SECTION", "ZP2015_LEVEL_SERIES") ) from $items
    not DescItem(type=="ZP2015_SERIAL_NUMBER") from $items
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_ID")
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setPolicyTypeCode("REF_NO");
end

// referenční označení v INV|KAT - povinné pro uzly mimo kořen
// neni mozne pro koren
rule "Referenční označení - povinné"
no-loop
when
    $activeLevel: ActiveLevel( parent!=null )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_ID")
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setPolicyTypeCode("REF_NO");
end

// Složka/Jednotlivost - lze zadat vždy ukládací jednotku
rule "Ukládací jednotka na složce - volitelně"
no-loop
when
    $activeLevel: ActiveLevel( )
    DescItem(type=="ZP2015_LEVEL_TYPE" && (specCode=="ZP2015_LEVEL_FOLDER"||specCode=="ZP2015_LEVEL_ITEM") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_STORAGE_ID")
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Pravidlo se vyhodnocuje později - po nastavení volitelnosti
rule "Ukládací jednotka na složce - povině"
salience -100
no-loop
when
    $activeLevel: ActiveLevel( )
    DescItem(type=="ZP2015_FOLDER_TYPE" && (specCode=="ZP2015_FOLDER_UNITS"||specCode=="ZP2015_FOLDER_SINGLE_TYPE") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_STORAGE_ID")
then
    $itemType.setType(RulItemType.Type.REQUIRED);
    $itemType.setPolicyTypeCode("STORAGE_ID");
end

// Druh archiválie povinně - u složky s jednotlivostmi
rule "Druh archiválie - povinně u složky"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_FOLDER_TYPE" && specCode=="ZP2015_FOLDER_SINGLE_TYPE" ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE" || code == "ZP2015_UNIT_COUNT")
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// Druh archiválie povinně - u jednotlivosti
rule "Druh archiválie - povinně u jednotlivosti"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_ITEM" ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE")
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// U jednotlivosti lze zvolit libovolny typ jednotlivosti
// (plati i pro slozku s jednotlivostmi)
rule "Druh archiválie - lze vybrat libovolný typ"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE")
    $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// U logické složky man. seznamu lze vybrat libovolny typ jendotlivosti
rule "Druh archiválie - slozka jina nez INV a KAT"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode not in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE")
    $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// 3.4.2 Inventar
// U logické složky inventare nesmi byt uvedene typy
rule "Druh archiválie - slozka v INV"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode == "ZP2015_ARRANGEMENT_INV" ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE")
    $itemSpec : RulItemSpecExt(code not in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP", "ZP2015_UNIT_TYPE_UKN",
       "ZP2015_UNIT_TYPE_PPR", "ZP2015_UNIT_TYPE_IND", "ZP2015_UNIT_TYP_ELE", "ZP2015_UNIT_TYPE_REP", "ZP2015_UNIT_TYPE_KTT",
       "ZP2015_UNIT_TYPE_PEC", "ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL", "ZP2015_UNIT_TYPE_FAL",
       "ZP2015_UNIT_TYPE_TIO") ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Poznamka 3.4.3 Katalog - nelze evidovat jednotlivosti u slozky

// Obsah/Regest
rule "Obsah/regest - doporučený pro složku a níže"
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code in ( "ZP2015_TITLE" ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Obsah/regest - povinný pro sérii"
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_SERIES") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code in ( "ZP2015_TITLE" ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// Vždy možné prvky popisu
rule "Univerzální prvky popisu - možné"
no-loop
when
    $itemType : RulItemTypeExt(code in
    ( "ZP2015_OTHER_ID",
      // 4.3.1 Odkaz na původce 
      "ZP2015_ORIGINATOR", 
      // 4.3.2 Dějiny jednotky popisu
      "ZP2015_UNIT_HIST", 
      // 4.3.3 Způsob uspořádání jednotky popisu
      "ZP2015_UNIT_ARR",
      // 4.3.4 Tematický popis jednotky popisu
      "ZP2015_UNIT_CONTENT",
      // 4.3.5 Přímý zdroj akvizice
      "ZP2015_UNIT_SOURCE", 
      // ZP4.3.6 Budoucí přírůstky 
      "ZP2015_FUTURE_UNITS",
      // 4.4.1 Podmínky přístupu, práva k jednotce popisu a její reprodukci
      "ZP2015_UNIT_ACCESS",
      // 4.4.2 Možnost zveřejnění informací o jednotce popisu
      "ZP2015_UNIT_INFO_RIGHTS", 
      // 4.4.3 Možnost zveřejnění reprodukce jednotky popisu
      "ZP2015_UNIT_COPY_RIGHTS",
      // 4.4.4 Fyzický stav jednotky popisu a technické požadavky
      "ZP2015_UNIT_CURRENT_STATUS",
      // ZP 4.5.1 Identifikace předlohy kopie
      "ZP2015_COPY_SOURCE",
      // ZP 4.5.2
      "ZP2015_RELATED_UNITS",
      // ZP 4.5.3
      "ZP2015_EXISTING_COPY",
      // Poznámky - ZP 4.6.1, 4.6.2
      "ZP2015_INTERNAL_NOTE", "ZP2015_NOTE",
      // 4.7.1 Zpracovatel jednotky popisu
      "ZP2015_ARRANGER",
      // 4.7.2 Pravidla zpracování jednotky popisu
      "ZP2015_ARRANGE_RULES",
      // ZP4.7.3 Datum (data) popisu 
      "ZP2015_DESCRIPTION_DATE",
      // ZP 5.2.10 Jazyk
      "ZP2015_LANGUAGE",
      // ZP 5.2.11 Edice a literatura
      "ZP2015_EDITION",
      // Obecná příloha 
      "ZP2015_ATTACHMENT" ) )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Prvky možné od úrovně složky níže
rule "Univerzální prvky popisu - možné od složky níže"
no-loop
when
    $activeLevel: ActiveLevel( )
    $itemType : RulItemTypeExt(code in
    ( "ZP2015_FORMAL_TITLE" ) )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $activeLevel.descItems
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Povolení všech jiných označení
rule "Povolení všech jiných označení (ZP2015_OTHER_ID)"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_OTHER_ID")
    $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Povolení všech jazyků
rule "Povolení všech jazyků (ZP2015_LANGUAGE)"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LANGUAGE")
    $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Datace - strojová a jiná datace
rule "Datace - možná na složce a níže"
no-loop
when
    $activeLevel: ActiveLevel( )
    $itemType : RulItemTypeExt(code in
    ( "ZP2015_UNIT_DATE_PRE", "ZP2015_UNIT_DATE", "ZP2015_UNIT_DATE_POST", "ZP2015_DATE_OTHER" ) )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $activeLevel.descItems
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Datace - textová
// Dotaz: v jakých úrovních?
rule "Datace - textová"
no-loop
when
    $activeLevel: ActiveLevel( )
    //not DescItem(type=="ZP2015_UNIT_DATE_TEXT" ) from $activeLevel.descItems
    //not DescItem(type in ( "ZP2015_UNIT_DATE_PRE", "ZP2015_UNIT_DATE", "ZP2015_UNIT_DATE_POST" ) ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code=="ZP2015_UNIT_DATE_TEXT")
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $activeLevel.descItems
then
       $itemType.setType(RulItemType.Type.POSSIBLE);
end


// Standarní datace je doporučená pro poslední složku a část jednotlivosti (bez potomků)
rule "Datace - strojová - doporučení"
salience -100
no-loop
when
    $activeLevel: ActiveLevel( !hasChildren )
    $itemType : RulItemTypeExt(code in ( "ZP2015_UNIT_DATE" ) )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM") ) from $activeLevel.descItems
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

// Povolení všech specifikací jiné datace označení
rule "Povolení všech jiných datací (ZP2015_DATE_OTHER)"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_DATE_OTHER")
    $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Doporuceni na textovou dataci
/*
rule "Druh arhivalie"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode=="ZP2015_UNIT_TYPE_LIO" ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code=="ZP2015_UNIT_DATE_TEXT")
then
       $itemType.setType(RulItemType.Type.REQUIRED);
end
*/

// Doporučení pro kořen dle MAN,INV, KAT - vyhodnoceno později
// 4.3.5 Přímý zdroj akvizice
// 4.4.4 Fyzický stav jednotky popisu a technické požadavky
// 4.7.1 Zpracovatel
// 4.7.2 Pravidla zpracování jednotky popisu
rule "Doporučení pro kořen pro MAN, INV, KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( parent == null )
    $descItem : DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode not in ("ZP2015_ARRANGEMENT_OTHER") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_UNIT_SOURCE", "ZP2015_UNIT_CURRENT_STATUS",
        "ZP2015_ARRANGER", "ZP2015_ARRANGE_RULES", "ZP2015_LANGUAGE") )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

// Doporučení pro kořen inventáře a katalogu - vyhodnoceno později
// ZP4.3.2 Dějiny jednotky popisu
// ZP4.3.3 Způsob uspořádání jednotky popisu
// ZP4.3.6 Budoucí přírůstky
rule "Doporučení pro kořen inventáře a katalogu"
no-loop
salience -100
when $activeLevel: ActiveLevel( parent == null )
    $descItem : DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ("ZP2015_UNIT_HIST", "ZP2015_UNIT_ARR", "ZP2015_FUTURE_UNITS") )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

//----------------------------------------------
// Listiny
//----------------------------------------------

// Doporučení pro listiny (vždy)
rule "Doporučení pro listiny (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ("ZP2015_STORAGE_COND", "ZP2015_SIZE", "ZP2015_ITEM_MAT", "ZP2015_LANGUAGE", "ZP2015_IMPRINT_COUNT",
        "ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

// Možné role entit pro listiny (vždy)
rule "Možné role entit pro listiny (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
    $itemSpec: RulItemSpecExt( code in (
        "ZP2015_ENTITY_ROLE_15", "ZP2015_ENTITY_ROLE_17", "ZP2015_ENTITY_ROLE_21",
        // žadatelé
        "ZP2015_ENTITY_ROLE_22",
        // mista vydani
        "ZP2015_ENTITY_ROLE_58"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Povinnost pro listiny v inv
rule "Povinnost pro listiny v inv"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $activeLevel.descItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ("ZP2015_STORAGE_COND", "ZP2015_SIZE", "ZP2015_ITEM_MAT", "ZP2015_LANGUAGE", "ZP2015_IMPRINT_COUNT",
        // nastaveni vztahu
        "ZP2015_ENTITY_ROLE"
    ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// Povinne role pro listiny v inv
rule "Povinne role pro listiny v inv"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $activeLevel.descItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( "ZP2015_ENTITY_ROLE_17", "ZP2015_ENTITY_ROLE_21" ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// UKN, KTT, reg.pom.
//----------------------------------------------

// Možné prvky pro UKN, KTT, reg.pom. (vždy)
rule "Možné prvky pro UKN, KTT, reg.pom. (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PPR", "ZP2015_UNIT_TYPE_IND",
        "ZP2015_UNIT_TYP_ELE", "ZP2015_UNIT_TYPE_REP",
        "ZP2015_UNIT_TYPE_UKN", "ZP2015_UNIT_TYPE_KTT") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Povinné prvky pro UKN, KTT, reg.pom. (KAT)
rule "Povinné prvky pro UKN, KTT, reg.pom. (KAT)"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PPR", "ZP2015_UNIT_TYPE_IND",
        "ZP2015_UNIT_TYP_ELE", "ZP2015_UNIT_TYPE_REP",
        "ZP2015_UNIT_TYPE_UKN", "ZP2015_UNIT_TYPE_KTT") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// Možné role entit pro UKN, KTT, reg.pom. (vždy)
rule "Možné role entit pro UKN, KTT, reg.pom. (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PPR", "ZP2015_UNIT_TYPE_IND",
        "ZP2015_UNIT_TYP_ELE", "ZP2015_UNIT_TYPE_REP",
        "ZP2015_UNIT_TYPE_UKN", "ZP2015_UNIT_TYPE_KTT") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",
        // autoři výtvarné stránky
        "ZP2015_ENTITY_ROLE_14",
        // písaři
        "ZP2015_ENTITY_ROLE_48",
        // výrobci
        "ZP2015_ENTITY_ROLE_53",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        "ZP2015_ENTITY_ROLE_62", "ZP2015_ENTITY_ROLE_65"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Povinné role entit pro UKN, KTT, reg.pom. v katalogu
rule "Povinne role pro UKN, KTT, reg.pom. v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PPR", "ZP2015_UNIT_TYPE_IND",
        "ZP2015_UNIT_TYP_ELE", "ZP2015_UNIT_TYPE_REP",
        "ZP2015_UNIT_TYPE_UKN", "ZP2015_UNIT_TYPE_KTT") ) from $activeLevel.descItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // písaři
        "ZP2015_ENTITY_ROLE_48",
        // výrobci
        "ZP2015_ENTITY_ROLE_53",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Fotograficke archivalie
//----------------------------------------------

// Možné prvky pro fotograficky material (vždy)
rule "Možné prvky pro fotograficky material (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ("ZP2015_ITEM_MAT", "ZP2015_ORIENTATION",
        "ZP2015_POSITION", "ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Povinnost prvku pro fotograficky material v inv a kat
rule "Povinnost prvku pro fotograficky material v inv kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $activeLevel.descItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ("ZP2015_ITEM_MAT", "ZP2015_ENTITY_ROLE"	) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end


// Možné role entit pro fotograficky material (vždy)
rule "Možné role entit pro fotograficky material (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři fotografií
        "ZP2015_ENTITY_ROLE_4",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",
        // odesílatelé
        "ZP2015_ENTITY_ROLE_24",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // ostatní entity zachycené jednotkami popisu
        "ZP2015_ENTITY_ROLE_65"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Povinné role entit pro fotograficky material v INV
rule "Povinné role entit pro fotograficky material v INV"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $activeLevel.descItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři fotografií
        "ZP2015_ENTITY_ROLE_4",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Povinné role entit pro fotograficky material v KAT
rule "Povinné role entit pro fotograficky material v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $activeLevel.descItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři fotografií
        "ZP2015_ENTITY_ROLE_4",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",
        // odesílatelé
        "ZP2015_ENTITY_ROLE_24",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end


//----------------------------------------------
// Mapy
//----------------------------------------------

// Možné prvky pro mapy (vždy)
rule "Možné prvky pro mapy (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ("ZP2015_SCALE", "ZP2015_POSITION",
        "ZP2015_ORIENTATION", "ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Povinnost prvku pro mapy v inv a kat
rule "Povinnost prvku pro mapy v inv kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $activeLevel.descItems
    // Rodic je INV nebo KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ("ZP2015_SCALE", "ZP2015_POSITION", "ZP2015_ENTITY_ROLE"	) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// Možné role entit pro mapy (vždy)
rule "Možné role entit pro mapy (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé/nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // objednatelé/příjemci
        "ZP2015_ENTITY_ROLE_19",
        // kartografové
        "ZP2015_ENTITY_ROLE_33",
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",
        // autoři výtvarné stránky
        "ZP2015_ENTITY_ROLE_14",
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // redaktoři
        "ZP2015_ENTITY_ROLE_32",
        // editoři
        "ZP2015_ENTITY_ROLE_34",
        // kresliči
        "ZP2015_ENTITY_ROLE_36",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62",
        // ostatní entity zachycené jednotkami popisu
        "ZP2015_ENTITY_ROLE_65"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Povinné role entit pro mapy v INV
rule "Povinné role entit pro mapy v INV"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $activeLevel.descItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé/nakladatelé
        "ZP2015_ENTITY_ROLE_16"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Povinné role entit pro mapy v KAT
rule "Povinné role entit pro mapy v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $activeLevel.descItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé/nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // objednatelé/příjemci
        "ZP2015_ENTITY_ROLE_19",
        // kartografové
        "ZP2015_ENTITY_ROLE_33",
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",
        // autoři výtvarné stránky
        "ZP2015_ENTITY_ROLE_14",
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // redaktoři
        "ZP2015_ENTITY_ROLE_32",
        // editoři
        "ZP2015_ENTITY_ROLE_34",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Technické výkresy
//----------------------------------------------

// Možné prvky pro technické výkresy (vždy)
rule "Možné prvky pro technické výkresy (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $activeLevel.descItems
	$itemType: RulItemTypeExt( code in ("ZP2015_SCALE", "ZP2015_POSITION", 
		"ZP2015_ORIENTATION", "ZP2015_ENTITY_ROLE") )
then
	$itemType.setType(RulItemType.Type.POSSIBLE);
end

// Povinnost prvku pro technické výkresy v inv a kat
rule "Povinnost prvku pro technické výkresy v inv kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $activeLevel.descItems
	// Rodic je INV nebo KAT 
	$level: Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ("ZP2015_SCALE", "ZP2015_ENTITY_ROLE"	) )
then
	$itemType.setType(RulItemType.Type.REQUIRED);
end

// Možné role entit pro technické výkresy (vždy)
rule "Možné role entit pro technické výkresy (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $activeLevel.descItems
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in (
		// objednatelé/příjemci 
		"ZP2015_ENTITY_ROLE_19",
		// autoři
		"ZP2015_ENTITY_ROLE_1",
		// schvalovatelé
		"ZP2015_ENTITY_ROLE_25",
		// stavitelé
		"ZP2015_ENTITY_ROLE_26",
		// výrobci
		"ZP2015_ENTITY_ROLE_53",
		// kresliči
		"ZP2015_ENTITY_ROLE_36",
		// místa vzniku jednotek popisu
		"ZP2015_ENTITY_ROLE_61",
		// místa vzniku předloh popisovaných kopií
		"ZP2015_ENTITY_ROLE_62",
		// typová označení a názvy výrobků a typových staveb
		"ZP2015_ENTITY_ROLE_63",
		// ostatní entity zachycené jednotkami popisu
		"ZP2015_ENTITY_ROLE_65"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Povinné role entit pro technické výkresy v INV
rule "Povinné role entit pro technické výkresy v INV"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $activeLevel.descItems
	// Rodic je INV 
	$level: Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// objednatelé/příjemci 
		"ZP2015_ENTITY_ROLE_19"
		// typová označení zatím nejsou správně uvedena jako povinná
		// - neměl by vzniknout příznak určující typovost?
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Povinné role entit pro technické výkresy v KAT
rule "Povinné role entit pro technické výkresy v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $activeLevel.descItems
	// Rodic je KAT 
	$level: Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// objednatelé/příjemci 
		"ZP2015_ENTITY_ROLE_19",
		// schvalovatelé
		"ZP2015_ENTITY_ROLE_25",
		// stavitelé
		"ZP2015_ENTITY_ROLE_26",
		// výrobci
		"ZP2015_ENTITY_ROLE_53",
		// místa vzniku jednotek popisu
		"ZP2015_ENTITY_ROLE_61",
		// ostatní entity zachycené jednotkami popisu
		"ZP2015_ENTITY_ROLE_65"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Tisky
//----------------------------------------------

// Možné prvky pro tisky (vždy)
rule "Možné prvky pro tisky (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $activeLevel.descItems
	$itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
	$itemType.setType(RulItemType.Type.POSSIBLE);
end

// Povinnost prvku pro tisky v inv a kat
rule "Povinnost prvku pro tisky v inv kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $activeLevel.descItems
	// Rodic je INV nebo KAT 
	$level: Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
	$itemType.setType(RulItemType.Type.REQUIRED);
end

// Možné role entit pro tisky (vždy)
rule "Možné role entit pro tisky (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $activeLevel.descItems
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in (
		// vydavatelé/nakladatelé 
		"ZP2015_ENTITY_ROLE_16",
		// příjemci 
		"ZP2015_ENTITY_ROLE_21",		
		// autoři
		"ZP2015_ENTITY_ROLE_1",
		// autoři výtvarné stránky
		"ZP2015_ENTITY_ROLE_14",
		// fotografové
		"ZP2015_ENTITY_ROLE_31",
		// kartografové
		"ZP2015_ENTITY_ROLE_33",
		// editoři / redaktoři
		"ZP2015_ENTITY_ROLE_35",
		// překladatelé
		"ZP2015_ENTITY_ROLE_44",
		// lektoři
		"ZP2015_ENTITY_ROLE_45",
		// výrobci nosičů záznamů
		"ZP2015_ENTITY_ROLE_50",
		// tiskárny/tiskaři
		"ZP2015_ENTITY_ROLE_52",
		// místa vydání
		"ZP2015_ENTITY_ROLE_58",
		// místa vzniku předloh popisovaných kopií
		"ZP2015_ENTITY_ROLE_62",
		// ostatní entity zachycené jednotkami popisu
		"ZP2015_ENTITY_ROLE_65"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Povinné role entit pro tisky v INV
rule "Povinné role entit pro tisky v INV"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $activeLevel.descItems
	// Rodic je INV 
	$level: Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// vydavatelé/nakladatelé 
		"ZP2015_ENTITY_ROLE_16",
		// autoři
		"ZP2015_ENTITY_ROLE_1",
		// místa vydání
		"ZP2015_ENTITY_ROLE_58"
		// místa vzniku kopií
		// - neměl by vzniknout příznak určující kopii?
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Povinné role entit pro tisky v KAT
rule "Povinné role entit pro tisky v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $activeLevel.descItems
	// Rodic je KAT 
	$level: Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// vydavatelé/nakladatelé 
		"ZP2015_ENTITY_ROLE_16",
		// příjemci 
		"ZP2015_ENTITY_ROLE_21",		
		// autoři
		"ZP2015_ENTITY_ROLE_1",
		// autoři výtvarné stránky
		"ZP2015_ENTITY_ROLE_14",
		// fotografové
		"ZP2015_ENTITY_ROLE_31",
		// kartografové
		"ZP2015_ENTITY_ROLE_33",
		// editoři / redaktoři
		"ZP2015_ENTITY_ROLE_35",
		// překladatelé
		"ZP2015_ENTITY_ROLE_44",
		// lektoři
		"ZP2015_ENTITY_ROLE_45",
		// výrobci nosičů záznamů
		"ZP2015_ENTITY_ROLE_50",
		// tiskárny/tiskaři
		"ZP2015_ENTITY_ROLE_52",
		// místa vydání
		"ZP2015_ENTITY_ROLE_58"
		// místa vzniku předloh popisovaných kopií
		//"ZP2015_ENTITY_ROLE_62",
		// ostatní entity zachycené jednotkami popisu
		//"ZP2015_ENTITY_ROLE_65"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.REQUIRED);
end


//----------------------------------------------
// Cenné papíry
//----------------------------------------------

// Možné prvky pro cenné papíry (vždy)
rule "Možné prvky pro cenné papíry (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $activeLevel.descItems
	$itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
	$itemType.setType(RulItemType.Type.POSSIBLE);
end

// Povinnost prvku pro cenné papíry v inv a kat
rule "Povinnost prvku pro cenné papíry v inv kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $activeLevel.descItems
	// Rodic je INV nebo KAT 
	$level: Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
	$itemType.setType(RulItemType.Type.REQUIRED);
end

// Možné role entit pro cenné papíry (vždy)
rule "Možné role entit pro cenné papíry (vždy)"
no-loop
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $activeLevel.descItems
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in (
		// vydavatelé 
		"ZP2015_ENTITY_ROLE_15",
		// držitelé
		"ZP2015_ENTITY_ROLE_23",		
		// autoři výtvarné stránky
		"ZP2015_ENTITY_ROLE_14",
		// tiskárny
		"ZP2015_ENTITY_ROLE_51",
		// místa vydání
		"ZP2015_ENTITY_ROLE_58",
		// místa vzniku předloh popisovaných kopií
		"ZP2015_ENTITY_ROLE_62",
		// ostatní entity zachycené jednotkami popisu
		"ZP2015_ENTITY_ROLE_65"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Povinné role entit pro cenné papíry v INV
rule "Povinné role entit pro cenné papíry v INV"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $activeLevel.descItems
	// Rodic je INV 
	$level: Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// vydavatelé 
		"ZP2015_ENTITY_ROLE_15"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Povinné role entit pro cenné papíry v KAT
rule "Povinné role entit pro cenné papíry v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
	$descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $activeLevel.descItems
	// Rodic je KAT 
	$level: Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// vydavatelé 
		"ZP2015_ENTITY_ROLE_15",
		// držitelé
		"ZP2015_ENTITY_ROLE_23",		
		// autoři výtvarné stránky
		"ZP2015_ENTITY_ROLE_14",
		// tiskárny
		"ZP2015_ENTITY_ROLE_51",
		// místa vydání
		"ZP2015_ENTITY_ROLE_58"
		// místa vzniku předloh popisovaných kopií
		//"ZP2015_ENTITY_ROLE_62",
		// ostatní entity zachycené jednotkami popisu
		//"ZP2015_ENTITY_ROLE_65"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.REQUIRED);
end
