package ZP2015;

import cz.tacr.elza.api.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.api.RulItemType;

rule "Všechny jsou možný a neopakovatelný"
when
	$itemType : RulItemTypeExt()
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setRepeatable(false);
end
