package ZP2015;

import cz.tacr.elza.api.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.api.RulItemType;

rule "Jen vybrané jsou možné"
no-loop 
when
	$itemType : RulItemTypeExt( code in ( 
	"ZP2015_RELATED_UNITS", "ZP2015_UNIT_HIST", "ZP2015_FUTURE_UNITS", "ZP2015_UNIT_ARR") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setRepeatable(false);
end

// Povinné prvky popisu
rule "Vybrané jsou povinné"
no-loop 
when
	$itemType : RulItemTypeExt( code in ("ZP2015_UNIT_CURRENT_STATUS", "ZP2015_UNIT_SOURCE", 
		"ZP2015_ARRANGER", "ZP2015_ARRANGE_RULES", "ZP2015_SIGNATURE_DATE",
		"ZP2015_DATE_RANGE", "ZP2015_UNIT_COUNT_TABLE", "ZP2015_UNIT_COUNT_SUM", "ZP2015_UNITS_AMOUNT", 
		"ZP2015_FINDING_AID_DATE", "ZP2015_ARRANGER_TEXT", "ZP2015_FINDING_AID_EDITOR",
		"ZP2015_FINDING_AID_APPROVED_BY" ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
    $itemType.setRepeatable(false);
end
