package drlglobal;
import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec
import cz.tacr.elza.drools.model.RequiredType;
import cz.tacr.elza.drools.model.item.Item;
import cz.tacr.elza.drools.model.Ap;
import cz.tacr.elza.drools.model.Part;
import cz.tacr.elza.drools.model.PartType;

rule "R_EXT_003 Použití typu zániku"
when $i: Item(spec == "EXC_EXTINCTION", type == "EXT_CLASS")
     $it: ItemType(code in ("EXT_TYPE"))
     $is : ItemSpec(code in ("EXT_STOPPUBLISHING")) from $it.specs
then
    $it.setPossible();
    $is.setPossible();
end