package cz.tacr.elza.ws.core.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2019-06-21T09:42:06.763+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://elza.tacr.cz/ws/core/v1", name = "DaoRequestsService")
@XmlSeeAlso({cz.tacr.elza.ws.types.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DaoRequestsService {

    @WebMethod(operationName = "DestructionRequestRevoked", action = "DestructionRequestRevoked")
    public void destructionRequestRevoked(
            @WebParam(partName = "requestRevoked", name = "requestRevoked", targetNamespace = "")
                    cz.tacr.elza.ws.types.v1.RequestRevoked requestRevoked
    ) throws CoreServiceException;

    @WebMethod(operationName = "TransferRequestFinished", action = "TransferRequestFinished")
    public void transferRequestFinished(
            @WebParam(partName = "requestIdentifier", name = "requestIdentifier", targetNamespace = "")
                    String requestIdentifier
    ) throws CoreServiceException;

    @WebMethod(operationName = "TransferRequestRevoked", action = "TransferRequestRevoked")
    public void transferRequestRevoked(
            @WebParam(partName = "requestRevoked", name = "requestRevoked", targetNamespace = "")
                    cz.tacr.elza.ws.types.v1.RequestRevoked requestRevoked
    ) throws CoreServiceException;

    @WebMethod(operationName = "DestructionRequestFinished", action = "DestructionRequestFinished")
    public void destructionRequestFinished(
            @WebParam(partName = "requestIdentifier", name = "requestIdentifier", targetNamespace = "")
                    String requestIdentifier
    ) throws CoreServiceException;
}
