package cz.tacr.elza.ws.core.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2019-06-21T09:42:06.716+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://elza.tacr.cz/ws/core/v1", name = "DaoService")
@XmlSeeAlso({cz.tacr.elza.ws.types.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DaoService {

    /**
     * Import one or more packages. Import will also create corresponding links to described material.
     */
    @WebMethod(operationName = "Import", action = "Import")
    public void _import(
            @WebParam(partName = "daoImport", name = "daoImport", targetNamespace = "")
                    cz.tacr.elza.ws.types.v1.DaoImport daoImport
    ) throws CoreServiceException;

    @WebMethod(operationName = "AddPackage", action = "AddPackage")
    @WebResult(name = "PackageIdentifier", targetNamespace = "", partName = "PackageIdentifier")
    public String addPackage(
            @WebParam(partName = "daoPackage", name = "daoPackage", targetNamespace = "")
                    cz.tacr.elza.ws.types.v1.DaoPackage daoPackage
    ) throws CoreServiceException;

    /**
     * Remove package by internal ID
     */
    @WebMethod(operationName = "RemovePackage", action = "RemovePackage")
    public void removePackage(
            @WebParam(partName = "PackageIdentifier", name = "PackageIdentifier", targetNamespace = "")
                    String packageIdentifier
    ) throws CoreServiceException;

    /**
     * Return current description of given did.
     * Function will throw error if didIdentifier is not valid.
     */
    @WebMethod(operationName = "GetDid", action = "GetDid")
    @WebResult(name = "did", targetNamespace = "", partName = "did")
    public cz.tacr.elza.ws.types.v1.Did getDid(
            @WebParam(partName = "PackageIdentifier", name = "PackageIdentifier", targetNamespace = "")
                    String packageIdentifier
    ) throws CoreServiceException;

    @WebMethod(operationName = "Link", action = "Link")
    public void link(
            @WebParam(partName = "daoLink", name = "daoLink", targetNamespace = "")
                    cz.tacr.elza.ws.types.v1.DaoLink daoLink
    ) throws CoreServiceException;

    /**
     * Remove digital archival object from system. Throw exception if digital archival object does not exists in the system.
     */
    @WebMethod(operationName = "RemoveDao", action = "RemoveDao")
    public void removeDao(
            @WebParam(partName = "PackageIdentifier", name = "PackageIdentifier", targetNamespace = "")
                    String packageIdentifier
    ) throws CoreServiceException;
}
