package cz.tacr.elza.interpi.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-24T16:42:12.460+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "wssoap", 
                  wsdlLocation = "file:/d:/marbes/projekty/elza/elza-core/src/main/resources/wsdl/interpi/interpi.ws.soap.wsdl",
                  targetNamespace = "http://tempuri.org") 
public class Wssoap extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org", "wssoap");
    public final static QName WssoapSoap = new QName("http://tempuri.org", "wssoapSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/d:/marbes/projekty/elza/elza-core/src/main/resources/wsdl/interpi/interpi.ws.soap.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Wssoap.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/d:/marbes/projekty/elza/elza-core/src/main/resources/wsdl/interpi/interpi.ws.soap.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Wssoap(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Wssoap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Wssoap() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Wssoap(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Wssoap(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Wssoap(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WssoapSoap
     */
    @WebEndpoint(name = "wssoapSoap")
    public WssoapSoap getWssoapSoap() {
        return super.getPort(WssoapSoap, WssoapSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WssoapSoap
     */
    @WebEndpoint(name = "wssoapSoap")
    public WssoapSoap getWssoapSoap(WebServiceFeature... features) {
        return super.getPort(WssoapSoap, WssoapSoap.class, features);
    }

}
