package ZP2015;

import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;
import cz.tacr.elza.drools.model.StructObjItem;

import java.util.Arrays;
import java.util.Set;
import cz.tacr.elza.domain.RulItemType;

// Jak psát pravidla:
// vyšší saliance (100) - vyhodnocuje se jako první a obsahu obecné předpoklady, např. neopakovatelnost apod.
// standardní úroveň - vyhodnocuje se obvykle možnost prvku popisu
// nižší saliance (-100) - vyhodnocováno po možnosti prvku popisu, obsahuje informaci o povinnosti

//
// Otazky:
// - Jak pridat kopii prvku? Jde o to mit moznost postupne pridavat
//   dostupne specifikace samostatnymi pravidly
// Priklad:
// - addWithAllSpec
// - addWithoutSpec - ?kde je vzit pozdeji?

rule "Prvky popisu lze nastavit na Nezjištěno"
salience 100
no-loop
when
    $itemType : RulItemTypeExt(code in (
        "ZP2015_SCALE", 
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",
        "ZP2015_ENTITY_ROLE"))
then
    $itemType.setIndefinable(true);
end

rule "Nastaveni vychozi urovne pro chyby u prvku popisu"
salience 100
no-loop
when
  $itemType : RulItemTypeExt()
then
  $itemType.setPolicyTypeCode("ZP2015_POL_BASIC");
end

rule "Nastaveni vychozi urovne pro chyby u specifikaci"
salience 100
no-loop
when
  $itemType : RulItemTypeExt()
  $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
  $itemSpec.setPolicyTypeCode("ZP2015_POL_BASIC");
end

// Nastaveni vychozi neopakovatelnosti atributu
rule "U atributu je zapotrebi nove explicitne nastavit neopakovatelnost"
salience 100
no-loop
when
    $itemType : RulItemTypeExt(code in ("ZP2015_ARRANGEMENT_TYPE", "ZP2015_LEVEL_TYPE", "ZP2015_FOLDER_TYPE",
        "ZP2015_UNIT_TYPE", "ZP2015_UNIT_SUBTYPE", "ZP2015_UNIT_COUNT", "ZP2015_UNIT_ID", 
        "ZP2015_SERIAL_NUMBER", "ZP2015_TITLE", "ZP2015_STORAGE_ID", "ZP2015_AIP_ID", 
        "ZP2015_FORMAL_TITLE", "ZP2015_UNIT_DATE", "ZP2015_UNIT_DATE_BULK",
        "ZP2015_UNIT_DATE_TEXT", "ZP2015_UNIT_HIST", "ZP2015_UNIT_ARR", "ZP2015_UNIT_CONTENT",
        "ZP2015_UNIT_SOURCE", "ZP2015_FUTURE_UNITS", "ZP2015_UNIT_ACCESS", "ZP2015_UNIT_INFO_RIGHTS",
        "ZP2015_UNIT_COPY_RIGHTS", "ZP2015_UNIT_CURRENT_STATUS", "ZP2015_COPY_SOURCE",
        "ZP2015_RELATED_UNITS", "ZP2015_EXISTING_COPY", "ZP2015_INTERNAL_NOTE", "ZP2015_NOTE",
        "ZP2015_ARRANGE_RULES", "ZP2015_STORAGE_COND", "ZP2015_SIZE",
        "ZP2015_SIZE_WIDTH", "ZP2015_SIZE_HEIGHT", "ZP2015_SIZE_DEPTH", "ZP2015_SIZE_UNITS", 
        "ZP2015_SCALE",
        "ZP2015_ORIENTATION", "ZP2015_ITEM_MAT", "ZP2015_PART", "ZP2015_EDITION",
        "ZP2015_EXERQUE", "ZP2015_PAINTING_CHAR", "ZP2015_CORROBORATION", "ZP2015_IMPRINT_COUNT",
        "ZP2015_IMPRINT_ORDER", "ZP2015_LEGEND", "ZP2015_MOVIE_LENGTH", "ZP2015_RECORD_LENGTH",
        "ZP2015_COLL_EXTENT_LENGTH", "ZP2015_DESCRIPTION_DATE","ZP2015_PUBLISHED",
        "ZP2015_WRITING",
        // nastaveni pro ulozeni
        "ZP2015_PACKET_TYPE", "ZP2015_PACKET_FIXED_PREFIX", "ZP2015_PACKET_PREFIX",
        "ZP2015_PACKET_NUMBER", "ZP2015_PACKET_POSTFIX", "ZP2015_ITEM_LINK"
        ))
then
    $itemType.setRepeatable(false);
end

rule "Atribut ZP2015_LEVEL_TYPE je povinný vždy"
salience 100
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Atribut ZP2015_LEVEL_TYPE, ZP2015_LEVEL_ROOT"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent==null )
    $itemSpec : RulItemSpecExt(code == "ZP2015_LEVEL_ROOT") from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Dílčí list je možný pokud je rodič kořen
rule "Dílčí list pod kořenem"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_ROOT" ) from $parentDescItems
    $itemSpec : RulItemSpecExt(code == "ZP2015_LEVEL_SECTION") from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Serie - možná pokud je rodič root nebo dílčí list
rule "Serie - možná pokud je rodič root nebo dílčí list"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ROOT", "ZP2015_LEVEL_SECTION") ) from $parentDescItems
    $itemSpec : RulItemSpecExt(code == "ZP2015_LEVEL_SERIES") from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Rodic serie a nema sourozence - muze byt serie, slozka, jednotlivost
rule "Rodic serie a nema sourozence - muze byt serie, slozka, jednotlivost"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems && siblingBefore==null && siblingAfter==null )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_SERIES" ) from $parentDescItems
    $itemSpec : RulItemSpecExt(code in ("ZP2015_LEVEL_SERIES", "ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Pokud je rodic série a ma sourozence pred typu serie, tak je serie"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems && siblingBefore!=null && $siblingDescItems: siblingBefore.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_SERIES" ) from $parentDescItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_SERIES") from $siblingDescItems
    $itemSpec : RulItemSpecExt(code in ("ZP2015_LEVEL_SERIES")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Pokud je rodic série a ma sourozence za typu serie, tak je serie"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems && siblingAfter!=null && $siblingDescItems: siblingAfter.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_SERIES" ) from $parentDescItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_SERIES") from $siblingDescItems
    $itemSpec : RulItemSpecExt(code in ("ZP2015_LEVEL_SERIES")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Pokud je rodic série a ma sourozence pred typu slozka nebo jednotlivost, tak je slozka nebo jednotlivost"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems && siblingBefore!=null && $siblingDescItems: siblingBefore.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_SERIES" ) from $parentDescItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM")) from $siblingDescItems
    $itemSpec : RulItemSpecExt(code in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Pokud je rodic série a ma sourozence za typu slozka nebo jednotlivost, tak je slozka nebo jednotlivost"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems && siblingAfter!=null && $siblingDescItems: siblingAfter.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_SERIES" ) from $parentDescItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM")) from $siblingDescItems
    $itemSpec : RulItemSpecExt(code in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Pokud je rodic série, ma sourozence za bez typu, tak je serie, slozka nebo jednotlivost"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems && siblingAfter!=null && $siblingDescItems: siblingAfter.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_SERIES" ) from $parentDescItems
    not(DescItem(type=="ZP2015_LEVEL_TYPE" ) from $siblingDescItems )
    $itemSpec : RulItemSpecExt(code in ("ZP2015_LEVEL_SERIES", "ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Pokud je rodic série, ma sourozence pred bez typu, tak je serie, slozka nebo jednotlivost"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems && siblingBefore!=null && $siblingDescItems: siblingBefore.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_SERIES" ) from $parentDescItems
    not(DescItem(type=="ZP2015_LEVEL_TYPE" ) from $siblingDescItems )
    $itemSpec : RulItemSpecExt(code in ("ZP2015_LEVEL_SERIES", "ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Pokud je rodič složka a není složka jednotlivostí, tak může mít podsložku nebo jednotlivost
rule "Atribut ZP2015_LEVEL_TYPE u rodice je ZP2015_LEVEL_FOLDER a není ZP2015_FOLDER_SINGLE_TYPE, tak může mít podsložku"
no-loop
when    
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $parentDescItems   
    // rodic neni slozka jednotlivosti    
    not( DescItem(type=="ZP2015_FOLDER_TYPE" && specCode=="ZP2015_FOLDER_SINGLE_TYPE" ) from $parentDescItems )
    
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM") ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Pokud je rodič složka jednotlivosti, tak může být jen jednotlivost
rule "Atribut ZP2015_LEVEL_TYPE u rodice je ZP2015_LEVEL_FOLDER"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems )
    DescItem(type=="ZP2015_FOLDER_TYPE" && specCode=="ZP2015_FOLDER_SINGLE_TYPE" ) from $parentDescItems
    $itemSpec : RulItemSpecExt(code in ("ZP2015_LEVEL_ITEM") ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Pokud je rodič jednotlivost, tak je část
rule "Atribut ZP2015_LEVEL_TYPE u rodice je ZP2015_LEVEL_ITEM"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LEVEL_TYPE")
    $activeLevel  : ActiveLevel( parent!=null && $parentDescItems: parent.descItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && (specCode=="ZP2015_LEVEL_ITEM"||specCode=="ZP2015_LEVEL_PART") ) from $parentDescItems
    $itemSpec : RulItemSpecExt(code == "ZP2015_LEVEL_PART" ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Složka musí mít uveden typ
rule "Složka musí mít uveden typ"
salience 100
no-loop
when
    $activeLevel : ActiveLevel( parent!=null  )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_FOLDER_TYPE")
    $itemSpec : RulItemSpecExt(code == "ZP2015_FOLDER_LOGICAL" ) from $itemType.rulItemSpecList
then
    $itemType.setType(RulItemType.Type.REQUIRED);
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Pokud je nadřazená složka s uvedenim EJ nebo hromadina, potom musí být logická
rule "Musí být logická složka, pokud nadřazená složka je s uvedenim EJ nebo hromadina"
no-loop
when
    $activeLevel : ActiveLevel( parent!=null  )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $activeLevel.descItems
    $level : Level( this!=$activeLevel )
    DescItem(type=="ZP2015_FOLDER_TYPE" && (specCode in ("ZP2015_FOLDER_SINGLE_TYPE", "ZP2015_FOLDER_UNITS", "ZP2015_FOLDER_DAO" ) ) ) from $level.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_FOLDER_TYPE")
    $itemSpec : RulItemSpecExt(code == "ZP2015_FOLDER_LOGICAL" ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Nesmí být jiná než logická složka, pokud nadřazená složka je s uvedenim EJ nebo hromadina"
no-loop
when
    $activeLevel : ActiveLevel( parent!=null  )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $activeLevel.descItems
    $level : Level( this!=$activeLevel )
    DescItem(type=="ZP2015_FOLDER_TYPE" && (specCode in ("ZP2015_FOLDER_SINGLE_TYPE", "ZP2015_FOLDER_UNITS", "ZP2015_FOLDER_DAO") ) ) from $level.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_FOLDER_TYPE")
    $itemSpec : RulItemSpecExt(code != "ZP2015_FOLDER_LOGICAL" ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.IMPOSSIBLE);
end

// Pokud je nadřazená složka bez uvedeni EJ nebo hromadina, potom muze byt hromadina nebo s uvedenim EJ
rule "Může být hromadina nebo s uvedením EJ, pokud nemá nadřazenou složku nebo jen logické"
no-loop
when
    $activeLevel : ActiveLevel( )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $activeLevel.descItems
    // neexistje nadrizeny level typu slozka
    not ( $level : Level( this!=$activeLevel ) and
         DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $level.descItems and
         DescItem(type=="ZP2015_FOLDER_TYPE" && specCode!="ZP2015_FOLDER_LOGICAL" ) from $level.descItems )
    $itemType : RulItemTypeExt(code == "ZP2015_FOLDER_TYPE")
    $itemSpec : RulItemSpecExt(code != "ZP2015_FOLDER_LOGICAL" ) from $itemType.rulItemSpecList
    // v katalogu nelze zadat slozku s vice stejnymi EJ
    // TODO: prepsat podminku pozitivne
    not (
        DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode=="ZP2015_ARRANGEMENT_KAT") from $activeLevel.descItems and
        RulItemSpecExt($itemSpec==this && code == "ZP2015_FOLDER_SINGLE_TYPE" ) from $itemType.rulItemSpecList
        )
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Typ pořádání - lze nastavit do úrovně složka
rule "Typ pořádání"
no-loop
when
  $activeLevel : ActiveLevel( )
  DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ROOT", "ZP2015_LEVEL_SECTION", "ZP2015_LEVEL_SERIES", "ZP2015_LEVEL_FOLDER") ) from $activeLevel.descItems
  $itemType : RulItemTypeExt(code == "ZP2015_ARRANGEMENT_TYPE")
  $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
  $itemType.setType(RulItemType.Type.POSSIBLE);
  $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

//------------------------------------------------------------------
// Prvky popisu pro každou složku
//-----------------------------------------------------------------

rule "Možné role entit pro složku"
no-loop
when $activeLevel: ActiveLevel( )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",        
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // vydavatelé / nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // pečetitelé
        "ZP2015_ENTITY_ROLE_17",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",
        // žadatelé
        "ZP2015_ENTITY_ROLE_22",
        // odesilatelé
        "ZP2015_ENTITY_ROLE_24",
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // redaktor
        "ZP2015_ENTITY_ROLE_32",
        // kartografové
        "ZP2015_ENTITY_ROLE_33",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // překladatelé
        "ZP2015_ENTITY_ROLE_44",
        // svědci
        "ZP2015_ENTITY_ROLE_46",
        // ručitelé (rukojmě)
        "ZP2015_ENTITY_ROLE_47",
        // písaři
        "ZP2015_ENTITY_ROLE_48",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vydání
        "ZP2015_ENTITY_ROLE_58",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62",
        // osoba/bytost zachycená jednotkami popisu
        "ZP2015_ENTITY_ROLE_66",
        // rod/rodina zachycená jednotkami popisu
		"ZP2015_ENTITY_ROLE_67",
		// korporace zachycená jednotkami popisu
		"ZP2015_ENTITY_ROLE_68",
		// událost zachycená jednotkami popisu
		"ZP2015_ENTITY_ROLE_69",
		// dílo/výtvor zachycené jednotkami popisu
		"ZP2015_ENTITY_ROLE_70",
		// geografický objekt zachycený jednotkami popisu
		"ZP2015_ENTITY_ROLE_71",
		// obecný pojem vztahující se k jednotce popisu
		"ZP2015_ENTITY_ROLE_72"        
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end


//----------------------------------------------------------------
// Složka manipulačního seznamu
//----------------------------------------------------------------

rule "Složka manipulačního seznamu"
no-loop
when
    // nesmi jiz mit deti
    $activeLevel : ActiveLevel( !hasChildren )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_MAN", "ZP2015_ARRANGEMENT_OTHER") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_FOLDER_TYPE" && specCode in ("ZP2015_FOLDER_UNITS", 
    													"ZP2015_FOLDER_LOGICAL", 
    													"ZP2015_FOLDER_SINGLE_TYPE") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_EXTRA_UNITS")
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Složka manipulačního seznamu - všechny typy archiválií"
no-loop
when
    $activeLevel : ActiveLevel( !hasChildren )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_MAN", "ZP2015_ARRANGEMENT_OTHER") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_FOLDER_TYPE" && specCode in ("ZP2015_FOLDER_UNITS", 
    												    "ZP2015_FOLDER_LOGICAL",
    												    "ZP2015_FOLDER_SINGLE_TYPE") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_EXTRA_UNITS")
    $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
  $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end


// Pořadové číslo povinné pokud je určen způsob pořádání
// zde je označeno, jen jako možné - je generováno akcí
rule "Pořadové číslo - možné"
no-loop
when
    $activeLevel : ActiveLevel( )
    $itemType : RulItemTypeExt(code == "ZP2015_SERIAL_NUMBER")
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setPolicyTypeCode("SERIAL_NO");
end

// referenční označení možné pro ostatní typy pro nejvyšší uzly
// neni mozne pro koren
rule "Referenční označení - možné pro série vždy"
no-loop
when
    $activeLevel: ActiveLevel( parent!=null && $items: descItems)
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ROOT" , "ZP2015_LEVEL_SECTION", "ZP2015_LEVEL_SERIES") ) from $items
    not DescItem(type=="ZP2015_SERIAL_NUMBER") from $items
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_ID")
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setPolicyTypeCode("REF_NO");
end

// referenční označení v INV|KAT - povinné pro uzly mimo kořen
// neni mozne pro koren
rule "Referenční označení - povinné"
no-loop
when
    $activeLevel: ActiveLevel( parent!=null )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_ID")
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setPolicyTypeCode("REF_NO");
end

rule "Ukládací jednotka na množstevní složce a složce s EJ - povině"
// Pravidlo se vyhodnocuje později - po nastavení volitelnosti
salience -100
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $activeLevel.descItems
    DescItem(type=="ZP2015_FOLDER_TYPE" && (specCode in ("ZP2015_FOLDER_UNITS", "ZP2015_FOLDER_SINGLE_TYPE") ) ) from $activeLevel.descItems
    not DescItem(type=="ZP2015_ITEM_LINK") from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_STORAGE_ID")
then
    $itemType.setType(RulItemType.Type.REQUIRED);
    $itemType.setPolicyTypeCode("ZP2015_POL_STORAGE_ID");
end

rule "Ukládací jednotka na logické a hromadné složce"
// Pravidlo se vyhodnocuje později - po nastavení volitelnosti
// využívá se pro složku manip seznamu a to i ve starších pomůckách
salience -100
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $activeLevel.descItems
    DescItem(type=="ZP2015_FOLDER_TYPE" && (specCode in ("ZP2015_FOLDER_LOGICAL", "ZP2015_FOLDER_UNITS") ) ) from $activeLevel.descItems
    // složka s dodatečnými EJ (obyvkle složka manip.seznamu)
    DescItem(type=="ZP2015_EXTRA_UNITS" ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_STORAGE_ID")
then
    $itemType.setType(RulItemType.Type.REQUIRED);
    $itemType.setPolicyTypeCode("ZP2015_POL_STORAGE_ID");
    $itemType.setRepeatable(true);
end


rule "Uložení v DA na digitální složce"
salience -100
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $activeLevel.descItems
    DescItem(type=="ZP2015_FOLDER_TYPE" && (specCode in ("ZP2015_FOLDER_DAO") ) ) from $activeLevel.descItems
    not DescItem(type=="ZP2015_ITEM_LINK") from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_AIP_ID")
then
    $itemType.setType(RulItemType.Type.REQUIRED);
    $itemType.setPolicyTypeCode("ZP2015_POL_STORAGE_ID");
end

rule "Ukládací jednotka na jednotlivosti bez nadřazené množstevní složky nebo složky s EJ - povině (vyjma KZA a ZZA, KTT)"
// Pravidlo se vyhodnocuje později - po nastavení volitelnosti
salience -100
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_ITEM" ) from $activeLevel.descItems
    // nemá poděděný typ složky množstevní nebo s EJ
    not DescItem(type=="ZP2015_FOLDER_TYPE" && (specCode in ("ZP2015_FOLDER_UNITS", "ZP2015_FOLDER_SINGLE_TYPE") ) ) from $activeLevel.descItems
    // nejedná se o Film nebo zvuk záznam
    not DescItem(type=="ZP2015_UNIT_TYPE" && (specCode in ("ZP2015_UNIT_TYPE_KZA", "ZP2015_UNIT_TYPE_ZZA", "ZP2015_UNIT_TYPE_KTT") ) ) from $activeLevel.descItems
    // není s ničím pevně spojena
    not DescItem(type in ("ZP2015_ITEM_LINK", "ZP2015_AIP_ID", "ZP2015_STORAGE_ID") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code in ("ZP2015_STORAGE_ID") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
    $itemType.setPolicyTypeCode("ZP2015_POL_STORAGE_ID");
end

rule "Ukládací jednotka na jednotlivosti v DA bez nadřazené množstevní složky nebo složky s EJ - povině (vyjma KZA a ZZA, KTT)"
// Pravidlo se vyhodnocuje později - po nastavení volitelnosti
salience -100
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_ITEM" ) from $activeLevel.descItems
    // nemá poděděný typ složky množstevní nebo s EJ
    not DescItem(type=="ZP2015_FOLDER_TYPE" && (specCode in ("ZP2015_FOLDER_UNITS", "ZP2015_FOLDER_SINGLE_TYPE", "ZP2015_FOLDER_DAO") ) ) from $activeLevel.descItems
    // nejedná se o Film nebo zvuk záznam
    not DescItem(type=="ZP2015_UNIT_TYPE" && (specCode in ("ZP2015_UNIT_TYPE_KZA", "ZP2015_UNIT_TYPE_ZZA", "ZP2015_UNIT_TYPE_KTT") ) ) from $activeLevel.descItems
    // není s ničím pevně spojena
    not DescItem(type in ("ZP2015_ITEM_LINK", "ZP2015_STORAGE_ID") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code in ("ZP2015_AIP_ID") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
    $itemType.setPolicyTypeCode("ZP2015_POL_STORAGE_ID");
end

rule "Ukládací jednotka na jednotlivosti bez nadřazené množstevní složky nebo složky s EJ - doporučené pro KZA, ZZA"
// Pravidlo se vyhodnocuje později - po nastavení volitelnosti
salience -100
no-loop
when
    // pokud ma dilci casti, tak muze byt ukladaci jednotka specifikovana na nich
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_ITEM" ) from $activeLevel.descItems
    // nemá poděděný typ složky množstevní nebo s EJ
    not DescItem(type=="ZP2015_FOLDER_TYPE" && (specCode in ("ZP2015_FOLDER_UNITS", "ZP2015_FOLDER_SINGLE_TYPE") ) ) from $activeLevel.descItems
    not DescItem(type=="ZP2015_ITEM_LINK") from $activeLevel.descItems
    // jedná se o Film nebo zvuk záznam
    DescItem(type=="ZP2015_UNIT_TYPE" && (specCode in ("ZP2015_UNIT_TYPE_KZA", "ZP2015_UNIT_TYPE_ZZA") ) ) from $activeLevel.descItems    
    $itemType : RulItemTypeExt(code == "ZP2015_STORAGE_ID")
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Ukládací jednotka na jednotlivosti bez nadřazené množstevní složky nebo složky s EJ - doporučené pro KTT"
// Pravidlo se vyhodnocuje později - po nastavení volitelnosti
salience -100
no-loop
when
    $activeLevel: ActiveLevel( !hasChildren )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_ITEM" ) from $activeLevel.descItems
    // nemá poděděný typ složky množstevní nebo s EJ
    not DescItem(type=="ZP2015_FOLDER_TYPE" && (specCode in ("ZP2015_FOLDER_UNITS", "ZP2015_FOLDER_SINGLE_TYPE") ) ) from $activeLevel.descItems
    // jedná se o kartotéku
    DescItem(type=="ZP2015_UNIT_TYPE" && (specCode in ("ZP2015_UNIT_TYPE_KTT") ) ) from $activeLevel.descItems    
    $itemType : RulItemTypeExt(code == "ZP2015_STORAGE_ID")
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

// Ukládací jednotka pro kartoteční zásuvku
rule "Ukládací jednotka pro kartoteční zásuvku"
salience -100
no-loop
when
    $activeLevel: ActiveLevel()
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_PART" ) from $activeLevel.descItems
    // jedná se o kartotéční zásuvku
    DescItem(type=="ZP2015_UNIT_TYPE" && (specCode in ("ZP2015_UNIT_TYPE_KTT_BOX") ) ) from $activeLevel.descItems    
    $itemType : RulItemTypeExt(code == "ZP2015_STORAGE_ID")
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Hromadinová ukládací jednotka se nesmí opakovat"
salience -200
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_STORAGE_ID" && structured!=null ) from $activeLevel.descItems
    StructObjItem(type=="ZP2015_PACKET_TYPE" && specCode in ("ZP2015_PACKET_TYPE_KAR", "ZP2015_PACKET_TYPE_FAS")) from $descItem.structured.items
    
    $descItem2 : DescItem(type=="ZP2015_STORAGE_ID" && structured!=null && $descItem!=this ) from $activeLevel.descItems
    StructObjItem(type=="ZP2015_PACKET_TYPE" && specCode in ("ZP2015_PACKET_TYPE_KAR", "ZP2015_PACKET_TYPE_FAS")) from $descItem2.structured.items
    
    $itemType : RulItemTypeExt(code == "ZP2015_STORAGE_ID")
then
    $itemType.setType(RulItemType.Type.IMPOSSIBLE);
end


//----------------------------------------------------
// Druhy archivalii
//---------------------------------------------------

// Druh archiválie povinně - u složky s jednotlivostmi
rule "Druh archiválie - povinně u složky"
no-loop
when
    $activeLevel: ActiveLevel( )
    // jedna se o slozku
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $activeLevel.descItems
    // ma nastaven typ slozky - slozka jednotlivosti
    DescItem(type=="ZP2015_FOLDER_TYPE" && specCode=="ZP2015_FOLDER_SINGLE_TYPE" ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code in ("ZP2015_UNIT_TYPE", "ZP2015_UNIT_COUNT") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// U složky man. seznamu lze vybrat skoro libovolny typ jendotlivosti
// Nelze vybrat cast jednotlivosti
rule "Druh archiválie - složka MAN a Starsi pomucky"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_MAN", "ZP2015_ARRANGEMENT_OTHER") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE")
    $itemSpec : RulItemSpecExt(code in ( "ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP",
        "ZP2015_UNIT_TYPE_UKN", 
        // Rukopisy 
        "ZP2015_UNIT_TYPE_RKP",
        // Podací protokoly
        "ZP2015_UNIT_TYPE_PPR",
        // Indexy
        "ZP2015_UNIT_TYPE_IND", 
        // Elenchy
        "ZP2015_UNIT_TYP_ELE",
        // Repertáře
        "ZP2015_UNIT_TYPE_REP",
        // Kartotéky
        "ZP2015_UNIT_TYPE_KTT",
        // Pečetidla
        "ZP2015_UNIT_TYPE_PEC",
        // Razítka
        "ZP2015_UNIT_TYPE_RAZ",
        // Samostatné pečetě, odlitky pečetí a otisky typářů
        "ZP2015_UNIT_TYPE_OTD",
        // Kopie otisků 
        "ZP2015_UNIT_TYPE_OTC",
        // Mapy
        "ZP2015_UNIT_TYPE_MAP",
        // Atlasy
        "ZP2015_UNIT_TYPE_ATL",
        // Technické výkresy
        "ZP2015_UNIT_TYPE_TVY",
        // Grafické listy
        "ZP2015_UNIT_TYPE_GLI",
        // Kresby
        "ZP2015_UNIT_TYPE_KRE",
        // Fotografie na papírové podložce
        "ZP2015_UNIT_TYPE_FSN",
        // Fotografické desky
        "ZP2015_UNIT_TYPE_FSD",
        // Listové filmy
        "ZP2015_UNIT_TYPE_LFI",
        // Svitkové filmy
        "ZP2015_UNIT_TYPE_SFI",
        // Kinofilmy
        "ZP2015_UNIT_TYPE_KIN",
        // Mikrofilmy
        "ZP2015_UNIT_TYPE_MF",
        // Mikrofiše
        "ZP2015_UNIT_TYPE_MFS",
        // Fotoalba
        "ZP2015_UNIT_TYPE_FAL",
        // Digitální fotografie
        "ZP2015_UNIT_TYPE_DFO",
        // Kinematografické záznamy (díla) v analogové i digitální podobě
        "ZP2015_UNIT_TYPE_KZA",
        // Zvukové záznamy (díla) v analogové i digitální podobě
        "ZP2015_UNIT_TYPE_ZZA",
        // Tisky do roku 1800
        "ZP2015_UNIT_TYPE_TIO",
        // Tisky po roce 1800
        "ZP2015_UNIT_TYPE_TIP",
        // Pohlednice
        "ZP2015_UNIT_TYPE_POH",
        // Plakáty
        "ZP2015_UNIT_TYPE_PKT",
        // Cenné papíry
        "ZP2015_UNIT_TYPE_CPA",
        // Štočky
        "ZP2015_UNIT_TYPE_STO",
        // Předměty numizmatické povahy
        "ZP2015_UNIT_TYPE_PNP",
        // Předměty faleristické povahy
        "ZP2015_UNIT_TYPE_PFP",
        // Jiné
        "ZP2015_UNIT_TYPE_JIN"
         ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// 3.4.2 Inventar
// U logické složky inventare nesmi byt uvedene typy
rule "Druh archiválie - slozka v INV"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode == "ZP2015_ARRANGEMENT_INV" ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE")
    $itemSpec : RulItemSpecExt(
    code in (
    // Rukopis
    "ZP2015_UNIT_TYPE_RKP",
    // Razítko
    "ZP2015_UNIT_TYPE_RAZ",
    // Samostatná pečeť, odlitek pečeti, otisk typáře
    "ZP2015_UNIT_TYPE_OTD",
    // Kopie otisku
    "ZP2015_UNIT_TYPE_OTC",
    // Mapa
    "ZP2015_UNIT_TYPE_MAP",
    // Technický výkres
    "ZP2015_UNIT_TYPE_TVY",
    // Grafický list
    "ZP2015_UNIT_TYPE_GLI",
    // Kresba
    "ZP2015_UNIT_TYPE_KRE",
    // Fotografie na papírové podložce
    "ZP2015_UNIT_TYPE_FSN",
    // Fotografická deska
    "ZP2015_UNIT_TYPE_FSD",
    // Listový filmy
    "ZP2015_UNIT_TYPE_LFI",
    // Svitkový film
    "ZP2015_UNIT_TYPE_SFI",
    // Kinofilm
    "ZP2015_UNIT_TYPE_KIN",
    // Mikrofilm
    "ZP2015_UNIT_TYPE_MF",
    // Mikrofiš
    "ZP2015_UNIT_TYPE_MFS",
    // Digitální fotografie
    "ZP2015_UNIT_TYPE_DFO",
    // Kinematografický záznam (dílo) v analogové i digitální podobě
    "ZP2015_UNIT_TYPE_KZA",
    // Zvukový záznam (dílo) v analogové i digitální podobě
    "ZP2015_UNIT_TYPE_ZZA",
    // Tisk po roce 1800
    "ZP2015_UNIT_TYPE_TIP",
    // Pohlednice
    "ZP2015_UNIT_TYPE_POH",
    // Plakát
    "ZP2015_UNIT_TYPE_PKT",
    // Cenný papír
    "ZP2015_UNIT_TYPE_CPA",
    // Štoček
    "ZP2015_UNIT_TYPE_STO",
    // Předmět numizmatické povahy
    "ZP2015_UNIT_TYPE_PNP",
    // Předmět faleristické povahy
    "ZP2015_UNIT_TYPE_PFP",
    // Jiná
    "ZP2015_UNIT_TYPE_JIN"    
    )) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Poznamka 3.4.3 Katalog - nelze evidovat jednotlivosti u slozky


rule "Druh archiválie - povinně u jednotlivosti a části jednotlivosti"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE")
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Druh archiválie - možné u jednotlivosti a části jednotlivosti (všechny typy pomůcek)"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE")
    $itemSpec : RulItemSpecExt(code in ( "ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP",
        "ZP2015_UNIT_TYPE_UKN", 
        // Rukopisy 
        "ZP2015_UNIT_TYPE_RKP",
        // Podací protokoly
        "ZP2015_UNIT_TYPE_PPR",
        // Indexy
        "ZP2015_UNIT_TYPE_IND", 
        // Elenchy
        "ZP2015_UNIT_TYP_ELE",
        // Repertáře
        "ZP2015_UNIT_TYPE_REP",
        // Samostatné pečetě, odlitky pečetí a otisky typářů
        "ZP2015_UNIT_TYPE_OTD",
        // Mapy
        "ZP2015_UNIT_TYPE_MAP",
        // Technické výkresy
        "ZP2015_UNIT_TYPE_TVY",
        // Grafické listy
        "ZP2015_UNIT_TYPE_GLI",
        // Kresby
        "ZP2015_UNIT_TYPE_KRE",
        // Fotografie na papírové podložce
        "ZP2015_UNIT_TYPE_FSN",
        // Fotoalba
        "ZP2015_UNIT_TYPE_FAL",
        // Tisky do roku 1800
        "ZP2015_UNIT_TYPE_TIO",
        // Tisky po roce 1800
        "ZP2015_UNIT_TYPE_TIP",
        // Pohlednice
        "ZP2015_UNIT_TYPE_POH",
        // Plakáty
        "ZP2015_UNIT_TYPE_PKT",
        // Cenné papíry
        "ZP2015_UNIT_TYPE_CPA",
        // Jiné
        "ZP2015_UNIT_TYPE_JIN"
         ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Druh archiválie - možné jen u jednotlivosti (všechny typy pomůcek)"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE")
    $itemSpec : RulItemSpecExt(code in (
        // Kartotéky
        "ZP2015_UNIT_TYPE_KTT",
        // Pečetidla
        "ZP2015_UNIT_TYPE_PEC",
        // Razítka
        "ZP2015_UNIT_TYPE_RAZ",
        // Kopie otisků 
        "ZP2015_UNIT_TYPE_OTC",
        // Atlasy
        "ZP2015_UNIT_TYPE_ATL",
        // Fotografické desky
        "ZP2015_UNIT_TYPE_FSD",
        // Listové filmy
        "ZP2015_UNIT_TYPE_LFI",
        // Svitkové filmy
        "ZP2015_UNIT_TYPE_SFI",
        // Kinofilmy
        "ZP2015_UNIT_TYPE_KIN",
        // Mikrofilmy
        "ZP2015_UNIT_TYPE_MF",
        // Mikrofiše
        "ZP2015_UNIT_TYPE_MFS",
        // Digitální fotografie
        "ZP2015_UNIT_TYPE_DFO",
        // Kinematografické záznamy (díla) v analogové i digitální podobě
        "ZP2015_UNIT_TYPE_KZA",
        // Zvukové záznamy (díla) v analogové i digitální podobě
        "ZP2015_UNIT_TYPE_ZZA",
        // Štočky
        "ZP2015_UNIT_TYPE_STO",
        // Předměty numizmatické povahy
        "ZP2015_UNIT_TYPE_PNP",
        // Předměty faleristické povahy
        "ZP2015_UNIT_TYPE_PFP",
        // Neevidovaná jednotlivost
        "ZP2015_UNIT_TYPE_OTHER"    
         ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Druh archiválie - možné jen u části jednotlivosti (všechny typy pomůcek)"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE")
    $itemSpec : RulItemSpecExt(code in (
        // Obecná část jednotlivosti
        "ZP2015_UNIT_TYPE_PART"    
         ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

//---------------------------------------------
// Dale jednotlive prvky popisu
//---------------------------------------------

rule "Obsah/regest - doporučený pro složku a níže"
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code in ( "ZP2015_TITLE" ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Obsah/regest - povinný pro sérii"
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_SERIES") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code in ( "ZP2015_TITLE" ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// Vždy možné prvky popisu
rule "Univerzální prvky popisu - možné"
no-loop
when
    $itemType : RulItemTypeExt(code in
    ( "ZP2015_OTHER_ID",
      // 4.3.1 Odkaz na původce 
      "ZP2015_ORIGINATOR", 
      // 4.3.2 Dějiny jednotky popisu
      "ZP2015_UNIT_HIST", 
      // 4.3.3 Způsob uspořádání jednotky popisu
      "ZP2015_UNIT_ARR",
      // 4.3.4 Tematický popis jednotky popisu
      "ZP2015_UNIT_CONTENT",
      // 4.3.5 Přímý zdroj akvizice
      "ZP2015_UNIT_SOURCE", 
      // ZP4.3.6 Budoucí přírůstky 
      "ZP2015_FUTURE_UNITS",
      // 4.4.1 Podmínky přístupu, práva k jednotce popisu a její reprodukci
      "ZP2015_UNIT_ACCESS",
      // 4.4.2 Možnost zveřejnění informací o jednotce popisu
      "ZP2015_UNIT_INFO_RIGHTS", 
      "ZP2015_RESTRICTION_ACCESS_SHARED", 
      "ZP2015_RESTRICTION_ACCESS_INLINE", 
      "ZP2015_PUBLISHED",
      // 4.4.3 Možnost zveřejnění reprodukce jednotky popisu
      "ZP2015_UNIT_COPY_RIGHTS",
      // 4.4.4 Fyzický stav jednotky popisu a technické požadavky
      "ZP2015_UNIT_CURRENT_STATUS",
      // ZP 4.5.1 Identifikace předlohy kopie
      "ZP2015_COPY_SOURCE",
      // ZP 4.5.2
      "ZP2015_RELATED_UNITS",
      // ZP 4.5.3
      "ZP2015_EXISTING_COPY",
      // Poznámky - ZP 4.6.1, 4.6.2
      "ZP2015_INTERNAL_NOTE", "ZP2015_NOTE",
      // 4.7.1 Zpracovatel jednotky popisu
      "ZP2015_ARRANGER",
      // 4.7.1 Informace o zpracování
      "ZP2015_ARRANGEMENT_INFO",
      // 4.7.2 Pravidla zpracování jednotky popisu
      "ZP2015_ARRANGE_RULES",
      // ZP4.7.3 Datum (data) popisu 
      "ZP2015_DESCRIPTION_DATE",
      // ZP 5.2.10 Jazyk
      "ZP2015_LANGUAGE",
      // ZP 5.2.10 písmo
      "ZP2015_WRITING",
      // ZP 5.2.11 Edice a literatura
      "ZP2015_EDITION",
      // Obecná příloha 
      "ZP2015_ATTACHMENT" ) )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Univerzální prvky popisu - možné od série níže"
no-loop
when
    $activeLevel: ActiveLevel( )
    $itemType : RulItemTypeExt(code in
    ( 
      // ZP4.2.4 Formální název jednotky popisu
      "ZP2015_FORMAL_TITLE"
     ) )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in (
        "ZP2015_LEVEL_SERIES", "ZP2015_LEVEL_FOLDER", 
        "ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART",
        "ZP2015_AP_REF") 
        ) from $activeLevel.descItems
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Univerzální prvky popisu - možné na složce"
no-loop
when
    $activeLevel: ActiveLevel( )
    $itemType : RulItemTypeExt(code in
    (
      // ZP5.2.2 Název autorského díla
      "ZP2015_ITEM_TITLE_REF"
     ) )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER") ) from $activeLevel.descItems
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Univerzální prvky popisu - možné od složky níže"
no-loop
when
    $activeLevel: ActiveLevel( )
    $itemType : RulItemTypeExt(code in
    ( 
      // ZP4.2.10 Ukládací jednotka a číslo
      "ZP2015_STORAGE_ID",      
      // ZP5.2.3 Způsob a forma dochování
      "ZP2015_STORAGE_COND",
      // ZP5.2.4 Rozměry, hmotnost, velikost, množství 
      "ZP2015_SIZE",
      // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
      "ZP2015_ITEM_MAT",
      // ZP5.2.9 Díl, část, pořadí vydání jednotky popisu
      "ZP2015_PART",
      // Role entit jsou možné vždy
      "ZP2015_ENTITY_ROLE"
     ) )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $activeLevel.descItems
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Ideální popis - jednotlivost"
no-loop
when
    $activeLevel: ActiveLevel( )
    $itemType : RulItemTypeExt(code in ( "ZP2015_ITEM_LINK" ) )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM") ) from $activeLevel.descItems
    not DescItem(type=="ZP2015_STORAGE_ID") from $activeLevel.descItems
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Podtypy jednotek popisu
rule "Podtypy jednotek popisu - jednotlivost a část jednotlivosti"
no-loop
when
    $activeLevel: ActiveLevel( )
    $itemType : RulItemTypeExt(code in
    ( 
      "ZP2015_UNIT_SUBTYPE"
     ) )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $activeLevel.descItems
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Podtypy jednotek popisu - množstevní složka"
no-loop
when
    $activeLevel: ActiveLevel( )
    $itemType : RulItemTypeExt(code in
    ( 
      "ZP2015_UNIT_SUBTYPE"
     ) )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_FOLDER_TYPE" && specCode in ("ZP2015_FOLDER_UNITS") ) from $activeLevel.descItems
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Podtypy jednotek popisu - pro UKN"
no-loop
when
    $activeLevel: ActiveLevel( )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_UKN") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code=="ZP2015_UNIT_SUBTYPE")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_UNIT_SUBTYPE_MTR")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Podtypy jednotek popisu - pro RKP"
no-loop
when
    $activeLevel: ActiveLevel( )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_RKP") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code=="ZP2015_UNIT_SUBTYPE")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_UNIT_SUBTYPE_HDB")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Podtypy jednotek popisu - pro ZP2015_UNIT_TYPE_PFP"
no-loop
when
    $activeLevel: ActiveLevel( )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PFP") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code=="ZP2015_UNIT_SUBTYPE")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_UNIT_SUBTYPE_STV")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Podtypy jednotek popisu - pro ZP2015_UNIT_TYPE_OTHER"
no-loop
when
    $activeLevel: ActiveLevel( )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_OTHER") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code=="ZP2015_UNIT_SUBTYPE")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_UNIT_SUBTYPE_PA", 
    									"ZP2015_UNIT_SUBTYPE_STVR", "ZP2015_UNIT_SUBTYPE_JMF"
    									)) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Povolení všech jiných označení
rule "Povolení všech jiných označení (ZP2015_OTHER_ID)"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_OTHER_ID")
    $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Povolení všech jazyků
rule "Povolení všech jazyků (ZP2015_LANGUAGE)"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_LANGUAGE")
    $itemSpec : RulItemSpecExt() from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Datace - strojová a jiná datace
rule "Datace - možná na složce a níže"
no-loop
when
    $activeLevel: ActiveLevel( )
    $itemType : RulItemTypeExt(code in ( "ZP2015_UNIT_DATE", "ZP2015_DATE_OTHER" ) )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $activeLevel.descItems
    // neexistje nadrizeny level typu logicka slozka s dataci a posuzovana uroven je slozka
    not ( $level : Level( this!=$activeLevel ) and
         //DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $level.descItems and
         DescItem(type=="ZP2015_FOLDER_TYPE" && specCode=="ZP2015_FOLDER_LOGICAL" ) from $level.descItems and
         DescItem(type in ( "ZP2015_UNIT_DATE", "ZP2015_DATE_OTHER" )) from $level.descItems and
         DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER") ) from $descItem
         )    
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Datace - textová
// Dotaz: v jakých úrovních?
rule "Datace - textová"
no-loop
when
    $activeLevel: ActiveLevel( )
    //not DescItem(type=="ZP2015_UNIT_DATE_TEXT" ) from $activeLevel.descItems
    //not DescItem(type in ( "ZP2015_UNIT_DATE_PRE", "ZP2015_UNIT_DATE", "ZP2015_UNIT_DATE_POST" ) ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code=="ZP2015_UNIT_DATE_TEXT")
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $activeLevel.descItems
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Na kořeni je možné uvést vlastní časový rozsah fondu
rule "Vlastní časový rozsah fondu - ZP2015_UNIT_DATE_BULK"
no-loop
when
    $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ROOT") ) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code=="ZP2015_UNIT_DATE_BULK")
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Standarní datace je doporučená pro poslední složku a část jednotlivosti (bez potomků)
rule "Datace - strojová - doporučení"
salience -100
no-loop
when
    $activeLevel: ActiveLevel( !hasChildren )
    $itemType : RulItemTypeExt(code in ( "ZP2015_UNIT_DATE" ) )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM") ) from $activeLevel.descItems

    // neexistje nadrizeny level typu logicka slozka s dataci
    not ( $level : Level( this!=$activeLevel ) and
         //DescItem(type=="ZP2015_LEVEL_TYPE" && specCode=="ZP2015_LEVEL_FOLDER" ) from $level.descItems and
         DescItem(type=="ZP2015_FOLDER_TYPE" && specCode=="ZP2015_FOLDER_LOGICAL" ) from $level.descItems and
         DescItem(type in ( "ZP2015_UNIT_DATE", "ZP2015_DATE_OTHER" )) from $level.descItems
         //DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM") ) from $descItem
         )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

// Povolení specifikací jiné datace označení
rule "Povolení vybraných jiných datací (ZP2015_DATE_OTHER)"
no-loop
when
    $itemType : RulItemTypeExt(code == "ZP2015_DATE_OTHER")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_DATE_OF_CONTENT",
    "ZP2015_DATE_DECLARED", "ZP2015_DATE_ORIG", "ZP2015_DATE_OF_COPY", "ZP2015_DATE_SEALING",
    "ZP2015_DATE_ACT_PUBLISHING", "ZP2015_DATE_INSERT", "ZP2015_DATE_MOLD_CREATION",
    "ZP2015_DATE_PUBLISHING", "ZP2015_DATE_CAPTURING")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povolení vždy možných rolí entit"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems ) 
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
    $itemSpec: RulItemSpecExt( code in (
        // osoba/bytost zachycená jednotkami popisu
        "ZP2015_ENTITY_ROLE_66",
        // rod/rodina zachycená jednotkami popisu
		"ZP2015_ENTITY_ROLE_67",
		// korporace zachycená jednotkami popisu
		"ZP2015_ENTITY_ROLE_68",
		// událost zachycená jednotkami popisu
		"ZP2015_ENTITY_ROLE_69",
		// dílo/výtvor zachycené jednotkami popisu
		"ZP2015_ENTITY_ROLE_70",
		// geografický objekt zachycený jednotkami popisu
		"ZP2015_ENTITY_ROLE_71",
		// obecný pojem vztahující se k jednotce popisu
		"ZP2015_ENTITY_ROLE_72"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Doporučené prvky pro první nastavení typu pomůcky (všechny typy)"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in (
        "ZP2015_ARRANGEMENT_OTHER", "ZP2015_ARRANGEMENT_MAN", "ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT"
        ) ) from $activeLevel.descItems
    // nesmi existovat rodic, ktery by mel jiz vyhodnoceni nastaveno
    not ( $level: Level( this!=$activeLevel && $parentItems: descItems ) and
         DescItem(type in ( "ZP2015_ARRANGEMENT_TYPE" ) )
          from $level.descItems )    
    $itemType: RulItemTypeExt( code in (
        // ZP4.3.3 Způsob uspořádání jednotky popisu
        "ZP2015_UNIT_ARR", 
        // 4.3.5 Přímý zdroj akvizice
        "ZP2015_UNIT_SOURCE",
        // 4.4.4 Fyzický stav jednotky popisu a technické požadavky 
        "ZP2015_UNIT_CURRENT_STATUS",
        // 4.7.1 Zpracovatel     
        "ZP2015_ARRANGER", 
        // 4.7.2 Pravidla zpracování jednotky popisu
        "ZP2015_ARRANGE_RULES", "ZP2015_LANGUAGE") )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Doporučené prvky pro první nastavení typu pomůcky (inv, kat)"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in (
        "ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT"
        ) ) from $activeLevel.descItems
    // nesmi existovat rodic, ktery by mel jiz vyhodnoceni nastaveno
    not ( $level: Level( this!=$activeLevel && $parentItems: descItems ) and
         DescItem(type in ( "ZP2015_ARRANGEMENT_TYPE" ) )
          from $level.descItems )    
    $itemType: RulItemTypeExt( code in (
        // 4.3.4 Tematický popis jednotky popisu
        "ZP2015_UNIT_CONTENT"
        ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Doporučené prvky pro první nastavení typu pomůcky (inv, kat, starsi)"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in (
        "ZP2015_ARRANGEMENT_OTHER", "ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT"
        ) ) from $activeLevel.descItems
    // nesmi existovat rodic, ktery by mel jiz vyhodnoceni nastaveno
    not ( $level: Level( this!=$activeLevel && $parentItems: descItems ) and
         DescItem(type in ( "ZP2015_ARRANGEMENT_TYPE" ) )
          from $level.descItems )    
    $itemType: RulItemTypeExt( code in (
        // ZP4.3.2 Dějiny jednotky popisu    
    	"ZP2015_UNIT_HIST" 
        ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Doporučení pro kořen inventáře a katalogu"
no-loop
salience -100
when $activeLevel: ActiveLevel( parent == null )
    $descItem : DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in (
    	// ZP4.3.6 Budoucí přírůstky
    	"ZP2015_FUTURE_UNITS"
	) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

//----------------------------------------------
// Inventář 1958 - 2015
//----------------------------------------------

rule "Inventární číslo možné na všech úrovních starší pomůcky"
no-loop
when $activeLevel: ActiveLevel( )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_OTHER")) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in (
        // Inventární číslo
        "ZP2015_INV_CISLO"
        ) )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Inventární číslo doporučené pro složky a jednotlivosti"
no-loop
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_OTHER")) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in (
        // Inventární číslo
        "ZP2015_INV_CISLO"
        ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Datace u starší pomůcky nemusí být zjištěna (sine dato)"
salience 100
no-loop
when $activeLevel: ActiveLevel( )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_OTHER")) from $activeLevel.descItems
    $itemType : RulItemTypeExt(code in ("ZP2015_UNIT_DATE"))
then
    $itemType.setIndefinable(true);
end

rule "Zneplatněný záznam možný pro složky a jednotlivosti"
no-loop
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_OTHER")) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in (
        // Zneplatněný záznam
        "ZP2015_INVALID_RECORD"
        ) )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Zneplatněný záznam možný pro složky a jednotlivosti - specifikace"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_OTHER")) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in (
        // Zneplatněný záznam
        "ZP2015_INVALID_RECORD"
        ) )
    $itemSpec: RulItemSpecExt( ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Související záznam s jinou EJ"
no-loop
when $activeLevel: ActiveLevel( )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_OTHER")) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in (
        // Související záznam
        "ZP2015_CONNECTED_RECORD"
        ) )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Související záznam s jinou EJ - specifikace"
no-loop
when $activeLevel: ActiveLevel( )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_OTHER")) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in (
        // Související záznam
        "ZP2015_CONNECTED_RECORD"
        ) )
    $itemSpec: RulItemSpecExt( ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

//----------------------------------------------
// Inventář
//----------------------------------------------

// nejsou žádná společná nastavení pro inventář


//----------------------------------------------
// Katalog
//----------------------------------------------

rule "Doporučené prvky na úrovni jednotlivosti (i části) pro katalog"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems:ownDescItems )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.9 Díl, část, pořadí vydání jednotky popisu
        "ZP2015_PART",
        // ZP5.2.10 Jazyk
        "ZP2015_LANGUAGE"
        ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Doporučené prvky na úrovni jednotlivosti (i části) pro katalog, pokud neni listem"
no-loop
salience -100
when $activeLevel: ActiveLevel( hasChildren && $ownItems:ownDescItems)
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.3 Způsob a forma dochování
        "ZP2015_STORAGE_COND",
        // ZP5.2.4 Rozměry, hmotnost, velikost, množství 
        "ZP2015_SIZE", 
        // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
        "ZP2015_ITEM_MAT"
        ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Povinné prvky na úrovni jednotlivosti (i části) pro katalog, pokud je listem"
no-loop
salience -100
when $activeLevel: ActiveLevel( !hasChildren && $ownItems:ownDescItems )
    $descItem : DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.3 Způsob a forma dochování
        "ZP2015_STORAGE_COND",
        // ZP5.2.4 Rozměry, hmotnost, velikost, množství 
        "ZP2015_SIZE", 
        // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
        "ZP2015_ITEM_MAT"
        ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end


//----------------------------------------------
// Listiny
//----------------------------------------------

// Doporučení pro listiny (vždy)
rule "Doporučení pro listiny (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems:ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $ownItems
    $itemType: RulItemTypeExt( code in ("ZP2015_STORAGE_COND", "ZP2015_SIZE", "ZP2015_ITEM_MAT",
        // ZP5.2.10 Jazyk 
        "ZP2015_LANGUAGE", "ZP2015_IMPRINT_COUNT",
        "ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

// Možné role entit pro listiny (vždy)
rule "Možné role entit pro listiny (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $ownItems 
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // pečetitelé 
        "ZP2015_ENTITY_ROLE_17",
        // příjemci 
        "ZP2015_ENTITY_ROLE_21",
        // žadatelé
        "ZP2015_ENTITY_ROLE_22",
        // svědci
        "ZP2015_ENTITY_ROLE_46",
        // ručitelé (rukojmě)
        "ZP2015_ENTITY_ROLE_47",
        // písaři
        "ZP2015_ENTITY_ROLE_48",
        // mista vydani
        "ZP2015_ENTITY_ROLE_58",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"        
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinnost prvku pro listiny v inv"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ("ZP2015_STORAGE_COND", "ZP2015_SIZE", 
        // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
        "ZP2015_ITEM_MAT",
        // ZP5.2.10 Jazyk
        "ZP2015_LANGUAGE",
        // ZP5.7.4 Počet otisků původní a současný 
        "ZP2015_IMPRINT_COUNT",
        // nastaveni vztahu
        "ZP2015_ENTITY_ROLE"
    ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro listiny (cast jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ("ZP2015_STORAGE_COND", "ZP2015_SIZE", 
        // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
        "ZP2015_ITEM_MAT",
        // ZP5.2.10 Jazyk
        "ZP2015_LANGUAGE",
        // ZP5.7.4 Počet otisků původní a současný 
        "ZP2015_IMPRINT_COUNT",
        // nastaveni vztahu
        "ZP2015_ENTITY_ROLE"
    ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Povinnost prvku pro listiny v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.7.4 Počet otisků původní a současný
        "ZP2015_IMPRINT_COUNT",
        // nastaveni vztahu
        "ZP2015_ENTITY_ROLE"
    ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinné role pro listiny v inv (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // pečetitelé 
        "ZP2015_ENTITY_ROLE_17",
        // příjemci 
        "ZP2015_ENTITY_ROLE_21",
        // mista vydani
        "ZP2015_ENTITY_ROLE_58"
         ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Doporučené role pro listiny v inv (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // pečetitelé 
        "ZP2015_ENTITY_ROLE_17",
        // příjemci 
        "ZP2015_ENTITY_ROLE_21",
        // mista vydani
        "ZP2015_ENTITY_ROLE_58"
         ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

rule "Povinné role entit pro listiny v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_LIO", "ZP2015_UNIT_TYPE_LIP") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // pečetitelé
        "ZP2015_ENTITY_ROLE_17",
        // příjemci 
        "ZP2015_ENTITY_ROLE_21", 
        // písaři
        "ZP2015_ENTITY_ROLE_48",
        // mista vydani
        "ZP2015_ENTITY_ROLE_58",
		// místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
        ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// UKN, KTT, reg.pom.
//----------------------------------------------

// Pokud je kartoteka a neni nad ni slozka s hromadinou nebo s poctem EJ,
// tak se musi pocet EJ zobrazit primo u kartoteky
rule "Počet zásuvek pro KTT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_KTT") ) from $ownItems
    // Rodič není samostatná EJ
    not (
      DescItem(type=="ZP2015_FOLDER_TYPE" && specCode in ("ZP2015_FOLDER_UNITS", "ZP2015_FOLDER_SINGLE_TYPE")) from $activeLevel.descItems
    )
    $itemType: RulItemTypeExt( code in ("ZP2015_UNIT_COUNT") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// Povolení kartotéčních lístků a zásuvek
// jen pokud je rodič KTT
rule "Možné části pro KTT"
no-loop
when
    $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // rodič je jednotlivost typu KTT
    $level: Level(this!=$activeLevel)
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_KTT") && !inherited) from $level.descItems
    $itemType : RulItemTypeExt(code == "ZP2015_UNIT_TYPE")
    $itemSpec : RulItemSpecExt(code in (
        // Kartotéční zásuvka
        "ZP2015_UNIT_TYPE_KTT_BOX",
        // Kartotéční lístek
        "ZP2015_UNIT_TYPE_KTT_ITEM"    
         ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end


// Povinné prvky pro UKN, KTT, reg.pom. (KAT)
rule "Povinné prvky pro UKN, KTT, reg.pom. (KAT)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PPR", "ZP2015_UNIT_TYPE_IND",
        "ZP2015_UNIT_TYP_ELE", "ZP2015_UNIT_TYPE_REP",
        "ZP2015_UNIT_TYPE_UKN", "ZP2015_UNIT_TYPE_KTT") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// Možné role entit pro UKN, KTT, reg.pom. (vždy)
rule "Možné role entit pro UKN, KTT, reg.pom. (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PPR", "ZP2015_UNIT_TYPE_IND",
        "ZP2015_UNIT_TYP_ELE", "ZP2015_UNIT_TYPE_REP",
        "ZP2015_UNIT_TYPE_UKN", "ZP2015_UNIT_TYPE_KTT") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // písaři
        "ZP2015_ENTITY_ROLE_48",
        // výrobci
        "ZP2015_ENTITY_ROLE_53",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
		// místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Povinné role entit pro UKN, KTT, reg.pom. v katalogu
rule "Povinne role pro UKN, KTT, reg.pom. v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PPR", "ZP2015_UNIT_TYPE_IND",
        "ZP2015_UNIT_TYP_ELE", "ZP2015_UNIT_TYPE_REP",
        "ZP2015_UNIT_TYPE_UKN", "ZP2015_UNIT_TYPE_KTT") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // písaři
        "ZP2015_ENTITY_ROLE_48",
        // výrobci
        "ZP2015_ENTITY_ROLE_53",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
		// místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"        
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// UKN - Matriky
//----------------------------------------------
rule "Možné prvky pro Matriky"
no-loop
when $activeLevel: ActiveLevel( $items: descItems )
    DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_MTR") ) from $items
    $itemType: RulItemTypeExt( code in (
         "ZP2015_UNIT_DATE"
       ) )    
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Možné prvky pro Matriky - opakovatelné"
no-loop
when $activeLevel: ActiveLevel( $items: descItems )
    DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_MTR") ) from $items
    $itemType: RulItemTypeExt( code in (
        "ZP2015_RECORD_TYPE", "ZP2015_ENTITY_ROLE", "ZP2015_OTHER_ID"
       ) )    
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
    $itemType.setRepeatable(true);
end

rule "Doporučené specifikace pro Matriky"
no-loop
when $activeLevel: ActiveLevel( $items: descItems )
    DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_MTR") ) from $items
    $itemType: RulItemTypeExt( code in (
        "ZP2015_ENTITY_ROLE"
       ) )    
    $itemSpec: RulItemSpecExt( code in ("ZP2015_ENTITY_ROLE_71")
     	) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end


rule "Možné specifikace pro Matriky"
no-loop
when $activeLevel: ActiveLevel( $items: descItems )
    $descItem : DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_MTR") ) from $items
    $itemType: RulItemTypeExt( code in (
        "ZP2015_RECORD_TYPE"
       ) )    
    $itemSpec: RulItemSpecExt( code in (
     	"ZP2015_RECORD_TYPE_BORN", "ZP2015_RECORD_TYPE_DIED", "ZP2015_RECORD_TYPE_MARRIED",
     	"ZP2015_RECORD_TYPE_INDEX_BORN", "ZP2015_RECORD_TYPE_INDEX_DIED", "ZP2015_RECORD_TYPE_INDEX_MARRIED") 
     	) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Doporučená signatura původce pro Matriky"
no-loop
when $activeLevel: ActiveLevel( $items: descItems )
    $descItem : DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_MTR") ) from $items
    $itemType: RulItemTypeExt( code in (
        "ZP2015_OTHER_ID"
       ) )    
    $itemSpec: RulItemSpecExt( code in ("ZP2015_OTHERID_SIG_ORIG")
     	) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end


//----------------------------------------------
// Rukopisy
//----------------------------------------------

// Možné prvky pro Rukopisy (vždy)
rule "Možné prvky pro Rukopisy (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_RKP") ) from $ownItems
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF"
       ) )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Možné role entit pro Rukopisy
rule "Možné role entit pro Rukopisy"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_RKP") ) from $ownItems
    not DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_HDB") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři textu
        "ZP2015_ENTITY_ROLE_11",
        // objednatelé / příjemci
        "ZP2015_ENTITY_ROLE_19",
        // tvůrci výtvarné stránky 
        "ZP2015_ENTITY_ROLE_39",
        // písaři
        "ZP2015_ENTITY_ROLE_48",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinnost prvku pro Rukopisy v inv"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_RKP") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV nebo KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        "ZP2015_ENTITY_ROLE" ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro Rukopisy v inv (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_RKP") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV nebo KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        "ZP2015_ENTITY_ROLE" ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Povinnost prvku pro Rukopisy v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_RKP") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV nebo KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        "ZP2015_ENTITY_ROLE" ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinné role entit pro Rukopisy v INV"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_RKP") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři textu
        "ZP2015_ENTITY_ROLE_11",
        // tvůrci výtvarné stránky 
        "ZP2015_ENTITY_ROLE_39"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro Rukopisy v INV (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_RKP") ) from $ownItems
    not DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_HDB") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři textu
        "ZP2015_ENTITY_ROLE_11",
        // tvůrci výtvarné stránky 
        "ZP2015_ENTITY_ROLE_39"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

// Povinné role entit pro Rukopisy v KAT
rule "Povinné role entit pro Rukopisy v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_RKP") ) from $ownItems
    not DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_HDB") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři textu
        "ZP2015_ENTITY_ROLE_11",
        // objednatelé / příjemci
        "ZP2015_ENTITY_ROLE_19",
        // tvůrci výtvarné stránky 
        "ZP2015_ENTITY_ROLE_39",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
		// místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"       
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Hudebniny
//----------------------------------------------

rule "Možné role entit pro Hudebniny"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_HDB") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé / nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // autoři hudební složky
        "ZP2015_ENTITY_ROLE_5",
        // autoři textové složky
        "ZP2015_ENTITY_ROLE_10",
        // autoři doprovodných textů
        "ZP2015_ENTITY_ROLE_3",
        // objednatelé / příjemci 
        "ZP2015_ENTITY_ROLE_19",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro Hudebniny v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_HDB") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři hudební složky
        "ZP2015_ENTITY_ROLE_5",
        // autoři textové složky
        "ZP2015_ENTITY_ROLE_10",        
        // objednatelé / příjemci 
        "ZP2015_ENTITY_ROLE_19",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro Hudebniny v INV (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_HDB") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři hudební složky
        "ZP2015_ENTITY_ROLE_5",
        // autoři textové složky
        "ZP2015_ENTITY_ROLE_10",        
        // objednatelé / příjemci 
        "ZP2015_ENTITY_ROLE_19",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

// Povinné role entit pro Hudebniny v KAT
rule "Povinné role entit pro Hudebniny v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_HDB") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé / nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // autoři hudební složky
        "ZP2015_ENTITY_ROLE_5",
        // autoři textové složky
        "ZP2015_ENTITY_ROLE_10",        
        // autoři doprovodných textů
        "ZP2015_ENTITY_ROLE_3",
        // objednatelé / příjemci 
        "ZP2015_ENTITY_ROLE_19",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
		// místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"       
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//-------
// Typáře
//-------

// Možné prvky pro Typáře (vždy)
rule "Možné prvky pro Typáře (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_PEC", "ZP2015_UNIT_TYPE_RAZ",
        "ZP2015_UNIT_TYPE_OTD", "ZP2015_UNIT_TYPE_OTC"
        ) ) from $ownItems
    $itemType: RulItemTypeExt( code in (
        // ZP5.7.1 Opis, nápis, exerque
        "ZP2015_EXERQUE",
        // ZP5.7.2 Popis obrazu v poli typáře či otisku
        "ZP2015_PAINTING_CHAR",
        // ZP5.7.3 Koroborace dokumentu, k němuž byl popisovaný otisk připojen
        "ZP2015_CORROBORATION",
        // ZP5.7.4 Počet otisků původní a současný
        "ZP2015_IMPRINT_COUNT",
        // ZP5.7.5 Pořadí otisku,
        "ZP2015_IMPRINT_ORDER"
        ) )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Povolení vybraných jiných datací (ZP2015_DATE_OTHER) pro typáře"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PFP") ) from $ownItems
    $itemType : RulItemTypeExt(code == "ZP2015_DATE_OTHER")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_DATE_USAGE")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Možné role entit pro typáře
rule "Možné role entit pro typáře"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_PEC", "ZP2015_UNIT_TYPE_RAZ") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37",
        // výrobce
        "ZP2015_ENTITY_ROLE_53",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Možné role entit pro otisky
rule "Možné role entit pro otisky"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_OTD" ) ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vydání
        "ZP2015_ENTITY_ROLE_58"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Možné role entit pro kopie otisků
rule "Možné role entit pro kopie otisků"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_OTC" ) ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37",
        // výrobce
        "ZP2015_ENTITY_ROLE_53",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinnost prvku pro typáře a kopie otisků v inv (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
                   "ZP2015_UNIT_TYPE_PEC", "ZP2015_UNIT_TYPE_RAZ", "ZP2015_UNIT_TYPE_OTC"
    ) ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.10 Jazyk, písmo
        "ZP2015_LANGUAGE",
        "ZP2015_ENTITY_ROLE" 
    ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro otisky v inv (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
                   "ZP2015_UNIT_TYPE_OTD"
    ) ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.3 Způsob a forma dochování
        "ZP2015_STORAGE_COND",
        // ZP5.2.10 Jazyk, písmo
        "ZP2015_LANGUAGE",
        "ZP2015_ENTITY_ROLE" 
    ) )
then
  $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro otisky v inv (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
                   "ZP2015_UNIT_TYPE_OTD"
    ) ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.3 Způsob a forma dochování
        "ZP2015_STORAGE_COND",
        // ZP5.2.10 Jazyk, písmo
        "ZP2015_LANGUAGE",
        "ZP2015_ENTITY_ROLE" 
    ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Povinnost prvku pro pečetidla, razítka v kat (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
                   "ZP2015_UNIT_TYPE_PEC", "ZP2015_UNIT_TYPE_RAZ"
    ) ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.7.1 Opis, nápis, exerque
        "ZP2015_EXERQUE",
        // ZP5.7.2 Popis obrazu v poli typáře či otisku
        "ZP2015_PAINTING_CHAR",
        "ZP2015_ENTITY_ROLE"        
    ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro pečetidla, razítka v kat (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
                   "ZP2015_UNIT_TYPE_PEC", "ZP2015_UNIT_TYPE_RAZ"
    ) ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.7.1 Opis, nápis, exerque
        "ZP2015_EXERQUE",
        // ZP5.7.2 Popis obrazu v poli typáře či otisku
        "ZP2015_PAINTING_CHAR",
        "ZP2015_ENTITY_ROLE"        
    ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Povinnost prvku pro samostatné pečetě a kopie otisků v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
                   "ZP2015_UNIT_TYPE_OTD", "ZP2015_UNIT_TYPE_OTC"
    ) ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.7.1 Opis, nápis, exerque
        "ZP2015_EXERQUE",
        // ZP5.7.2 Popis obrazu v poli typáře či otisku
        "ZP2015_PAINTING_CHAR",
        // ZP5.7.3 Koroborace dokumentu, k němuž byl popisovaný otisk připojen
        "ZP2015_CORROBORATION",
        // ZP5.7.5 Pořadí otisku,
        "ZP2015_IMPRINT_ORDER",
        "ZP2015_ENTITY_ROLE" 
    ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinné role entit pro typáře v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_PEC", "ZP2015_UNIT_TYPE_RAZ") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro typáře v INV (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_PEC", "ZP2015_UNIT_TYPE_RAZ") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

// Povinné role entit pro typáře v KAT
rule "Povinné role entit pro typáře v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_PEC", "ZP2015_UNIT_TYPE_RAZ") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37",
        // výrobce
        "ZP2015_ENTITY_ROLE_53",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro otisky v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_OTD") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro otisky v INV (část jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_OTD") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

// Povinné role entit pro otisky v KAT
rule "Povinné role entit pro otisky v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_OTD") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro kopie otisků v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_OTC") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro kopie otisků v INV (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_OTC") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

// Povinné role entit pro kopie otisků v KAT
rule "Povinné role entit pro kopie otisků v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in (
        "ZP2015_UNIT_TYPE_OTC") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // majitelé typářů
        "ZP2015_ENTITY_ROLE_37",
        // výrobce
        "ZP2015_ENTITY_ROLE_53",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Mapy
//----------------------------------------------

// Možné prvky pro mapy (vždy)
rule "Možné prvky pro mapy (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $ownItems
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        "ZP2015_SCALE", "ZP2015_POSITION",
        "ZP2015_ORIENTATION") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Povolení vybraných jiných datací (ZP2015_DATE_OTHER) pro mapy"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $ownItems
    $itemType : RulItemTypeExt(code == "ZP2015_DATE_OTHER")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_DATE_MAP_UPDATE")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinnost prvku pro mapy v inv (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV nebo KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        "ZP2015_SCALE", "ZP2015_POSITION", "ZP2015_ENTITY_ROLE" ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro mapy v inv (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV nebo KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        "ZP2015_SCALE", "ZP2015_POSITION", "ZP2015_ENTITY_ROLE" ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Povinnost prvku pro mapy v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV nebo KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        "ZP2015_SCALE", "ZP2015_POSITION", "ZP2015_ENTITY_ROLE" ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// Možné role entit pro mapy (vždy)
rule "Možné role entit pro mapy (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé/nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // objednatelé/příjemci
        "ZP2015_ENTITY_ROLE_19",
        // kartografové
        "ZP2015_ENTITY_ROLE_33",
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // redaktoři
        "ZP2015_ENTITY_ROLE_32",
        // editoři
        "ZP2015_ENTITY_ROLE_34",
        // kresliči
        "ZP2015_ENTITY_ROLE_36",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro mapy v INV"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé/nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // kartografové
        "ZP2015_ENTITY_ROLE_33"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro mapy v INV (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé/nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // kartografové
        "ZP2015_ENTITY_ROLE_33"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

// Povinné role entit pro mapy v KAT
rule "Povinné role entit pro mapy v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_MAP", "ZP2015_UNIT_TYPE_ATL") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé/nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // objednatelé/příjemci
        "ZP2015_ENTITY_ROLE_19",
        // kartografové
        "ZP2015_ENTITY_ROLE_33",
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // redaktoři
        "ZP2015_ENTITY_ROLE_32",
        // editoři
        "ZP2015_ENTITY_ROLE_34",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
		// místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"        
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end


//----------------------------------------------
// Technické výkresy
//----------------------------------------------

// Možné prvky pro technické výkresy (vždy)
rule "Možné prvky pro technické výkresy (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $ownItems
    $itemType: RulItemTypeExt( code in ("ZP2015_SCALE", "ZP2015_POSITION", 
        "ZP2015_ORIENTATION") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Povinnost prvku pro technické výkresy v inv (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV nebo KAT 
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ("ZP2015_SCALE", "ZP2015_ENTITY_ROLE"    ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro technické výkresy v inv (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV nebo KAT 
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ("ZP2015_SCALE", "ZP2015_ENTITY_ROLE"    ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Povinnost prvku pro technické výkresy v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV nebo KAT 
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ("ZP2015_SCALE", "ZP2015_ENTITY_ROLE"    ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end
// Možné role entit pro technické výkresy (vždy)
rule "Možné role entit pro technické výkresy (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // objednatelé/příjemci 
        "ZP2015_ENTITY_ROLE_19",
        // autor
        "ZP2015_ENTITY_ROLE_1",
        // schvalovatelé
        "ZP2015_ENTITY_ROLE_25",
        // stavitelé
        "ZP2015_ENTITY_ROLE_26",
        // výrobci
        "ZP2015_ENTITY_ROLE_53",
        // kresliči
        "ZP2015_ENTITY_ROLE_36",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62",
        // typová označení a názvy výrobků a typových staveb
        "ZP2015_ENTITY_ROLE_63"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro technické výkresy v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // autor
        "ZP2015_ENTITY_ROLE_1", 
        // objednatelé/příjemci 
        "ZP2015_ENTITY_ROLE_19",
        // typová označení a názvy výrobků a typových staveb
        "ZP2015_ENTITY_ROLE_63"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end


rule "Povinné role entit pro technické výkresy v INV (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // autor
        "ZP2015_ENTITY_ROLE_1",
        // objednatelé/příjemci 
        "ZP2015_ENTITY_ROLE_19",
        // typová označení a názvy výrobků a typových staveb
        "ZP2015_ENTITY_ROLE_63"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

// Povinné role entit pro technické výkresy v KAT
rule "Povinné role entit pro technické výkresy v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TVY") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autor
        "ZP2015_ENTITY_ROLE_1",
        // objednatelé/příjemci 
        "ZP2015_ENTITY_ROLE_19",
        // schvalovatelé
        "ZP2015_ENTITY_ROLE_25",
        // stavitelé
        "ZP2015_ENTITY_ROLE_26",
        // výrobci
        "ZP2015_ENTITY_ROLE_53",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
		// místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62",        
        // typová označení a názvy výrobků a typových staveb
        "ZP2015_ENTITY_ROLE_63"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end


//----------------------------------------------
// Grafické listy a kresby
//----------------------------------------------

// Možné prvky pro Grafické listy a kresby (vždy)
rule "Možné prvky pro Grafické listy a kresby (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_GLI", "ZP2015_UNIT_TYPE_KRE") ) from $ownItems
    $itemType: RulItemTypeExt( code in (
        // ZP5.11.1 Legenda
        "ZP2015_LEGEND",
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",        
        // ZP5.2.6 Souřadnice - tvar a souřadnice
        "ZP2015_POSITION", 
        // ZP5.2.7 Orientace z hlediska světových stran
        "ZP2015_ORIENTATION") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Možné role entit pro Grafické listy a kresby (vždy)
rule "Možné role entit pro Grafické listy a kresby (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_GLI", "ZP2015_UNIT_TYPE_KRE") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé / nakladatelé 
        "ZP2015_ENTITY_ROLE_16",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",
        // tvůrci technického zpracování
        "ZP2015_ENTITY_ROLE_38",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinnost prvku pro Grafické listy a kresby v inv (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_GLI", "ZP2015_UNIT_TYPE_KRE") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",         
        "ZP2015_ENTITY_ROLE"    ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro Grafické listy a kresby v inv (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_GLI", "ZP2015_UNIT_TYPE_KRE") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",         
        "ZP2015_ENTITY_ROLE"    ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

// Povinnost prvku pro Grafické listy a kresby v kat
rule "Povinnost prvku pro Grafické listy a kresby v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_GLI", "ZP2015_UNIT_TYPE_KRE") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",
        // ZP5.11.1 Legenda
        "ZP2015_LEGEND",  "ZP2015_ENTITY_ROLE"  ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinné role entit Grafické listy a kresby v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_GLI", "ZP2015_UNIT_TYPE_KRE") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV 
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // tvůrci technického zpracování
        "ZP2015_ENTITY_ROLE_38",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39"        
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit Grafické listy a kresby v INV (část jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_GLI", "ZP2015_UNIT_TYPE_KRE") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV 
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // tvůrci technického zpracování
        "ZP2015_ENTITY_ROLE_38",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39"        
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

// Povinné role entit pro Grafické listy a kresby v KAT
rule "Povinné role entit Grafické listy a kresby v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_GLI", "ZP2015_UNIT_TYPE_KRE") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // vydavatelé / nakladatelé 
        "ZP2015_ENTITY_ROLE_16",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",
        // tvůrci technického zpracování
        "ZP2015_ENTITY_ROLE_38",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",        
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end


//----------------------------------------------
// Fotograficke archivalie
//----------------------------------------------

// Možné prvky pro fotograficky material (vždy)
rule "Možné prvky pro fotograficky material (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $ownItems
    $itemType: RulItemTypeExt( code in ("ZP2015_ORIENTATION",
        "ZP2015_POSITION") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// viz https://bugzilla.lightcomp.cz/show_bug.cgi?id=4683
/*
rule "Doporučené prvky pro fotograficky material v inv (složka)"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER") ) from $activeLevel.descItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
       // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
       "ZP2015_ITEM_MAT",
       "ZP2015_ENTITY_ROLE" ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end
*/

rule "Povinnost prvku pro fotograficky material v inv (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
       // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
       "ZP2015_ITEM_MAT",
       "ZP2015_ENTITY_ROLE" ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro fotograficky material v inv (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
       // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
       "ZP2015_ITEM_MAT",
       "ZP2015_ENTITY_ROLE" ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Povinnost prvku pro fotograficky material v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
        "ZP2015_ITEM_MAT",
       "ZP2015_ENTITY_ROLE"	) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end


rule "Možné role entit pro fotograficky material (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // fotograf
        "ZP2015_ENTITY_ROLE_31",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",
        // odesílatelé
        "ZP2015_ENTITY_ROLE_24",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro fotograficky material v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // fotograf
        "ZP2015_ENTITY_ROLE_31",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro fotograficky material v INV (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // fotograf
        "ZP2015_ENTITY_ROLE_31",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

// Povinné role entit pro fotograficky material v KAT
rule "Povinné role entit pro fotograficky material v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_FSN", "ZP2015_UNIT_TYPE_FSD",
    "ZP2015_UNIT_TYPE_LFI", "ZP2015_UNIT_TYPE_SFI", "ZP2015_UNIT_TYPE_KIN", "ZP2015_UNIT_TYPE_MF", "ZP2015_UNIT_TYPE_MFS",
    "ZP2015_UNIT_TYPE_FAL", "ZP2015_UNIT_TYPE_DFO") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems )
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // fotograf
        "ZP2015_ENTITY_ROLE_31",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",
        // odesílatelé
        "ZP2015_ENTITY_ROLE_24",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61"
        // místa vzniku předloh popisovaných kopií
        //"ZP2015_ENTITY_ROLE_62"      
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Kinematografické filmy
//----------------------------------------------

rule "Možné prvky pro Kinematografické filmy (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_KZA") ) from $ownItems
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",
        // ZP5.13.1 Délka filmového záznamu
        "ZP2015_MOVIE_LENGTH") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Povolení vybraných jiných datací (ZP2015_DATE_OTHER) pro Kinematografické filmy"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_KZA") ) from $ownItems
    $itemType : RulItemTypeExt(code == "ZP2015_DATE_OTHER")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_DATE_RECORDING")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

// Odstraneno, viz https://bugzilla.lightcomp.cz/show_bug.cgi?id=4683
/*
rule "Doporučené prvky pro Kinematografické filmy v inv (složka)"
no-loop
salience -100
when $activeLevel: ActiveLevel( )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_KZA") ) from $activeLevel.descItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_FOLDER") ) from $activeLevel.descItems
    // Rodic je INV 
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
        "ZP2015_ITEM_MAT", 
        // ZP5.13.1 Délka filmového záznamu
        "ZP2015_MOVIE_LENGTH",
        "ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end
*/

rule "Povinnost prvku pro Kinematografické filmy v inv (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_KZA") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems    
    // Rodic je INV 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
        "ZP2015_ITEM_MAT", 
        // ZP5.13.1 Délka filmového záznamu
        "ZP2015_MOVIE_LENGTH",
        "ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro Kinematografické filmy v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_KZA") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        // ZP5.13.1 Délka filmového záznamu
        "ZP2015_MOVIE_LENGTH",
        "ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Možné role entit pro Kinematografické filmy (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_KZA") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // produkční společnosti/producenti 
        "ZP2015_ENTITY_ROLE_18",
        // objednatelé / příjemci
        "ZP2015_ENTITY_ROLE_19",
        // distributoři
        "ZP2015_ENTITY_ROLE_20",
        // režiséři
        "ZP2015_ENTITY_ROLE_27",
        // scénáristé
        "ZP2015_ENTITY_ROLE_28",
        // kameramani
        "ZP2015_ENTITY_ROLE_29",
        // autoři námětů
        "ZP2015_ENTITY_ROLE_9",
        // autoři dialogů
        "ZP2015_ENTITY_ROLE_2",
        // autoři hudby
        "ZP2015_ENTITY_ROLE_6",
        // autoři komentářů
        "ZP2015_ENTITY_ROLE_8",
        // autoři choreografií
        "ZP2015_ENTITY_ROLE_7",
        // autoři triků a speciálních efektů
        "ZP2015_ENTITY_ROLE_12",
        // interpreti hudby
        "ZP2015_ENTITY_ROLE_30",
        // tvůrci výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // dramaturgové
        "ZP2015_ENTITY_ROLE_40",
        // střih
        "ZP2015_ENTITY_ROLE_41",
        // zvuk
        "ZP2015_ENTITY_ROLE_42",
        // účinkující
        "ZP2015_ENTITY_ROLE_43",
        // překladatelé
        "ZP2015_ENTITY_ROLE_44",
        // zpracovatelé nosičů záznamů
        "ZP2015_ENTITY_ROLE_49",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // místa vzniku záznamů
        "ZP2015_ENTITY_ROLE_56",
        // místa výroby jednotek popisu
        "ZP2015_ENTITY_ROLE_60"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro Kinematografické filmy v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_KZA") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // produkční společnosti/producenti 
        "ZP2015_ENTITY_ROLE_18",
        // režiséři
        "ZP2015_ENTITY_ROLE_27",
        // scénáristé
        "ZP2015_ENTITY_ROLE_28",
        // kameramani
        "ZP2015_ENTITY_ROLE_29",
        // autoři námětů
        "ZP2015_ENTITY_ROLE_9",
        // autoři dialogů
        "ZP2015_ENTITY_ROLE_2",
        // autoři hudby
        "ZP2015_ENTITY_ROLE_6"
        ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Povinné role entit pro Kinematografické filmy v KAT
rule "Povinné role entit pro Kinematografické filmy v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_KZA") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // produkční společnosti/producenti 
        "ZP2015_ENTITY_ROLE_18",
        // objednatelé / příjemci
        "ZP2015_ENTITY_ROLE_19",
        // distributoři
        "ZP2015_ENTITY_ROLE_20",
        // režiséři
        "ZP2015_ENTITY_ROLE_27",
        // scénáristé
        "ZP2015_ENTITY_ROLE_28",
        // kameramani
        "ZP2015_ENTITY_ROLE_29",
        // autoři námětů
        "ZP2015_ENTITY_ROLE_9",
        // autoři dialogů
        "ZP2015_ENTITY_ROLE_2",
        // autoři hudby
        "ZP2015_ENTITY_ROLE_6",
        // autoři komentářů
        "ZP2015_ENTITY_ROLE_8",
        // autoři choreografií
        "ZP2015_ENTITY_ROLE_7",
        // autoři triků a speciálních efektů
        "ZP2015_ENTITY_ROLE_12",
        // interpreti hudby
        "ZP2015_ENTITY_ROLE_30",
        // tvůrci výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // dramaturgové
        "ZP2015_ENTITY_ROLE_40",
        // střih
        "ZP2015_ENTITY_ROLE_41",
        // zvuk
        "ZP2015_ENTITY_ROLE_42",
        // účinkující
        "ZP2015_ENTITY_ROLE_43",
        // překladatelé
        "ZP2015_ENTITY_ROLE_44",
        // zpracovatelé nosičů záznamů
        "ZP2015_ENTITY_ROLE_49",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // místa vzniku záznamů
        "ZP2015_ENTITY_ROLE_56",
        // místa výroby jednotek popisu
        "ZP2015_ENTITY_ROLE_60"
        ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Zvukové archiválie
//----------------------------------------------

rule "Možné prvky pro Zvukové záznamy (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_ZZA") ) from $ownItems
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",
        // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
        "ZP2015_ITEM_MAT", 
        // ZP5.14.1 Délka zvukového záznamu
        "ZP2015_RECORD_LENGTH") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Povolení vybraných jiných datací (ZP2015_DATE_OTHER) pro Zvukové záznamy"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_ZZA") ) from $ownItems
    $itemType : RulItemTypeExt(code == "ZP2015_DATE_OTHER")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_DATE_RECORDING")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinnost prvku pro Zvukové záznamy v inv"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_ZZA") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        // ZP5.2.8 Technika, adjustace, nosič a látka záznamu
        "ZP2015_ITEM_MAT", 
        // ZP5.14.1 Délka zvukového záznamu
        "ZP2015_RECORD_LENGTH",
        "ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro Zvukové záznamy v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_ZZA") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",    
        // ZP5.14.1 Délka zvukového záznamu
        "ZP2015_RECORD_LENGTH",
        "ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

// Možné role entit pro Zvukové záznamy (vždy)
rule "Možné role entit pro Zvukové záznamy (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_ZZA") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // produkční společnosti/producenti 
        "ZP2015_ENTITY_ROLE_18",
        // objednatelé / příjemci
        "ZP2015_ENTITY_ROLE_19",
        // distributoři
        "ZP2015_ENTITY_ROLE_20",
        // režiséři
        "ZP2015_ENTITY_ROLE_27",
        // scénáristé
        "ZP2015_ENTITY_ROLE_28",
        // autoři námětů
        "ZP2015_ENTITY_ROLE_9",
        // autoři dialogů
        "ZP2015_ENTITY_ROLE_2",
        // autoři hudby
        "ZP2015_ENTITY_ROLE_6",
        // autoři komentářů
        "ZP2015_ENTITY_ROLE_8",
        // autoři triků a speciálních efektů
        "ZP2015_ENTITY_ROLE_12",
        // interpreti hudby
        "ZP2015_ENTITY_ROLE_30",
        // tvůrci výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // dramaturgové
        "ZP2015_ENTITY_ROLE_40",
        // střih
        "ZP2015_ENTITY_ROLE_41",
        // zvuk
        "ZP2015_ENTITY_ROLE_42",
        // účinkující
        "ZP2015_ENTITY_ROLE_43",
        // překladatelé
        "ZP2015_ENTITY_ROLE_44",
        // zpracovatelé nosičů záznamů
        "ZP2015_ENTITY_ROLE_49",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // místa vzniku záznamů
        "ZP2015_ENTITY_ROLE_56",
        // místa výroby jednotek popisu
        "ZP2015_ENTITY_ROLE_60"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end


// Povinné role entit pro Zvukové záznamy v INV
rule "Povinné role entit pro Zvukové záznamy v INV"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_ZZA") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // produkční společnosti/producenti 
        "ZP2015_ENTITY_ROLE_18",
        // režiséři
        "ZP2015_ENTITY_ROLE_27",
        // scénáristé
        "ZP2015_ENTITY_ROLE_28",
        // autoři námětů
        "ZP2015_ENTITY_ROLE_9",
        // autoři dialogů
        "ZP2015_ENTITY_ROLE_2",
        // autoři hudby
        "ZP2015_ENTITY_ROLE_6"
        ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

// Povinné role entit pro Zvukové záznamy v KAT
rule "Povinné role entit pro Zvukové záznamy v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_ZZA") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // produkční společnosti/producenti 
        "ZP2015_ENTITY_ROLE_18",
        // objednatelé / příjemci
        "ZP2015_ENTITY_ROLE_19",
        // distributoři
        "ZP2015_ENTITY_ROLE_20",
        // režiséři
        "ZP2015_ENTITY_ROLE_27",
        // scénáristé
        "ZP2015_ENTITY_ROLE_28",
        // autoři námětů
        "ZP2015_ENTITY_ROLE_9",
        // autoři dialogů
        "ZP2015_ENTITY_ROLE_2",
        // autoři hudby
        "ZP2015_ENTITY_ROLE_6",
        // autoři komentářů
        "ZP2015_ENTITY_ROLE_8",
        // autoři triků a speciálních efektů
        "ZP2015_ENTITY_ROLE_12",
        // interpreti hudby
        "ZP2015_ENTITY_ROLE_30",
        // tvůrci výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // dramaturgové
        "ZP2015_ENTITY_ROLE_40",
        // střih
        "ZP2015_ENTITY_ROLE_41",
        // zvuk
        "ZP2015_ENTITY_ROLE_42",
        // účinkující
        "ZP2015_ENTITY_ROLE_43",
        // překladatelé
        "ZP2015_ENTITY_ROLE_44",
        // zpracovatelé nosičů záznamů
        "ZP2015_ENTITY_ROLE_49",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // místa vzniku záznamů
        "ZP2015_ENTITY_ROLE_56",
        // místa výroby jednotek popisu
        "ZP2015_ENTITY_ROLE_60"
        ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Tisky
//----------------------------------------------

rule "Možné prvky pro tisky (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $ownItems
	$itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF") )
then
	$itemType.setType(RulItemType.Type.POSSIBLE);
end

rule "Povinnost prvku pro tisky v inv (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
	// Rodic je INV nebo KAT 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",
	    "ZP2015_ENTITY_ROLE") )
then
	$itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro tisky v inv (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
	// Rodic je INV nebo KAT 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",
	    "ZP2015_ENTITY_ROLE") )
then
	$itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Povinnost prvku pro tisky v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
	// Rodic je INV nebo KAT 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in (
        // ZP5.2.2 Název autorského díla
        "ZP2015_ITEM_TITLE_REF",
	    "ZP2015_ENTITY_ROLE") )
then
	$itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Možné role entit pro tisky (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $ownItems
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in (
		// vydavatelé/nakladatelé 
		"ZP2015_ENTITY_ROLE_16",
		// příjemci 
		"ZP2015_ENTITY_ROLE_21",		
		// autoři textu
		"ZP2015_ENTITY_ROLE_11",
		// fotografové
		"ZP2015_ENTITY_ROLE_31",
        // redaktor
        "ZP2015_ENTITY_ROLE_32",		
		// kartografové
		"ZP2015_ENTITY_ROLE_33",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",		
		// překladatelé
		"ZP2015_ENTITY_ROLE_44",
		// lektoři
		"ZP2015_ENTITY_ROLE_45",
		// výrobci nosičů záznamů
		"ZP2015_ENTITY_ROLE_50",
		// tiskárny/tiskaři
		"ZP2015_ENTITY_ROLE_52",
		// místa vydání
		"ZP2015_ENTITY_ROLE_58",
		// místa vzniku předloh popisovaných kopií
		"ZP2015_ENTITY_ROLE_62"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro tisky v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
	// Rodic je INV 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// vydavatelé/nakladatelé 
		"ZP2015_ENTITY_ROLE_16",
		// autoři textu
		"ZP2015_ENTITY_ROLE_11",
		// místa vydání
		"ZP2015_ENTITY_ROLE_58",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro tisky v INV (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
	// Rodic je INV 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// vydavatelé/nakladatelé 
		"ZP2015_ENTITY_ROLE_16",
		// autoři textu
		"ZP2015_ENTITY_ROLE_11",
		// místa vydání
		"ZP2015_ENTITY_ROLE_58",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

rule "Povinné role entit pro tisky v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_TIO", "ZP2015_UNIT_TYPE_TIP") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
	// Rodic je KAT 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// vydavatelé/nakladatelé 
		"ZP2015_ENTITY_ROLE_16",
		// příjemci 
		"ZP2015_ENTITY_ROLE_21",		
		// autoři textu
		"ZP2015_ENTITY_ROLE_11",
		// fotografové
		"ZP2015_ENTITY_ROLE_31",
        // redaktor
        "ZP2015_ENTITY_ROLE_32",		
		// kartografové
		"ZP2015_ENTITY_ROLE_33",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",		
		// překladatelé
		"ZP2015_ENTITY_ROLE_44",
		// lektoři
		"ZP2015_ENTITY_ROLE_45",
		// výrobci nosičů záznamů
		"ZP2015_ENTITY_ROLE_50",
		// tiskárny/tiskaři
		"ZP2015_ENTITY_ROLE_52",
		// místa vydání
		"ZP2015_ENTITY_ROLE_58",
		// místa vzniku předloh popisovaných kopií
		"ZP2015_ENTITY_ROLE_62"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.REQUIRED);
end


//----------------------------------------------
// Pohlednice
//----------------------------------------------

rule "Možné prvky pro Pohlednice (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_POH") ) from $ownItems
    $itemType: RulItemTypeExt( code in (
        // ZP5.2.6 Souřadnice - tvar a souřadnice
        "ZP2015_POSITION",
        // ZP5.2.7 Orientace z hlediska světových stran
        "ZP2015_ORIENTATION") )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end

// Povinnost prvku pro Pohlednice v kat
rule "Povinnost prvku pro Pohlednice v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_POH") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Možné role entit pro Pohlednice (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_POH") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé / nakladatelé 
        "ZP2015_ENTITY_ROLE_16",
        // odesilatelé
        "ZP2015_ENTITY_ROLE_24",        
        // příjemci
        "ZP2015_ENTITY_ROLE_21",
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vydání
        "ZP2015_ENTITY_ROLE_58",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro Pohlednice v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_POH") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // vydavatelé / nakladatelé 
        "ZP2015_ENTITY_ROLE_16",
        // odesilatelé
        "ZP2015_ENTITY_ROLE_24",        
        // příjemci
        "ZP2015_ENTITY_ROLE_21",
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vydání
        "ZP2015_ENTITY_ROLE_58",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"     
        ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Plakáty
//----------------------------------------------

rule "Povinnost prvku pro Plakáty v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PKT") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Možné role entit pro Plakáty (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PKT") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé / nakladatelé 
        "ZP2015_ENTITY_ROLE_16",
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",        
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",        
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vydání
        "ZP2015_ENTITY_ROLE_58",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro Plakáty v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PKT") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // vydavatelé / nakladatelé 
        "ZP2015_ENTITY_ROLE_16",
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",        
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",        
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vydání
        "ZP2015_ENTITY_ROLE_58",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
        ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Štočky
//----------------------------------------------

// Povinnost prvku pro Štočky v kat
rule "Povinnost prvku pro Štočky v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_STO") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Možné role entit pro Štočky (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_STO") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé / nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",        
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // kartografové
        "ZP2015_ENTITY_ROLE_33",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro Štočky v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_STO") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // vydavatelé / nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",        
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // kartografové
        "ZP2015_ENTITY_ROLE_33",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
        ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end


//----------------------------------------------
// Cenné papíry
//----------------------------------------------

rule "Povinnost prvku pro cenné papíry v inv (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
	// Rodic je INV nebo KAT 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
	$itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro cenné papíry v inv (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
	// Rodic je INV nebo KAT 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
	$itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Povinnost prvku pro cenné papíry v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
	// Rodic je INV nebo KAT 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
	$itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Možné role entit pro cenné papíry (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $ownItems
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in (
		// vydavatelé 
		"ZP2015_ENTITY_ROLE_15",
		// držitelé
		"ZP2015_ENTITY_ROLE_23",		
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
		// tiskárna/tiskař
		"ZP2015_ENTITY_ROLE_52",
		// místa vydání
		"ZP2015_ENTITY_ROLE_58",
		// místa vzniku předloh popisovaných kopií
		"ZP2015_ENTITY_ROLE_62"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro cenné papíry v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
	// Rodic je INV 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// vydavatelé 
		"ZP2015_ENTITY_ROLE_15"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro cenné papíry v INV (část jednotlivosti)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_PART") ) from $ownItems
	// Rodic je INV 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// vydavatelé 
		"ZP2015_ENTITY_ROLE_15"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end

// Povinné role entit pro cenné papíry v KAT
rule "Povinné role entit pro cenné papíry v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
	DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_CPA") ) from $ownItems
	DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
	// Rodic je KAT 
	Level( $items: descItems ) 
	DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
	// nastaveni prvku	
	$itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
	$itemSpec: RulItemSpecExt( code in ( 
		// vydavatelé 
		"ZP2015_ENTITY_ROLE_15",
		// držitelé
		"ZP2015_ENTITY_ROLE_23",		
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
		// tiskárna/tiskař
		"ZP2015_ENTITY_ROLE_52",
		// místa vydání
		"ZP2015_ENTITY_ROLE_58",
		// místa vzniku předloh popisovaných kopií
		"ZP2015_ENTITY_ROLE_62"
	 ) ) from $itemType.rulItemSpecList
then
	$itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Faleristické předměty
//----------------------------------------------

rule "Povolení vybraných jiných datací (ZP2015_DATE_OTHER) pro předmět faler povahy"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PFP") ) from $ownItems
    $itemType : RulItemTypeExt(code == "ZP2015_DATE_OTHER")
    $itemSpec : RulItemSpecExt(code in ("ZP2015_DATE_AWARDING",
    	"ZP2015_DATE_AWARD_CER", "ZP2015_DATE_WITHDRAWAL")) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end


rule "Povinnost prvku pro Faleristické předměty v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PFP") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV nebo KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Povinnost prvku pro Faleristické předměty v kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PFP") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV nebo KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Možné role entit pro Faleristické předměty (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PFP") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",        
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // výrobci
        "ZP2015_ENTITY_ROLE_53",
        // místa vydavatelů
        "ZP2015_ENTITY_ROLE_57",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro Faleristické předměty v INV (jednotlivost)"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PFP") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM") ) from $ownItems
    // Rodic je INV
    Level( $items: descItems ) 
    not(DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_STV") ) from $items)
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // příjemci
        "ZP2015_ENTITY_ROLE_21"        
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro Faleristické předměty v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PFP") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    not(DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_STV") ) from $items)
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",        
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // výrobci
        "ZP2015_ENTITY_ROLE_53",
        // místa vydavatelů
        "ZP2015_ENTITY_ROLE_57",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//-----------------
// Státní vyznamenání
//-----------------

rule "Doporučené prvky pro podtyp státní vyznamenání"
no-loop
when $activeLevel: ActiveLevel( $items: descItems )
    DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_STV") ) from $items
    $itemType: RulItemTypeExt( code in (
    	"ZP2015_AWARD_LEVEL",
    	"ZP2015_AWARD_GROUP",
        "ZP2015_DATE_OTHER",
        "ZP2015_OTHER_ID"
       ) )
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
end

rule "Doporučené specifikace pro podtyp státní vyznamenání"
no-loop
when $activeLevel: ActiveLevel( $items: descItems )
    $itemType: RulItemTypeExt( code in (
        "ZP2015_DATE_OTHER",
        "ZP2015_OTHER_ID"))
    $itemSpec: RulItemSpecExt( code in ( 
        "ZP2015_OTHERID_MATRIXID",
        "ZP2015_DATE_AWARDING"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.RECOMMENDED);
end


rule "Možné specifikace pro podtyp státní vyznamenání"
no-loop
when $activeLevel: ActiveLevel( $items: descItems )
    $itemType: RulItemTypeExt( code in (
    	"ZP2015_AWARD_LEVEL", 
        "ZP2015_DATE_OTHER"
       ) )
    $itemSpec: RulItemSpecExt( code in ( 
        "ZP2015_AWARD_LEVEL_CLASS",
        "ZP2015_AWARD_LEVEL_DEGREE",         
        "ZP2015_DATE_AWARD_CER",
        "ZP2015_DATE_WITHDRAWAL"       
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end


rule "Možné role entit pro státní vyznamenání (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_STV") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // nositel státního vyznamenání / ceny
        "ZP2015_ENTITY_ROLE_74",
        // navrhovatel
        "ZP2015_ENTITY_ROLE_75",
        // předávající
        "ZP2015_ENTITY_ROLE_76"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end


rule "Povinné prvky pro podtyp státní vyznamenání (inventář, katalog)"
salience -100
no-loop
when $activeLevel: ActiveLevel( $items: descItems )
    DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_STV") ) from $items
    // Rodic je INV
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT")) from $items
    $itemType: RulItemTypeExt( code in (
    	"ZP2015_AWARD_LEVEL",
    	"ZP2015_AWARD_GROUP",
        "ZP2015_DATE_OTHER"
       ) )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end


rule "Povinné role entit pro státní vyznamenání (inventář, katalog)"
salience -100
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    // Rodic je INV
    Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT")) from $items
    DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_STV") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // státní vyznamenání / cena
        "ZP2015_ENTITY_ROLE_73",
        // nositel státního vyznamenání / ceny
        "ZP2015_ENTITY_ROLE_74"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Numizmatické předměty
//----------------------------------------------

rule "Povinnost prvku pro Numizmatické předměty v inv a kat"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PNP") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV nebo KAT 
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV", "ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

rule "Možné role entit pro Numizmatické předměty (vždy)"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PNP") ) from $ownItems    
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",        
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // výrobci
        "ZP2015_ENTITY_ROLE_53",
        // místa výroby jednotek popisu
        "ZP2015_ENTITY_ROLE_60",
        // místa vydavatelů
        "ZP2015_ENTITY_ROLE_57",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinné role entit pro Numizmatické předměty v INV"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PNP") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_INV")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

rule "Povinné role entit pro Numizmatické předměty v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_PNP") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je KAT 
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in ( 
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",        
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // výrobci
        "ZP2015_ENTITY_ROLE_53",
        // místa výroby jednotek popisu
        "ZP2015_ENTITY_ROLE_60",
        // místa vydavatelů
        "ZP2015_ENTITY_ROLE_57",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.REQUIRED);
end

//----------------------------------------------
// Jiné a neevid. jednotlivost
//----------------------------------------------

rule "Možné role entit pro jiné jednotlivosti"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_JIN") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // vydavatelé / nakladatelé
        "ZP2015_ENTITY_ROLE_16",        
        // pečetitelé
        "ZP2015_ENTITY_ROLE_17",
        // objednatelé / příjemci
        "ZP2015_ENTITY_ROLE_19",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",
        // žadatelé
        "ZP2015_ENTITY_ROLE_22",
        // odesilatelé
        "ZP2015_ENTITY_ROLE_24",
        // stavitelé
        "ZP2015_ENTITY_ROLE_26",
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // redaktor
        "ZP2015_ENTITY_ROLE_32",        
        // kartografové
        "ZP2015_ENTITY_ROLE_33",
        // kresliči
        "ZP2015_ENTITY_ROLE_36",
        // tvůrci technického zpracování
        "ZP2015_ENTITY_ROLE_38",
        // tvůrci výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",
        // překladatelé
        "ZP2015_ENTITY_ROLE_44",
        // svědci
        "ZP2015_ENTITY_ROLE_46",
        // ručitelé (rukojmě)
        "ZP2015_ENTITY_ROLE_47",
        // písaři
        "ZP2015_ENTITY_ROLE_48",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // výrobci
        "ZP2015_ENTITY_ROLE_53",
        // místa vydání
        "ZP2015_ENTITY_ROLE_58",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62",
        // typová označení a názvy výrobků a typových staveb
        "ZP2015_ENTITY_ROLE_63"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

rule "Povinnost prvku pro jiné jednotlivosti v KAT"
no-loop
salience -100
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_JIN") ) from $ownItems
    DescItem(type=="ZP2015_LEVEL_TYPE" && specCode in ("ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART") ) from $ownItems
    // Rodic je INV nebo KAT 
    $level: Level( $items: descItems ) 
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_KAT")) from $items
    // nastaveni prvku  
    $itemType: RulItemTypeExt( code in ("ZP2015_ENTITY_ROLE") )
then
    $itemType.setType(RulItemType.Type.REQUIRED);
end

//----------------------------------
// Neevidovaná jednotlivost
//----------------------------------

// Pridano na zaklade: https://bugzilla.lightcomp.cz/show_bug.cgi?id=6173
rule "Možné prvky popisu pro neevidované jednotlivosti ve starší pomůcce"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_OTHER") ) from $ownItems
    DescItem(type=="ZP2015_ARRANGEMENT_TYPE" && specCode in ("ZP2015_ARRANGEMENT_OTHER") ) from $activeLevel.descItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_IMPRINT_COUNT" ) )
then
    $itemType.setType(RulItemType.Type.POSSIBLE);
end


rule "Možné role entit pro neevidované jednotlivosti"
no-loop
when $activeLevel: ActiveLevel( $ownItems: ownDescItems )
    $descItem : DescItem(type=="ZP2015_UNIT_TYPE" && specCode in ("ZP2015_UNIT_TYPE_OTHER") ) from $ownItems
    $itemType: RulItemTypeExt( code in ( "ZP2015_ENTITY_ROLE" ) )
    $itemSpec: RulItemSpecExt( code in (
        // autoři textů
        "ZP2015_ENTITY_ROLE_11",        
        // vydavatelé
        "ZP2015_ENTITY_ROLE_15",
        // vydavatelé / nakladatelé
        "ZP2015_ENTITY_ROLE_16",
        // pečetitelé
        "ZP2015_ENTITY_ROLE_17",
        // příjemci
        "ZP2015_ENTITY_ROLE_21",
        // žadatelé
        "ZP2015_ENTITY_ROLE_22",
        // odesilatelé
        "ZP2015_ENTITY_ROLE_24",
        // fotografové
        "ZP2015_ENTITY_ROLE_31",
        // redaktor
        "ZP2015_ENTITY_ROLE_32",        
        // kartografové
        "ZP2015_ENTITY_ROLE_33",
        // tvůrce výtvarné stránky
        "ZP2015_ENTITY_ROLE_39",        
        // překladatelé
        "ZP2015_ENTITY_ROLE_44",
        // svědci
        "ZP2015_ENTITY_ROLE_46",
        // ručitelé (rukojmě)
        "ZP2015_ENTITY_ROLE_47",
        // písaři
        "ZP2015_ENTITY_ROLE_48",
        // výrobci nosičů záznamů
        "ZP2015_ENTITY_ROLE_50",
        // tiskárny/tiskaři
        "ZP2015_ENTITY_ROLE_52",
        // místa vydání
        "ZP2015_ENTITY_ROLE_58",
        // místa vzniku jednotek popisu
        "ZP2015_ENTITY_ROLE_61",
        // místa vzniku předloh popisovaných kopií
        "ZP2015_ENTITY_ROLE_62"
     ) ) from $itemType.rulItemSpecList
then
    $itemSpec.setType(RulItemSpec.Type.POSSIBLE);
end

//------------------------------
// Podtyp právní akt
//------------------------------

rule "Možné prvky pro podtyp právní akt"
no-loop
when $activeLevel: ActiveLevel( $items: descItems )
    DescItem(type=="ZP2015_UNIT_SUBTYPE" && specCode in ("ZP2015_UNIT_SUBTYPE_PA") ) from $items
    $itemType: RulItemTypeExt( code in (
        "ZP2015_LEGALACT_REF"
       ) )    
then
    $itemType.setType(RulItemType.Type.RECOMMENDED);
    $itemType.setRepeatable(true);
end
