package ZP2015;

import cz.tacr.elza.drools.model.DescItem;
import cz.tacr.elza.drools.model.DescItemChange;
import cz.tacr.elza.domain.vo.RelatedNodeDirection;
import cz.tacr.elza.domain.vo.NodeTypeOperation;

global java.util.Set results;

rule "Uzel se revaliduje při každé operaci"
when
then
	results.add(RelatedNodeDirection.NODE);
end

// ZP2015_STORAGE_ID - každá větev musí mít alespoň jeden obal
rule "Dopad na všechny potomky při změně: ZP2015_ARRANGEMENT_TYPE, ZP2015_LEVEL_TYPE, ZP2015_FOLDER_TYPE, ZP2015_STORAGE_ID"
when
    DescItem(type in ("ZP2015_ARRANGEMENT_TYPE", "ZP2015_LEVEL_TYPE", "ZP2015_FOLDER_TYPE", "ZP2015_STORAGE_ID" ))
	NodeTypeOperation(this==NodeTypeOperation.SAVE_DESC_ITEM)
then
	results.add(RelatedNodeDirection.DESCENDANTS);
end

// Při vytvoření uzlu se zneplatňuje rodič a sourozenec
rule "Vytvoření uzlu"
when
	NodeTypeOperation( this==NodeTypeOperation.CREATE_NODE )
then
	results.add(RelatedNodeDirection.PARENT);
	results.add(RelatedNodeDirection.SIBLINGS);
end

rule "Vymazání uzlu"
when
	NodeTypeOperation( this==NodeTypeOperation.DELETE_NODE )
then
	results.add(RelatedNodeDirection.PARENT);
	results.add(RelatedNodeDirection.SIBLINGS);
end

rule "Odpojení uzlu se stejným rodičem"
when
	NodeTypeOperation(this==NodeTypeOperation.DISCONNECT_NODE_LOCAL)
then
	results.add(RelatedNodeDirection.SIBLINGS);
end

rule "Připojení uzlu se stejným rodičem"
when
	NodeTypeOperation(this==NodeTypeOperation.CONNECT_NODE_LOCAL)
then
	results.add(RelatedNodeDirection.SIBLINGS);
end

rule "DisconnectNode"
when
	NodeTypeOperation(this==NodeTypeOperation.DISCONNECT_NODE)
then
	results.add(RelatedNodeDirection.PARENT);
	results.add(RelatedNodeDirection.SIBLINGS);
end

rule "ConnectNode"
when
	NodeTypeOperation(this==NodeTypeOperation.CONNECT_NODE)
then
	results.add(RelatedNodeDirection.PARENT);
	results.add(RelatedNodeDirection.SIBLINGS);
	results.add(RelatedNodeDirection.DESCENDANTS);
end

rule "Pokud v SaveDescriptionItems provedu přidání významného PP, tak dopady jsou na potomky"
when
    descItem : DescItem(type in ("ZP2015_UNIT_DATE", 
         "ZP2015_LANGUAGE", "ZP2015_ARRANGER",
         "ZP2015_UNIT_CURRENT_STATUS", "ZP2015_LANGUAGE",
         "ZP2015_UNIT_SOURCE"
         ), 
    	change in ( DescItemChange.CREATE, DescItemChange.DELETE)
    	)
    NodeTypeOperation(this==NodeTypeOperation.SAVE_DESC_ITEM)
then
	results.add(RelatedNodeDirection.DESCENDANTS);
end


/*

rule "Pokud v SaveDescriptionItems provedu smazání hodnoty ZP2015_TITLE, tak dopady jsou Node+Descendants"
when
    descItem : DescItem(type == "ZP2015_LEVEL_TYPE", change == DescItemChange.DELETE)
	eval( nodeTypeOperation.equals(NodeTypeOperation.SAVE_DESC_ITEM) )
then
	results.add(RelatedNodeDirection.NODE);
	results.add(RelatedNodeDirection.DESCENDANTS);
end
*/
