package ZP2015_ObsahStrukturovany;

import cz.tacr.elza.domain.RulItemTypeExt;
import cz.tacr.elza.domain.RulItemType;
import cz.tacr.elza.domain.RulItemSpec;
import cz.tacr.elza.domain.RulItemSpecExt;
import cz.tacr.elza.drools.model.AvailableDescItems;
import cz.tacr.elza.drools.model.ActiveLevel;
import cz.tacr.elza.drools.model.Level;
import cz.tacr.elza.drools.model.DescItem;
import cz.tacr.elza.drools.model.StructObjItem;

//----------------------------------------------
// Obsah - strukturovaný
//----------------------------------------------

rule "Obsah - strukturovaný - možný prvek Role entit (TEXT)"
no-loop
when
    $activeLevel : ActiveLevel( parent!=null && $parentDescItems: parent.descItems )
    DescItem(type == "ZP2015_LEVEL_TYPE" && specCode in ( "ZP2015_LEVEL_SERIES", "ZP2015_LEVEL_FOLDER", "ZP2015_LEVEL_ITEM", "ZP2015_LEVEL_PART" ) ) from $activeLevel.ownDescItems
    $itemType : RulItemTypeExt(code == "ZP2015_ENTITY_ROLE_TEXT")     
then
    $itemType.setMinType(RulItemType.Type.POSSIBLE);
end
