package cz.tacr.elza.ws.digitization.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-08T12:27:09.188+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://elza.tacr.cz/ws/digitization/v1", name = "DigitizationFrontdesk")
@XmlSeeAlso({cz.tacr.elza.ws.types.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DigitizationFrontdesk {

    /**
     * Post new digitization request.
     */
    @WebMethod(operationName = "PostRequest", action = "http://tacr.elza.cz/ws/digitization/postRequest")
    @WebResult(name = "requestId", targetNamespace = "", partName = "requestId")
    public java.lang.String postRequest(
        @WebParam(partName = "digitizationRequest", name = "digitizationRequest", targetNamespace = "")
        cz.tacr.elza.ws.types.v1.DigitizationRequest digitizationRequest
    ) throws DigitizationServiceException;
}
