
package cz.tacr.elza.ws.digitization.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-12-08T12:27:09.168+01:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "errorDescription", targetNamespace = "http://elza.tacr.cz/ws/types/v1")
public class DigitizationServiceException extends Exception {
    
    private cz.tacr.elza.ws.types.v1.ErrorDescription errorDescription;

    public DigitizationServiceException() {
        super();
    }
    
    public DigitizationServiceException(String message) {
        super(message);
    }
    
    public DigitizationServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public DigitizationServiceException(String message, cz.tacr.elza.ws.types.v1.ErrorDescription errorDescription) {
        super(message);
        this.errorDescription = errorDescription;
    }

    public DigitizationServiceException(String message, cz.tacr.elza.ws.types.v1.ErrorDescription errorDescription, Throwable cause) {
        super(message, cause);
        this.errorDescription = errorDescription;
    }

    public cz.tacr.elza.ws.types.v1.ErrorDescription getFaultInfo() {
        return this.errorDescription;
    }
}
