elza:
  debug:
    clientLog: true
    # Enable performance logger, each REST request is logged
    performanceLogger: false
    h2:
       # Enable H2 DB console on URL .../console
       console: false

  # ISO code of locale
  locale: cs

  export:
    mapviewer:
        url: "https://www.lightcomp.cz/extra/mapview/?wkb="

  # Integration settings
  #  URL for integration JavaScript
  # integrationScriptUrl: /elzainteg/integ.js  

  workingDir: ./work

  asyncActions:
    node:
      threadCount: 4
      maxPerFund: 2
    bulk:
      threadCount: 4
      maxPerFund: 1
    output:
      threadCount: 4
      maxPerFund: 1

  # Scope obsahující entity nelze standardně smazat
  # Povolením této volby je možné odstranit scope
  # a navázané ApState
  scope:
    deleteWithEntities: false

  # Příznak kontroly datové struktury
  ap:
    checkDb: false

#  hibernate:
#    index:
#      enabled: true
#      refresh_rate: 60000
#      batch_size: 100
#      thread_max: 4

# swagger-ui custom path
springdoc:
  swagger-ui:
    #path: /swagger-ui.html
    path: /swagger

spring:
  application:
     name: elza
     version: ${project.parent.version}
  datasource:
    url: ${elza.data.url}
    username: ${elza.data.user}
    password: ${elza.data.pass}
    hikari:
      # Prodlouzeni doby cekani na transakci
      connectionTimeout: 300000
      # Zvyseni poctu pripojeni do DB z duvodu behu paralelnich transakci pri validacich
      maximumPoolSize: 20
  main:
    # Povolit předefinování beans
    allow-bean-definition-overriding: true
    # Povolit kruhové odkazy mezi beans
    allow-circular-references: true
  data:
    rest:
      base-uri: /rest
  app:
      buildType: REL
  jackson:
      serialization:
          WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    # pametova databaze automaticky zapina hibernate.ddl-auto: create
    hibernate.ddl-auto: none
    generate-ddl: false
    # Logovani SQL dotazu
    #show-sql: true
    properties:
      net.sf.ehcache.configurationResourceName: /ehcache.xml
      hibernate:
        search:
          coordination:
            strategy: outbox-polling
          backend:
            analysis:
              configurer: cz.tacr.elza.domain.LuceneAnalyzerConfigurer
            directory:
              root: ${elza.workingDir}/lucene/indexes
            lucene_version: LATEST
        cache:
          use_second_level_cache: true
          region:
            factory_class: jcache
          # PostgreSQL
          dialect: org.hibernate.dialect.PostgreSQLDialect
