elza:
  debug:
    clientLog: true
    # Enable performance logger, each REST request is logged
    performanceLogger: false
    h2:
       # Enable H2 DB console on URL .../console
       console: false

  # ISO code of locale
  locale: cs
  
  export:
    mapviewer:
        url: "https://www.lightcomp.cz/extra/mapview/?wkb="
 
  # Integration settings
  #  URL for integration JavaScript
  # integrationScriptUrl: /elzainteg/integ.js  

  workingDir: ./work

  asyncActions:
    node:
      threadCount: 4
      maxPerFund: 2
    bulk:
      threadCount: 4
      maxPerFund: 1
    output:
      threadCount: 4
      maxPerFund: 1

  # Scope obsahující entity nelze standardně smazat
  # Povolením této volby je možné odstranit scope 
  # a navázané ApState
  scope:
    deleteWithEntities: false

  # Příznak kontroly datové struktury
  ap:
    checkDb: false

#  hibernate:
#    index:
#      enabled: true
#      refresh_rate: 60000
#      batch_size: 100
#      thread_max: 4

# swagger-ui custom path
springdoc:
  swagger-ui:
    #path: /swagger-ui.html
    path: /swagger

spring:
  application:
     name: elza
     version: ${project.parent.version}
  datasource:
    url: ${elza.data.url}
    username: ${elza.data.user}
    password: ${elza.data.pass}
    hikari:
      # Prodlouzeni doby cekani na transakci
      connectionTimeout: 300000
      # Zvyseni poctu pripojeni do DB z duvodu behu paralelnich transakci pri validacich
      maximumPoolSize: 20

  main:
    allow-bean-definition-overriding: true
  data:
    rest:
      base-uri: /rest
  app:
      buildType: REL
  jackson:
      serialization:
          WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    #pametova databaze automaticky zapina hibernate.ddl-auto: create
    hibernate.ddl-auto: none
    generate-ddl: false
    # Logovani SQL dotazu
    #show-sql: true
    properties:
        net.sf.ehcache.configurationResourceName: /ehcache.xml
        hibernate:
            cache:
              use_second_level_cache: true
              region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

            search:
                lucene_version: LUCENE_CURRENT
                default:
                    indexBase: ${elza.workingDir}/lucene/indexes/
                    directory_provider: filesystem
                    worker:
                      backend: cz.tacr.elza.search.DbQueueProcessor

            # PostgreSQL
            dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
            # H2
            #dialect: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
            # MySQL
            #dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
            # Oracle
            #dialect: org.hibernate.spatial.dialect.oracle.OracleSpatial10gDialect
            # MSSQL
            #dialect: org.hibernate.dialect.SQLServer2008Dialect
