package drlglobal;
import cz.tacr.elza.drools.model.ItemType;
import cz.tacr.elza.drools.model.ItemSpec
import cz.tacr.elza.drools.model.RequiredType;
import cz.tacr.elza.drools.model.item.Item;
import cz.tacr.elza.drools.model.Ap;
import cz.tacr.elza.drools.model.Part;
import cz.tacr.elza.drools.model.PartType;

rule "R_EVE_002 Použití typu události"
when $it: ItemType(code == "EV_TYPE")
     $is : ItemSpec(code in ("ET_MILESTONES","ET_AWARD")) from $it.specs
then
    $is.setPossible();
end
